<?php
/**
 * Standalone generator for openapi.json and docs/api_docs.txt.
 *
 * Run from the project root:
 *   php "modules/Rest API/src/Command/generate-openapi.php"
 *
 * The Registry loads only plain-PHP definition files and the OpenApi builder
 * works on those arrays, so no database or full Gibbon bootstrap is needed.
 */

// This script lives at modules/Rest API/src/Command/generate-openapi.php
$moduleDir = realpath(__DIR__.'/../../');
if ($moduleDir === false) {
    fwrite(STDERR, "Cannot resolve module directory.\n");
    exit(1);
}

spl_autoload_register(function ($class) use ($moduleDir) {
    $prefix = 'Gibbon\\Module\\RestAPI\\';
    if (strpos($class, $prefix) !== 0) {
        return;
    }
    $path = $moduleDir.'/src/'.str_replace('\\', '/', substr($class, strlen($prefix))).'.php';
    if (file_exists($path)) {
        require $path;
    }
});

use Gibbon\Module\RestAPI\Support\OpenApi;
use Gibbon\Module\RestAPI\Resource\Registry;

$baseUrl = 'https://your-gibbon.example/modules/Rest%20API/api.php/v2';
$moduleVersion = '3.3.03';

$document = OpenApi::build($baseUrl, $moduleVersion);
$json = json_encode($document, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);

$outJson = $moduleDir.'/openapi.json';
file_put_contents($outJson, $json."\n");
echo "Wrote openapi.json (".count(Registry::all())." resources, ".count($document['paths'])." paths).\n";

$L = [];
$L[] = "# Gibbon REST API — developer reference";
$L[] = "";
$L[] = "**Base URL:** `{$baseUrl}`";
$L[] = "**Version:** {$moduleVersion}";
$L[] = "**Spec file:** `openapi.json` (OpenAPI 3.0, ready for Postman/Swagger UI)";
$L[] = "";
$L[] = "## Table of contents";
$L[] = "";
$L[] = "1. [Authentication](#authentication)";
$L[] = "2. [Rate limits](#rate-limits)";
$L[] = "3. [Error format](#error-format)";
$L[] = "4. [Reading collections](#reading-collections)";
$L[] = "5. [Writing data](#writing-data)";
$L[] = "6. [Bulk operations](#bulk-operations)";
$L[] = "7. [Exports](#exports)";
$L[] = "8. [Search and aggregation](#search-and-aggregation)";
$L[] = "9. [Relation traversal](#relation-traversal)";
$L[] = "10. [File transfers](#file-transfers)";
$L[] = "11. [Composite endpoints](#composite-endpoints)";
$L[] = "12. [Webhooks](#webhooks)";
$L[] = "13. [Batch requests](#batch-requests)";
$L[] = "14. [Resource index](#resource-index)";
$L[] = "15. [Scopes](#scopes)";
$L[] = "16. [Meta endpoints](#meta-endpoints)";
$L[] = "";
$L[] = "---";
$L[] = "";
$L[] = "## Authentication";
$L[] = "";
$L[] = "Two credential types are accepted, sent in the `Authorization` header as";
$L[] = "a bearer token.";
$L[] = "";
$L[] = "| Type | Prefix | Lifetime | Notes |";
$L[] = "|------|--------|----------|-------|";
$L[] = "| API key | `gib_` | Permanent | Long-lived, tied to a person/role, per-minute limit, IP allow-list |";
$L[] = "| User token | `tok_` | Minutes | Short-lived, from `/auth/login`, refreshable via `/auth/refresh` |";
$L[] = "";
$L[] = "### Login (password grant)";
$L[] = "";
$L[] = "```http";
$L[] = "POST /auth/login";
$L[] = "Content-Type: application/json";
$L[] = "";
$L[] = '{"username":"teacher","password":"secret","scopes":"students.read,attendance.write"}';
$L[] = "```";
$L[] = "";
$L[] = "Returns a token pair and the linked person:";
$L[] = "";
$L[] = "```json";
$L[] = "{";
$L[] = '  "data": {';
$L[] = '    "token": "tok_...",';
$L[] = '    "refreshToken": "ref_...",';
$L[] = '    "expiresIn": 120,';
$L[] = '    "user": { "tawasulPersonID": "123", "username": "teacher", "surname": "Smith" }';
$L[] = "  }";
$L[] = "}";
$L[] = "```";
$L[] = "";
$L[] = "### Refresh a token";
$L[] = "";
$L[] = "```http";
$L[] = "POST /auth/refresh";
$L[] = "Content-Type: application/json";
$L[] = "";
$L[] = '{"refreshToken":"ref_..."}';
$L[] = "```";
$L[] = "";
$L[] = "### Identify the current credential";
$L[] = "";
$L[] = "```http";
$L[] = "GET /auth/me";
$L[] = "Authorization: Bearer tok_...";
$L[] = "```";
$L[] = "";
$L[] = "Shows the credential type, granted scopes, linked person and roles.";
$L[] = "";
$L[] = "### Logout";
$L[] = "";
$L[] = "```http";
$L[] = "POST /auth/logout";
$L[] = "Authorization: Bearer tok_...";
$L[] = "```";
$L[] = "";
$L[] = "Revokes the current user token (API keys must be revoked in the Gibbon UI).";
$L[] = "";
$L[] = "---";
$L[] = "";
$L[] = "## Rate limits";
$L[] = "";
$L[] = "| Credential | Source | Default limit | Window |";
$L[] = "|------------|--------|---------------|--------|";
$L[] = "| API key | key's `rateLimit` setting | configurable | 1 minute |";
$L[] = "| User token | `tokenRateLimit` setting | 240 | 1 minute |";
$L[] = "| Login attempts | `tokenRateLimit` setting | configurable | 1 minute |";
$L[] = "";
$L[] = "Every response carries `X-RateLimit-Limit`, `X-RateLimit-Remaining` and";
$L[] = "`X-RateLimit-Reset` (Unix timestamp). Exceeding the limit returns 429.";
$L[] = "Repeated failed logins from one IP are temporarily locked out.";
$L[] = "";
$L[] = "---";
$L[] = "";
$L[] = "## Error format";
$L[] = "";
$L[] = "All errors use the same JSON shape and carry an `X-Request-Id`:";
$L[] = "";
$L[] = "```json";
$L[] = "{";
$L[] = '  "error": { "code": "forbidden", "message": "This credential does not hold the \"x.write\" scope.", "details": { ... } },';
$L[] = '  "meta": { "requestID": "req_a1b2c3d4e5f6a7b8" }';
$L[] = "}";
$L[] = "```";
$L[] = "";
$L[] = "| Status | Code | Meaning |";
$L[] = "|--------|------|---------|";
$L[] = "| 400 | bad_request | Invalid JSON or missing required parameter |";
$L[] = "| 401 | unauthorized | No credential, or it was not recognised |";
$L[] = "| 403 | forbidden | Scope missing, IP blocked, or no role permission |";
$L[] = "| 404 | not_found | Resource or record does not exist |";
$L[] = "| 405 | method_not_allowed | The HTTP method is not supported on this path |";
$L[] = "| 409 | conflict | A record with that unique value already exists |";
$L[] = "| 422 | validation_failed | Input failed validation rules |";
$L[] = "| 429 | rate_limited | Too many requests in the current window |";
$L[] = "| 503 | unavailable | The API or database is not reachable |";
$L[] = "";
$L[] = "---";
$L[] = "";
$L[] = "## Reading collections";
$L[] = "";
$L[] = "```http";
$L[] = "GET /students?page=1&pageSize=25&sort=-surname&search=John&fields=tawasulPersonID,preferredName,surname";
$L[] = "Authorization: Bearer gib_...";
$L[] = "```";
$L[] = "";
$L[] = "### Query parameters (all collections)";
$L[] = "";
$L[] = "| Parameter | Type | Description |";
$L[] = "|-----------|------|-------------|";
$L[] = "| `page` | integer | Page number, starting at 1. Defaults to 1. |";
$L[] = "| `pageSize` | integer | Records per page (max configurable). Defaults to 25. |";
$L[] = "| `sort` | string | Sort field. Prefix with `-` for descending. |";
$L[] = "| `search` | string | Free-text search across the searchable fields. |";
$L[] = "| `fields` | string | Comma-separated list of fields to return. |";
$L[] = "| `tawasulSchoolYearID` | integer | Restrict to one school year. |";
$L[] = "";
$L[] = "Each resource also accepts its own `filters` (see the resource table below).";
$L[] = "Numeric and date filters accept `<filter>From` and `<filter>To` suffixes.";
$L[] = "";
$L[] = "### Single record";
$L[] = "";
$L[] = "```http";
$L[] = "GET /students/GS001234";
$L[] = "Authorization: Bearer gib_...";
$L[] = "```";
$L[] = "";
$L[] = "---";
$L[] = "";
$L[] = "## Writing data";
$L[] = "";
$L[] = "Create, update and delete all require the `<resource>.write` scope **and** the";
$L[] = "linked Gibbon user's role to hold the matching module action (when role";
$L[] = "permissions are enforced). POST returns 201; PATCH/PUT/DELETE return 200.";
$L[] = "";
$L[] = "### Create (POST)";
$L[] = "";
$L[] = "```http";
$L[] = "POST /attendance";
$L[] = "Authorization: Bearer tok_...";
$L[] = "Content-Type: application/json";
$L[] = "";
$L[] = '{"tawasulCourseClassID":"12345","tawasulPersonID":"GS001234","date":"2026-09-18","status":"Present"}';
$L[] = "```";
$L[] = "";
$L[] = "### Partial update (PATCH)";
$L[] = "";
$L[] = "```http";
$L[] = "PATCH /attendance/ATT001";
$L[] = "Authorization: Bearer tok_...";
$L[] = "Content-Type: application/json";
$L[] = "";
$L[] = '{"status":"Late"}';
$L[] = "```";
$L[] = "";
$L[] = "### Full replace (PUT)";
$L[] = "";
$L[] = "```http";
$L[] = "PUT /attendance/ATT001";
$L[] = "Authorization: Bearer tok_...";
$L[] = "Content-Type: application/json";
$L[] = "";
$L[] = '{"tawasulCourseClassID":"12345","tawasulPersonID":"GS001234","date":"2026-09-18","status":"Present"}';
$L[] = "```";
$L[] = "";
$L[] = "PUT replaces the entire record — omit a required field and you get 422.";
$L[] = "";
$L[] = "### Delete (DELETE)";
$L[] = "";
$L[] = "```http";
$L[] = "DELETE /attendance/ATT001";
$L[] = "Authorization: Bearer tok_...";
$L[] = "```";
$L[] = "";
$L[] = "---";
$L[] = "";
$L[] = "## Bulk operations";
$L[] = "";
$L[] = "Create, update or delete up to 500 records in one transaction. Every item";
$L[] = "must succeed or the whole request is rolled back.";
$L[] = "";
$L[] = "```http";
$L[] = "POST /attendance/bulk";
$L[] = "Authorization: Bearer tok_...";
$L[] = "Content-Type: application/json";
$L[] = "";
$L[] = '{';
$L[] = '  "items": [';
$L[] = '    {"tawasulCourseClassID":"12345","tawasulPersonID":"GS001234","date":"2026-09-18","status":"Present"}';
$L[] = '  ]';
$L[] = "}";
$L[] = "```";
$L[] = "";
$L[] = "Each item is either a new object, an object with the primary key to update,";
$L[] = 'or `{"op":"delete","id":"ATT001"}` to remove a record.';
$L[] = "";
$L[] = "---";
$L[] = "";
$L[] = "## Exports";
$L[] = "";
$L[] = "Download an entire resource as CSV — no pagination, one row per record.";
$L[] = "";
$L[] = "```http";
$L[] = "GET /students/export";
$L[] = "Authorization: Bearer gib_...";
$L[] = "Accept: text/csv";
$L[] = "```";
$L[] = "";
$L[] = "---";
$L[] = "";
$L[] = "## Search and aggregation";
$L[] = "";
$L[] = "### Free-text search";
$L[] = "`GET /students?search=Smith` — searches the resource's `search` columns.";
$L[] = "";
$L[] = "### Distinct values";
$L[] = "`GET /students/distinct?field=tawasulYearGroupID` — unique non-null values for a column.";
$L[] = "";
$L[] = "### Aggregate summary";
$L[] = "`GET /attendance/aggregate?by=status` — counts grouped by one or more fields.";
$L[] = "";
$L[] = "---";
$L[] = "";
$L[] = "## Relation traversal";
$L[] = "";
$L[] = "Follow a foreign-key link from one record to its related record or list:";
$L[] = "";
$L[] = "```http";
$L[] = "GET /students/GS001234/attendance";
$L[] = "Authorization: Bearer gib_...";
$L[] = "```";
$L[] = "";
$L[] = "The relation name appears in each resource's OpenAPI spec under the path";
$L[] = "`/{resource}/{id}/{relation}`.";
$L[] = "";
$L[] = "---";
$L[] = "";
$L[] = "## File transfers";
$L[] = "";
$L[] = "File transfer is off by default. An administrator enables it in the Rest API";
$L[] = "settings. Once enabled:";
$L[] = "";
$L[] = "```http";
$L[] = "GET  /files/{resource}/{id}           # list file fields on a record";
$L[] = "GET  /files/{resource}/{id}/{field}  # download (add ?disposition=inline to view)";
$L[] = "POST /files/{resource}/{id}/{field}  # attach or replace (multipart or base64 JSON)";
$L[] = "DELETE /files/{resource}/{id}/{field}# detach and delete the file";
$L[] = "```";
$L[] = "";
$L[] = "Uploads are rejected if the extension is in the forbidden list (`.php`, `.html`,";
$L[] = "etc.) or if the file exceeds the configured maximum size (413).";
$L[] = "";
$L[] = "---";
$L[] = "";
$L[] = "## Composite endpoints";
$L[] = "";
$L[] = "Convenience endpoints that join data across multiple resources in a single call.";
$L[] = "Each part is included only when the caller holds the read scope for it.";
$L[] = "";
$L[] = "| Endpoint | Description |";
$L[] = "|----------|-------------|";
$L[] = "| `GET /students/{id}/profile` | Student, family, enrolment, timetable, attendance summary, recent behaviour |";
$L[] = "| `GET /staff/{id}/profile` | Staff member, contract, roles, departments, taught classes, absences |";
$L[] = "| `GET /families/{id}/profile` | Family, adults with contact details, children |";
$L[] = "| `GET /courses/{id}/overview` | Course, its classes, and enrolment count per class |";
$L[] = "| `GET /students/{id}/finance` | Invoices, fees and payments with outstanding totals |";
$L[] = "| `GET /students/{id}/timetable` | Timetabled periods for one person, by day |";
$L[] = "| `GET /classes/{id}/roster` | Students and teachers attached to one class |";
$L[] = "";
$L[] = "---";
$L[] = "";
$L[] = "## Webhooks";
$L[] = "";
$L[] = "When enabled, every create/update/delete is POSTed to subscribed URLs as";
$L[] = "a `{resource}.created`, `{resource}.updated`, `{resource}.replaced` or";
$L[] = "`{resource}.deleted` event. Each delivery carries an `X-Gibbon-Signature`";
$L[] = "header: `sha256=` HMAC-SHA256 of the raw body using the subscription secret.";
$L[] = "";
$L[] = "### Subscribe";
$L[] = "";
$L[] = "```http";
$L[] = "POST /webhooks";
$L[] = "Authorization: Bearer tok_...";
$L[] = "Content-Type: application/json";
$L[] = "";
$L[] = '{"name":"Attendance changes","url":"https://hooks.example.com/gibbon","events":"attendance.created,attendance.updated"}';
$L[] = "```";
$L[] = "";
$L[] = "---";
$L[] = "";
$L[] = "## Batch requests";
$L[] = "";
$L[] = "Send multiple API calls in one HTTP request to reduce round-trips:";
$L[] = "";
$L[] = "```http";
$L[] = "POST /batch";
$L[] = "Authorization: Bearer tok_...";
$L[] = "Content-Type: application/json";
$L[] = "";
$L[] = '{"requests":[{"method":"GET","path":"/students?pageSize=1"},{"method":"GET","path":"/classes/A24"}]}';
$L[] = "```";
$L[] = "";
$L[] = "Returns an array of per-request responses, each with its own status code.";
$L[] = "";
$L[] = "---";
$L[] = "";
$L[] = "## Resource index";
$L[] = "";
$L[] = "Resources are grouped by area. Each supports `GET` (collection and single),";
$L[] = "and most support `POST`, `PATCH`, `PUT`, `DELETE`. Read the full OpenAPI spec";
$L[] = "at `GET /openapi.json` for field types, filters and exact parameters.";
$L[] = "";

foreach (Registry::groups() as $group => $resources) {
    $L[] = "";
    $L[] = "### {$group}";
    $L[] = "";
    $L[] = "| Resource | Title | Methods | Read scope | Write scope |";
    $L[] = "|----------|-------|---------|------------|-------------|";
    foreach ($resources as $name => $resource) {
        $methods = implode(',', $resource['methods']);
        $readScope  = '`'.$resource['scope'].'.read`';
        $writeScope = in_array('POST', $resource['methods'], true) ||
                      in_array('PATCH', $resource['methods'], true) ||
                      in_array('PUT', $resource['methods'], true) ||
                      in_array('DELETE', $resource['methods'], true)
            ? '`'.$resource['scope'].'.write`'
            : '—';
        $L[] = "| `{$name}` | {$resource['title']} | {$methods} | {$readScope} | {$writeScope} |";
    }
}

$L[] = "";
$L[] = "---";
$L[] = "";
$L[] = "## Scopes";
$L[] = "";
$L[] = "Credentials carry a set of scopes. `*` grants everything; otherwise each";
$L[] = "resource lists `read` and (optionally) `write`:";
$L[] = "";
$L[] = "| Scope | Description |";
$L[] = "|------|-------------|";
foreach (Registry::scopes() as $scope => $desc) {
    $L[] = "| `{$scope}` | {$desc} |";
}

$L[] = "";
$L[] = "---";
$L[] = "";
$L[] = "## Meta endpoints";
$L[] = "";
$L[] = "| Endpoint | Auth | Description |";
$L[] = "|----------|------|-------------|";
$L[] = "| `GET /` | — | API index with links |";
$L[] = "| `GET /health` | — | Service health check |";
$L[] = "| `GET /scopes` | — | All scopes an API key can hold |";
$L[] = "| `GET /resources` | — | Every available resource with methods and filters |";
$L[] = "| `GET /events` | — | All webhook event types |";
$L[] = "| `GET /stats` | yes | School-wide counts and API usage |";
$L[] = "| `GET /dashboard` | yes | Current-user dashboard data |";
$L[] = "| `GET /permissions` | yes | Actions the current user can perform |";
$L[] = "| `GET /analytics` | yes | Request analytics and trends (pass `?days=7`) |";
$L[] = "| `GET /openapi.json` | yes | This OpenAPI 3 specification |";

$L[] = "";
$L[] = "---";
$L[] = "";
$L[] = "## HTTP method summary";
$L[] = "";
$L[] = "| Method | Meaning |";
$L[] = "|--------|---------|";
$L[] = "| `GET` | Read a collection or a single record |";
$L[] = "| `POST` | Create a record (or bulk create via `/bulk`) |";
$L[] = "| `PATCH` | Partial update — only the fields sent are changed |";
$L[] = "| `PUT` | Full replace — the entire record is overwritten |";
$L[] = "| `DELETE` | Remove a record |";
$L[] = "| `OPTIONS` | CORS preflight |";

$L[] = "";
$L[] = "---";
$L[] = "";
$L[] = "_Generated from the live resource registry by `modules/Rest API/src/Command/generate-openapi.php`._";

file_put_contents($moduleDir.'/docs/api_docs.txt', implode("\n", $L)."\n");
echo "Wrote docs/api_docs.txt.\n";
