<?php
/*
Academics: courses, classes, enrolments, units, lesson planner, markbook,
timetable and homework.
*/

return [

'courses' => [
    'title' => 'Courses',
    'group' => 'Academics',
    'scope' => 'courses',
    'module' => 'TawasulTimetableAdmin',
    'action' => 'Manage Courses & Classes',
    'table' => 'tawasulCourse',
    'primaryKey' => 'tawasulCourseID',
    'description' => 'Courses offered in a school year, grouped by department.',
    'select' => "SELECT tawasulCourse.tawasulCourseID, tawasulCourse.tawasulSchoolYearID, tawasulCourse.tawasulDepartmentID, tawasulDepartment.name AS departmentName, tawasulCourse.name, tawasulCourse.nameShort, tawasulCourse.description, tawasulCourse.tawasulYearGroupIDList, tawasulCourse.orderBy, (SELECT COUNT(*) FROM tawasulCourseClass WHERE tawasulCourseClass.tawasulCourseID=tawasulCourse.tawasulCourseID) AS classCount FROM tawasulCourse LEFT JOIN tawasulDepartment ON (tawasulCourse.tawasulDepartmentID=tawasulDepartment.tawasulDepartmentID)",
    'yearFilter' => 'tawasulCourse.tawasulSchoolYearID',
    'filters' => ['tawasulDepartmentID' => 'tawasulCourse.tawasulDepartmentID', 'nameShort' => 'tawasulCourse.nameShort'],
    'search' => ['tawasulCourse.name', 'tawasulCourse.nameShort'],
    'sort' => ['name' => 'tawasulCourse.name', 'nameShort' => 'tawasulCourse.nameShort'],
    'defaultSort' => 'tawasulCourse.nameShort',
    'writable' => ['tawasulSchoolYearID', 'tawasulDepartmentID', 'name', 'nameShort', 'description', 'map', 'tawasulYearGroupIDList', 'orderBy'],
    'required' => ['tawasulSchoolYearID', 'name', 'nameShort'],
    'methods' => ['GET', 'POST', 'PATCH', 'PUT', 'DELETE'],
],

'classes' => [
    'title' => 'Classes',
    'group' => 'Academics',
    'scope' => 'classes',
    'module' => 'TawasulTimetableAdmin',
    'action' => 'Manage Courses & Classes',
    'table' => 'tawasulCourseClass',
    'primaryKey' => 'tawasulCourseClassID',
    'description' => 'Class groups within a course, with enrolment counts.',
    'select' => "SELECT tawasulCourseClass.tawasulCourseClassID, tawasulCourseClass.tawasulCourseID, tawasulCourseClass.name, tawasulCourseClass.nameShort, tawasulCourseClass.reportable, tawasulCourseClass.attendance, tawasulCourseClass.enrolmentMin, tawasulCourseClass.enrolmentMax, tawasulCourseClass.tawasulScaleIDTarget, tawasulCourse.name AS courseName, tawasulCourse.nameShort AS courseNameShort, tawasulCourse.tawasulSchoolYearID, tawasulCourse.tawasulDepartmentID, (SELECT COUNT(*) FROM tawasulCourseClassPerson WHERE tawasulCourseClassPerson.tawasulCourseClassID=tawasulCourseClass.tawasulCourseClassID AND role='Student') AS studentCount FROM tawasulCourseClass JOIN tawasulCourse ON (tawasulCourseClass.tawasulCourseID=tawasulCourse.tawasulCourseID)",
    'yearFilter' => 'tawasulCourse.tawasulSchoolYearID',
    'filters' => ['tawasulCourseID' => 'tawasulCourseClass.tawasulCourseID', 'tawasulDepartmentID' => 'tawasulCourse.tawasulDepartmentID', 'attendance' => 'tawasulCourseClass.attendance', 'reportable' => 'tawasulCourseClass.reportable'],
    'search' => ['tawasulCourseClass.name', 'tawasulCourseClass.nameShort', 'tawasulCourse.name', 'tawasulCourse.nameShort'],
    'sort' => ['name' => 'tawasulCourseClass.name', 'course' => 'tawasulCourse.nameShort'],
    'defaultSort' => 'tawasulCourse.nameShort, tawasulCourseClass.nameShort',
    'writable' => ['tawasulCourseID', 'name', 'nameShort', 'reportable', 'attendance', 'enrolmentMin', 'enrolmentMax', 'tawasulScaleIDTarget'],
    'required' => ['tawasulCourseID', 'name', 'nameShort'],
    'methods' => ['GET', 'POST', 'PATCH', 'PUT', 'DELETE'],
],

'class-enrolments' => [
    'title' => 'Class Enrolments',
    'group' => 'Academics',
    'scope' => 'enrolments',
    'module' => 'TawasulTimetableAdmin',
    'action' => 'Manage Courses & Classes',
    'table' => 'tawasulCourseClassPerson',
    'primaryKey' => 'tawasulCourseClassPersonID',
    'description' => 'Students and teachers attached to a class.',
    'select' => "SELECT tawasulCourseClassPerson.tawasulCourseClassPersonID, tawasulCourseClassPerson.tawasulCourseClassID, tawasulCourseClassPerson.tawasulPersonID, tawasulCourseClassPerson.role, tawasulCourseClassPerson.dateEnrolled, tawasulCourseClassPerson.dateUnenrolled, tawasulCourseClassPerson.reportable, tawasulPerson.surname, tawasulPerson.preferredName, tawasulPerson.username, tawasulPerson.studentID, tawasulPerson.image_240, tawasulCourseClass.name AS className, tawasulCourseClass.nameShort AS classNameShort, tawasulCourse.name AS courseName, tawasulCourse.nameShort AS courseNameShort, tawasulCourse.tawasulSchoolYearID FROM tawasulCourseClassPerson JOIN tawasulPerson ON (tawasulCourseClassPerson.tawasulPersonID=tawasulPerson.tawasulPersonID) JOIN tawasulCourseClass ON (tawasulCourseClassPerson.tawasulCourseClassID=tawasulCourseClass.tawasulCourseClassID) JOIN tawasulCourse ON (tawasulCourseClass.tawasulCourseID=tawasulCourse.tawasulCourseID)",
    'yearFilter' => 'tawasulCourse.tawasulSchoolYearID',
    'filters' => ['tawasulCourseClassID' => 'tawasulCourseClassPerson.tawasulCourseClassID', 'tawasulPersonID' => 'tawasulCourseClassPerson.tawasulPersonID', 'role' => 'tawasulCourseClassPerson.role', 'tawasulCourseID' => 'tawasulCourseClass.tawasulCourseID'],
    'search' => ['tawasulPerson.surname', 'tawasulPerson.preferredName', 'tawasulPerson.username'],
    'defaultSort' => 'tawasulCourseClassPerson.role, tawasulPerson.surname',
    'writable' => ['tawasulCourseClassID', 'tawasulPersonID', 'role', 'dateEnrolled', 'dateUnenrolled', 'reportable'],
    'required' => ['tawasulCourseClassID', 'tawasulPersonID', 'role'],
    'methods' => ['GET', 'POST', 'PATCH', 'PUT', 'DELETE'],
],

'units' => [
    'title' => 'Units',
    'group' => 'Academics',
    'scope' => 'units',
    'module' => 'TawasulPlanner',
    'action' => 'Unit Planner',
    'table' => 'tawasulUnit',
    'primaryKey' => 'tawasulUnitID',
    'description' => 'Units of work attached to a course.',
    'select' => "SELECT tawasulUnit.tawasulUnitID, tawasulUnit.tawasulCourseID, tawasulUnit.name, tawasulUnit.active, tawasulUnit.description, tawasulUnit.tags, tawasulUnit.ordering, tawasulUnit.sharedPublic, tawasulUnit.license, tawasulCourse.name AS courseName, tawasulCourse.tawasulSchoolYearID FROM tawasulUnit JOIN tawasulCourse ON (tawasulUnit.tawasulCourseID=tawasulCourse.tawasulCourseID)",
    'yearFilter' => 'tawasulCourse.tawasulSchoolYearID',
    'filters' => ['tawasulCourseID' => 'tawasulUnit.tawasulCourseID', 'active' => 'tawasulUnit.active'],
    'search' => ['tawasulUnit.name', 'tawasulUnit.tags'],
    'defaultSort' => 'tawasulUnit.ordering, tawasulUnit.name',
],

'lessons' => [
    'title' => 'Lessons',
    'group' => 'Academics',
    'scope' => 'planner',
    'module' => 'TawasulPlanner',
    'action' => 'Lesson Planner',
    'table' => 'tawasulPlannerEntry',
    'primaryKey' => 'tawasulPlannerEntryID',
    'description' => 'Lesson planner entries, including homework details.',
    'select' => "SELECT tawasulPlannerEntry.tawasulPlannerEntryID, tawasulPlannerEntry.tawasulCourseClassID, tawasulPlannerEntry.tawasulUnitID, tawasulPlannerEntry.date, tawasulPlannerEntry.timeStart, tawasulPlannerEntry.timeEnd, tawasulPlannerEntry.name, tawasulPlannerEntry.summary, tawasulPlannerEntry.description, tawasulPlannerEntry.homework, tawasulPlannerEntry.homeworkDueDateTime, tawasulPlannerEntry.homeworkDetails, tawasulPlannerEntry.homeworkSubmission, tawasulPlannerEntry.viewableStudents, tawasulPlannerEntry.viewableParents, tawasulCourseClass.name AS className, tawasulCourse.nameShort AS courseNameShort, tawasulCourse.tawasulSchoolYearID FROM tawasulPlannerEntry JOIN tawasulCourseClass ON (tawasulPlannerEntry.tawasulCourseClassID=tawasulCourseClass.tawasulCourseClassID) JOIN tawasulCourse ON (tawasulCourseClass.tawasulCourseID=tawasulCourse.tawasulCourseID)",
    'yearFilter' => 'tawasulCourse.tawasulSchoolYearID',
    'filters' => ['tawasulCourseClassID' => 'tawasulPlannerEntry.tawasulCourseClassID', 'tawasulUnitID' => 'tawasulPlannerEntry.tawasulUnitID', 'date' => 'tawasulPlannerEntry.date', 'homework' => 'tawasulPlannerEntry.homework'],
    'search' => ['tawasulPlannerEntry.name', 'tawasulPlannerEntry.summary'],
    'sort' => ['date' => 'tawasulPlannerEntry.date', 'name' => 'tawasulPlannerEntry.name'],
    'defaultSort' => 'tawasulPlannerEntry.date DESC, tawasulPlannerEntry.timeStart',
    'writable' => ['tawasulCourseClassID', 'tawasulUnitID', 'date', 'timeStart', 'timeEnd', 'name', 'summary', 'description', 'teachersNotes', 'homework', 'homeworkDueDateTime', 'homeworkDetails', 'viewableStudents', 'viewableParents'],
    'required' => ['tawasulCourseClassID', 'date', 'timeStart', 'timeEnd', 'name'],
    'methods' => ['GET', 'POST', 'PATCH', 'PUT', 'DELETE'],
],

'markbook-columns' => [
    'title' => 'Markbook Columns',
    'group' => 'Academics',
    'scope' => 'markbook',
    'module' => 'TawasulMarkbook',
    'action' => 'View Markbook',
    'writeAction' => 'Edit Markbook',
    'table' => 'tawasulMarkbookColumn',
    'primaryKey' => 'tawasulMarkbookColumnID',
    'description' => 'Assessment columns in a class markbook.',
    'select' => "SELECT tawasulMarkbookColumn.tawasulMarkbookColumnID, tawasulMarkbookColumn.tawasulCourseClassID, tawasulMarkbookColumn.tawasulUnitID, tawasulMarkbookColumn.tawasulPlannerEntryID, tawasulMarkbookColumn.tawasulSchoolYearTermID, tawasulMarkbookColumn.type, tawasulMarkbookColumn.name, tawasulMarkbookColumn.description, tawasulMarkbookColumn.date, tawasulMarkbookColumn.sequenceNumber, tawasulMarkbookColumn.attainment, tawasulMarkbookColumn.tawasulScaleIDAttainment, tawasulMarkbookColumn.attainmentWeighting, tawasulMarkbookColumn.attainmentRawMax, tawasulMarkbookColumn.effort, tawasulMarkbookColumn.tawasulScaleIDEffort, tawasulMarkbookColumn.comment, tawasulMarkbookColumn.complete, tawasulMarkbookColumn.completeDate, tawasulMarkbookColumn.viewableStudents, tawasulMarkbookColumn.viewableParents, tawasulCourseClass.name AS className, tawasulCourse.nameShort AS courseNameShort, tawasulCourse.tawasulSchoolYearID FROM tawasulMarkbookColumn JOIN tawasulCourseClass ON (tawasulMarkbookColumn.tawasulCourseClassID=tawasulCourseClass.tawasulCourseClassID) JOIN tawasulCourse ON (tawasulCourseClass.tawasulCourseID=tawasulCourse.tawasulCourseID)",
    'yearFilter' => 'tawasulCourse.tawasulSchoolYearID',
    'filters' => ['tawasulCourseClassID' => 'tawasulMarkbookColumn.tawasulCourseClassID', 'complete' => 'tawasulMarkbookColumn.complete', 'type' => 'tawasulMarkbookColumn.type', 'tawasulSchoolYearTermID' => 'tawasulMarkbookColumn.tawasulSchoolYearTermID'],
    'search' => ['tawasulMarkbookColumn.name', 'tawasulMarkbookColumn.description'],
    'sort' => ['date' => 'tawasulMarkbookColumn.date', 'sequenceNumber' => 'tawasulMarkbookColumn.sequenceNumber'],
    'defaultSort' => 'tawasulMarkbookColumn.date DESC, tawasulMarkbookColumn.sequenceNumber',
    'writable' => ['tawasulCourseClassID', 'tawasulUnitID', 'tawasulPlannerEntryID', 'tawasulSchoolYearTermID', 'type', 'name', 'description', 'date', 'sequenceNumber', 'attainment', 'tawasulScaleIDAttainment', 'attainmentWeighting', 'attainmentRawMax', 'effort', 'tawasulScaleIDEffort', 'comment', 'complete', 'completeDate', 'viewableStudents', 'viewableParents'],
    'required' => ['tawasulCourseClassID', 'type', 'name', 'date'],
    'methods' => ['GET', 'POST', 'PATCH', 'PUT', 'DELETE'],
],

'markbook-entries' => [
    'title' => 'Markbook Entries',
    'group' => 'Academics',
    'scope' => 'markbook',
    'module' => 'TawasulMarkbook',
    'action' => 'View Markbook',
    'writeAction' => 'Edit Markbook',
    'table' => 'tawasulMarkbookEntry',
    'primaryKey' => 'tawasulMarkbookEntryID',
    'description' => 'Individual student results against a markbook column.',
    'select' => "SELECT tawasulMarkbookEntry.tawasulMarkbookEntryID, tawasulMarkbookEntry.tawasulMarkbookColumnID, tawasulMarkbookEntry.tawasulPersonIDStudent, tawasulMarkbookEntry.attainmentValue, tawasulMarkbookEntry.attainmentValueRaw, tawasulMarkbookEntry.attainmentDescriptor, tawasulMarkbookEntry.attainmentConcern, tawasulMarkbookEntry.effortValue, tawasulMarkbookEntry.effortDescriptor, tawasulMarkbookEntry.effortConcern, tawasulMarkbookEntry.comment, tawasulMarkbookEntry.modifiedAssessment, tawasulPerson.surname, tawasulPerson.preferredName, tawasulPerson.studentID, tawasulMarkbookColumn.name AS columnName, tawasulMarkbookColumn.tawasulCourseClassID, tawasulCourse.tawasulSchoolYearID FROM tawasulMarkbookEntry JOIN tawasulMarkbookColumn ON (tawasulMarkbookEntry.tawasulMarkbookColumnID=tawasulMarkbookColumn.tawasulMarkbookColumnID) JOIN tawasulPerson ON (tawasulMarkbookEntry.tawasulPersonIDStudent=tawasulPerson.tawasulPersonID) JOIN tawasulCourseClass ON (tawasulMarkbookColumn.tawasulCourseClassID=tawasulCourseClass.tawasulCourseClassID) JOIN tawasulCourse ON (tawasulCourseClass.tawasulCourseID=tawasulCourse.tawasulCourseID)",
    'yearFilter' => 'tawasulCourse.tawasulSchoolYearID',
    'filters' => ['tawasulMarkbookColumnID' => 'tawasulMarkbookEntry.tawasulMarkbookColumnID', 'tawasulPersonIDStudent' => 'tawasulMarkbookEntry.tawasulPersonIDStudent', 'tawasulCourseClassID' => 'tawasulMarkbookColumn.tawasulCourseClassID', 'attainmentConcern' => 'tawasulMarkbookEntry.attainmentConcern'],
    'search' => ['tawasulPerson.surname', 'tawasulPerson.preferredName'],
    'defaultSort' => 'tawasulPerson.surname, tawasulPerson.preferredName',
    'writable' => ['tawasulMarkbookColumnID', 'tawasulPersonIDStudent', 'attainmentValue', 'attainmentValueRaw', 'attainmentDescriptor', 'attainmentConcern', 'effortValue', 'effortDescriptor', 'effortConcern', 'comment', 'modifiedAssessment'],
    'required' => ['tawasulMarkbookColumnID', 'tawasulPersonIDStudent'],
    'methods' => ['GET', 'POST', 'PATCH', 'PUT', 'DELETE'],
],

'timetables' => [
    'title' => 'Timetables',
    'group' => 'Academics',
    'scope' => 'timetable',
    'module' => 'TawasulTimetableAdmin',
    'action' => 'Manage Timetables',
    'table' => 'tawasulTT',
    'primaryKey' => 'tawasulTTID',
    'description' => 'Timetables defined for a school year.',
    'select' => "SELECT tawasulTT.* FROM tawasulTT",
    'yearFilter' => 'tawasulTT.tawasulSchoolYearID',
    'filters' => ['active' => 'tawasulTT.active'],
    'search' => ['tawasulTT.name', 'tawasulTT.nameShort'],
    'defaultSort' => 'tawasulTT.name',
],

'timetable-days' => [
    'title' => 'Timetable Days',
    'group' => 'Academics',
    'scope' => 'timetable',
    'module' => 'TawasulTimetableAdmin',
    'action' => 'Manage Timetables',
    'table' => 'tawasulTTDay',
    'primaryKey' => 'tawasulTTDayID',
    'description' => 'Days within a timetable cycle.',
    'select' => "SELECT tawasulTTDay.*, tawasulTT.name AS timetableName, tawasulTT.tawasulSchoolYearID FROM tawasulTTDay JOIN tawasulTT ON (tawasulTTDay.tawasulTTID=tawasulTT.tawasulTTID)",
    'yearFilter' => 'tawasulTT.tawasulSchoolYearID',
    'filters' => ['tawasulTTID' => 'tawasulTTDay.tawasulTTID'],
    'defaultSort' => 'tawasulTTDay.tawasulTTID, tawasulTTDay.name',
],

'timetable-periods' => [
    'title' => 'Timetable Periods',
    'group' => 'Academics',
    'scope' => 'timetable',
    'module' => 'TawasulTimetableAdmin',
    'action' => 'Manage Timetables',
    'table' => 'tawasulTTColumnRow',
    'primaryKey' => 'tawasulTTColumnRowID',
    'description' => 'Period rows and their start and end times.',
    'select' => "SELECT tawasulTTColumnRow.*, tawasulTTColumn.name AS columnName FROM tawasulTTColumnRow JOIN tawasulTTColumn ON (tawasulTTColumnRow.tawasulTTColumnID=tawasulTTColumn.tawasulTTColumnID)",
    'filters' => ['tawasulTTColumnID' => 'tawasulTTColumnRow.tawasulTTColumnID', 'type' => 'tawasulTTColumnRow.type'],
    'defaultSort' => 'tawasulTTColumnRow.timeStart',
],

'timetable-slots' => [
    'title' => 'Timetable Slots',
    'group' => 'Academics',
    'scope' => 'timetable',
    'module' => 'TawasulTimetableAdmin',
    'action' => 'Manage Timetables',
    'table' => 'tawasulTTDayRowClass',
    'primaryKey' => 'tawasulTTDayRowClassID',
    'description' => 'Scheduled class slots: which class meets in which period, day and room.',
    'select' => "SELECT tawasulTTDayRowClass.tawasulTTDayRowClassID, tawasulTTDayRowClass.tawasulTTDayID, tawasulTTDayRowClass.tawasulTTColumnRowID, tawasulTTDayRowClass.tawasulCourseClassID, tawasulTTDayRowClass.tawasulSpaceID, tawasulTTColumnRow.name AS periodName, tawasulTTColumnRow.timeStart, tawasulTTColumnRow.timeEnd, tawasulTTDay.name AS dayName, tawasulTTDay.tawasulTTID, tawasulSpace.name AS spaceName, tawasulCourseClass.name AS className, tawasulCourseClass.nameShort AS classNameShort, tawasulCourse.name AS courseName, tawasulCourse.nameShort AS courseNameShort, tawasulCourse.tawasulSchoolYearID FROM tawasulTTDayRowClass JOIN tawasulTTColumnRow ON (tawasulTTDayRowClass.tawasulTTColumnRowID=tawasulTTColumnRow.tawasulTTColumnRowID) JOIN tawasulTTDay ON (tawasulTTDayRowClass.tawasulTTDayID=tawasulTTDay.tawasulTTDayID) JOIN tawasulCourseClass ON (tawasulTTDayRowClass.tawasulCourseClassID=tawasulCourseClass.tawasulCourseClassID) JOIN tawasulCourse ON (tawasulCourseClass.tawasulCourseID=tawasulCourse.tawasulCourseID) LEFT JOIN tawasulSpace ON (tawasulTTDayRowClass.tawasulSpaceID=tawasulSpace.tawasulSpaceID)",
    'yearFilter' => 'tawasulCourse.tawasulSchoolYearID',
    'filters' => ['tawasulTTDayID' => 'tawasulTTDayRowClass.tawasulTTDayID', 'tawasulCourseClassID' => 'tawasulTTDayRowClass.tawasulCourseClassID', 'tawasulSpaceID' => 'tawasulTTDayRowClass.tawasulSpaceID', 'tawasulTTID' => 'tawasulTTDay.tawasulTTID'],
    'defaultSort' => 'tawasulTTColumnRow.timeStart',
],

'timetable-dates' => [
    'title' => 'Timetable Dates',
    'group' => 'Academics',
    'scope' => 'timetable',
    'module' => 'TawasulTimetableAdmin',
    'action' => 'Manage Timetables',
    'table' => 'tawasulTTDayDate',
    'primaryKey' => 'tawasulTTDayDateID',
    'description' => 'Maps calendar dates onto timetable cycle days.',
    'select' => "SELECT tawasulTTDayDate.*, tawasulTTDay.name AS dayName, tawasulTTDay.tawasulTTID FROM tawasulTTDayDate JOIN tawasulTTDay ON (tawasulTTDayDate.tawasulTTDayID=tawasulTTDay.tawasulTTDayID)",
    'filters' => ['date' => 'tawasulTTDayDate.date', 'tawasulTTDayID' => 'tawasulTTDayDate.tawasulTTDayID', 'tawasulTTID' => 'tawasulTTDay.tawasulTTID'],
    'sort' => ['date' => 'tawasulTTDayDate.date'],
    'defaultSort' => 'tawasulTTDayDate.date',
],

'analytics-cache' => [
    'title' => 'Analytics Cache',
    'group' => 'Modules: Learning Analytics',
    'scope' => 'analytics',
    'module' => 'Learning Analytics',
    'action' => 'Learning Analytics Dashboard',
    'table' => 'analyticsCache',
    'primaryKey' => 'analyticsCacheID',
    'description' => 'Cached analytics results from the Learning Analytics module.',
    'select' => "SELECT * FROM analyticsCache",
    'filters' => ['dataType' => 'analyticsCache.dataType', 'scope' => 'analyticsCache.scope'],
    'sort' => ['computedAt' => 'analyticsCache.computedAt'],
    'defaultSort' => 'analyticsCache.computedAt DESC',
    'methods' => ['GET', 'POST', 'PATCH', 'PUT', 'DELETE'],
],

];
