<?php
/*
Community module resources.

Each entry names the Gibbon module it belongs to. The dispatcher skips any
resource whose module is not installed and active, and the whole group is
hidden unless the "Expose community modules" setting is enabled, so this file
is safe on a school that runs none of them.

Schemas verified against each module's own manifest.php / CHANGEDB.php.
*/

return [

'badges' => [
    'title' => 'Badges',
    'group' => 'Modules: Badges',
    'scope' => 'badges',
    'module' => 'Badges',
    'action' => 'Manage Badges',
    'table' => 'badgesBadge',
    'primaryKey' => 'badgesBadgeID',
    'description' => 'Badge definitions from the Badges module.',
    'select' => "SELECT badgesBadge.badgesBadgeID, badgesBadge.name, badgesBadge.category, badgesBadge.description, badgesBadge.active, badgesBadge.logo, badgesBadge.timestampCreated FROM badgesBadge",
    'filters' => ['active' => 'badgesBadge.active', 'category' => 'badgesBadge.category'],
    'search' => ['badgesBadge.name', 'badgesBadge.description'],
    'defaultSort' => 'badgesBadge.name',
],

'badge-awards' => [
    'title' => 'Badge Awards',
    'group' => 'Modules: Badges',
    'scope' => 'badges',
    'module' => 'Badges',
    'action' => 'Manage Badges',
    'table' => 'badgesBadgeStudent',
    'primaryKey' => 'badgesBadgeStudentID',
    'description' => 'Badges awarded to students.',
    'select' => "SELECT badgesBadgeStudent.badgesBadgeStudentID, badgesBadgeStudent.badgesBadgeID, badgesBadgeStudent.tawasulSchoolYearID, badgesBadgeStudent.tawasulPersonID, badgesBadgeStudent.date, badgesBadgeStudent.comment, badgesBadgeStudent.timestamp, badgesBadge.name AS badgeName, tawasulPerson.surname, tawasulPerson.preferredName FROM badgesBadgeStudent JOIN badgesBadge ON (badgesBadgeStudent.badgesBadgeID=badgesBadge.badgesBadgeID) JOIN tawasulPerson ON (badgesBadgeStudent.tawasulPersonID=tawasulPerson.tawasulPersonID)",
    'yearFilter' => 'badgesBadgeStudent.tawasulSchoolYearID',
    'filters' => ['badgesBadgeID' => 'badgesBadgeStudent.badgesBadgeID', 'tawasulPersonID' => 'badgesBadgeStudent.tawasulPersonID', 'date' => 'badgesBadgeStudent.date'],
    'search' => ['tawasulPerson.surname', 'tawasulPerson.preferredName', 'badgesBadge.name'],
    'defaultSort' => 'badgesBadgeStudent.date DESC',
    'writable' => ['badgesBadgeID', 'tawasulSchoolYearID', 'tawasulPersonID', 'date', 'comment', 'tawasulPersonIDCreator'],
    'required' => ['badgesBadgeID', 'tawasulSchoolYearID', 'tawasulPersonID', 'date'],
    'methods' => ['GET', 'POST', 'PATCH', 'PUT', 'DELETE'],
],

'house-point-categories' => [
    'title' => 'House Point Categories',
    'group' => 'Modules: House Points',
    'scope' => 'housepoints',
    'module' => 'House Points',
    'action' => 'Categories',
    'table' => 'hpCategory',
    'primaryKey' => 'categoryID',
    'description' => 'Categories under which house and student points are awarded.',
    'select' => "SELECT hpCategory.categoryID, hpCategory.categoryName, hpCategory.categoryEvent, hpCategory.categoryOrder, hpCategory.categoryType FROM hpCategory",
    'filters' => ['categoryType' => 'hpCategory.categoryType'],
    'search' => ['hpCategory.categoryName'],
    'defaultSort' => 'hpCategory.categoryOrder',
],

'house-points-student' => [
    'title' => 'Student House Points',
    'group' => 'Modules: House Points',
    'scope' => 'housepoints',
    'module' => 'House Points',
    'action' => 'Award Points',
    'table' => 'hpPointStudent',
    'primaryKey' => 'hpID',
    'description' => 'House points awarded to individual students.',
    'select' => "SELECT hpPointStudent.hpID, hpPointStudent.studentID AS tawasulPersonID, hpPointStudent.categoryID, hpPointStudent.points, hpPointStudent.activity, hpPointStudent.yearID AS tawasulSchoolYearID, hpPointStudent.awardedDate, hpPointStudent.awardedBy, hpCategory.categoryName, tawasulPerson.surname, tawasulPerson.preferredName FROM hpPointStudent LEFT JOIN hpCategory ON (hpPointStudent.categoryID=hpCategory.categoryID) LEFT JOIN tawasulPerson ON (hpPointStudent.studentID=tawasulPerson.tawasulPersonID)",
    'yearFilter' => 'hpPointStudent.yearID',
    'filters' => ['tawasulPersonID' => 'hpPointStudent.studentID', 'categoryID' => 'hpPointStudent.categoryID'],
    'search' => ['tawasulPerson.surname', 'tawasulPerson.preferredName', 'hpPointStudent.activity'],
    'defaultSort' => 'hpPointStudent.awardedDate DESC',
    'writable' => ['studentID', 'categoryID', 'points', 'activity', 'yearID', 'awardedDate', 'awardedBy'],
    'required' => ['studentID', 'categoryID', 'points', 'yearID'],
    'methods' => ['GET', 'POST', 'PATCH', 'PUT', 'DELETE'],
],

'house-points-house' => [
    'title' => 'House Points',
    'group' => 'Modules: House Points',
    'scope' => 'housepoints',
    'module' => 'House Points',
    'action' => 'Award Points',
    'table' => 'hpPointHouse',
    'primaryKey' => 'hpID',
    'description' => 'House points awarded to a house as a whole.',
    'select' => "SELECT hpPointHouse.hpID, hpPointHouse.houseID AS tawasulHouseID, hpPointHouse.categoryID, hpPointHouse.points, hpPointHouse.activity, hpPointHouse.yearID AS tawasulSchoolYearID, hpPointHouse.awardedDate, hpPointHouse.awardedBy, hpCategory.categoryName, tawasulHouse.name AS houseName FROM hpPointHouse LEFT JOIN hpCategory ON (hpPointHouse.categoryID=hpCategory.categoryID) LEFT JOIN tawasulHouse ON (hpPointHouse.houseID=tawasulHouse.tawasulHouseID)",
    'yearFilter' => 'hpPointHouse.yearID',
    'filters' => ['tawasulHouseID' => 'hpPointHouse.houseID', 'categoryID' => 'hpPointHouse.categoryID'],
    'defaultSort' => 'hpPointHouse.awardedDate DESC',
],

'trips' => [
    'title' => 'Trips',
    'group' => 'Modules: Trip Planner',
    'scope' => 'trips',
    'module' => 'Trip Planner',
    'action' => 'Manage Trips',
    'table' => 'tripPlannerRequests',
    'primaryKey' => 'tripPlannerRequestID',
    'description' => 'Trip requests and their approval status.',
    'select' => "SELECT tripPlannerRequests.tripPlannerRequestID, tripPlannerRequests.creatorPersonID, tripPlannerRequests.title, tripPlannerRequests.description, tripPlannerRequests.location, tripPlannerRequests.status, tripPlannerRequests.tawasulSchoolYearID, creator.surname AS creatorSurname, creator.preferredName AS creatorPreferredName FROM tripPlannerRequests LEFT JOIN tawasulPerson AS creator ON (tripPlannerRequests.creatorPersonID=creator.tawasulPersonID)",
    'yearFilter' => 'tripPlannerRequests.tawasulSchoolYearID',
    'filters' => ['status' => 'tripPlannerRequests.status', 'creatorPersonID' => 'tripPlannerRequests.creatorPersonID'],
    'search' => ['tripPlannerRequests.title', 'tripPlannerRequests.location'],
    'defaultSort' => 'tripPlannerRequests.tripPlannerRequestID DESC',
],

'trip-days' => [
    'title' => 'Trip Days',
    'group' => 'Modules: Trip Planner',
    'scope' => 'trips',
    'module' => 'Trip Planner',
    'action' => 'Manage Trips',
    'table' => 'tripPlannerRequestDays',
    'primaryKey' => 'tripPlannerRequestDaysID',
    'description' => 'The dates and times a trip runs.',
    'select' => "SELECT tripPlannerRequestDays.* FROM tripPlannerRequestDays",
    'filters' => ['tripPlannerRequestID' => 'tripPlannerRequestDays.tripPlannerRequestID', 'startDate' => 'tripPlannerRequestDays.startDate'],
    'defaultSort' => 'tripPlannerRequestDays.startDate',
],

'trip-people' => [
    'title' => 'Trip Participants',
    'group' => 'Modules: Trip Planner',
    'scope' => 'trips',
    'module' => 'Trip Planner',
    'action' => 'Manage Trips',
    'table' => 'tripPlannerRequestPerson',
    'primaryKey' => 'tripPlannerRequestPersonID',
    'description' => 'Staff and students attached to a trip, with their role.',
    'select' => "SELECT tripPlannerRequestPerson.*, tawasulPerson.surname, tawasulPerson.preferredName FROM tripPlannerRequestPerson JOIN tawasulPerson ON (tripPlannerRequestPerson.tawasulPersonID=tawasulPerson.tawasulPersonID)",
    'filters' => ['tripPlannerRequestID' => 'tripPlannerRequestPerson.tripPlannerRequestID', 'tawasulPersonID' => 'tripPlannerRequestPerson.tawasulPersonID', 'role' => 'tripPlannerRequestPerson.role'],
    'defaultSort' => 'tawasulPerson.surname',
],

'pd-requests' => [
    'title' => 'Professional Development Requests',
    'group' => 'Modules: Professional Development',
    'scope' => 'pd',
    'module' => 'Professional Development',
    'action' => 'Manage Requests',
    'table' => 'professionalDevelopmentRequests',
    'primaryKey' => 'professionalDevelopmentRequestID',
    'description' => 'Staff requests to attend professional development, with status and cost.',
    'select' => "SELECT professionalDevelopmentRequests.professionalDevelopmentRequestID, professionalDevelopmentRequests.tawasulSchoolYearID, professionalDevelopmentRequests.tawasulPersonIDCreated, professionalDevelopmentRequests.timestampCreated, professionalDevelopmentRequests.status, professionalDevelopmentRequests.eventType, professionalDevelopmentRequests.eventFocus, professionalDevelopmentRequests.eventTitle, professionalDevelopmentRequests.eventLocation, tawasulPerson.surname, tawasulPerson.preferredName FROM professionalDevelopmentRequests LEFT JOIN tawasulPerson ON (professionalDevelopmentRequests.tawasulPersonIDCreated=tawasulPerson.tawasulPersonID)",
    'yearFilter' => 'professionalDevelopmentRequests.tawasulSchoolYearID',
    'filters' => ['status' => 'professionalDevelopmentRequests.status', 'eventType' => 'professionalDevelopmentRequests.eventType', 'tawasulPersonIDCreated' => 'professionalDevelopmentRequests.tawasulPersonIDCreated'],
    'search' => ['professionalDevelopmentRequests.eventTitle', 'professionalDevelopmentRequests.eventLocation'],
    'defaultSort' => 'professionalDevelopmentRequests.timestampCreated DESC',
],

'clinics' => [
    'title' => 'Clinics',
    'group' => 'Modules: Clinics',
    'scope' => 'clinics',
    'module' => 'Clinics',
    'action' => 'Manage Clinics',
    'table' => 'clinicsClinic',
    'primaryKey' => 'clinicsClinicID',
    'description' => 'Clinic sessions offered in a block.',
    'select' => "SELECT clinicsClinic.clinicsClinicID, clinicsClinic.tawasulSchoolYearID, clinicsClinic.clinicsBlockID, clinicsClinic.name, clinicsClinic.description, clinicsClinic.tawasulDepartmentID, clinicsClinic.tawasulYearGroupIDList, clinicsClinic.active, clinicsClinic.maxParticipants, clinicsClinic.tawasulSpaceID FROM clinicsClinic",
    'yearFilter' => 'clinicsClinic.tawasulSchoolYearID',
    'filters' => ['active' => 'clinicsClinic.active', 'clinicsBlockID' => 'clinicsClinic.clinicsBlockID', 'tawasulDepartmentID' => 'clinicsClinic.tawasulDepartmentID'],
    'search' => ['clinicsClinic.name', 'clinicsClinic.description'],
    'defaultSort' => 'clinicsClinic.name',
],

'clinic-students' => [
    'title' => 'Clinic Students',
    'group' => 'Modules: Clinics',
    'scope' => 'clinics',
    'module' => 'Clinics',
    'action' => 'Manage Clinics',
    'table' => 'clinicsClinicStudent',
    'primaryKey' => 'clinicsClinicStudentID',
    'description' => 'Student enrolment in clinics.',
    'select' => "SELECT clinicsClinicStudent.*, tawasulPerson.surname, tawasulPerson.preferredName FROM clinicsClinicStudent JOIN tawasulPerson ON (clinicsClinicStudent.tawasulPersonID=tawasulPerson.tawasulPersonID)",
    'filters' => ['clinicsClinicID' => 'clinicsClinicStudent.clinicsClinicID', 'clinicsBlockID' => 'clinicsClinicStudent.clinicsBlockID', 'tawasulPersonID' => 'clinicsClinicStudent.tawasulPersonID', 'status' => 'clinicsClinicStudent.status'],
    'defaultSort' => 'tawasulPerson.surname',
],

'stream-posts' => [
    'title' => 'Stream Posts',
    'group' => 'Modules: Stream',
    'scope' => 'stream',
    'module' => 'Stream',
    'action' => 'Stream',
    'table' => 'streamPost',
    'primaryKey' => 'streamPostID',
    'description' => 'Posts on the school stream.',
    'select' => "SELECT streamPost.streamPostID, streamPost.tawasulSchoolYearID, streamPost.tawasulPersonID, streamPost.post, streamPost.streamCategoryIDList, streamPost.timestamp, tawasulPerson.surname, tawasulPerson.preferredName FROM streamPost JOIN tawasulPerson ON (streamPost.tawasulPersonID=tawasulPerson.tawasulPersonID)",
    'yearFilter' => 'streamPost.tawasulSchoolYearID',
    'filters' => ['tawasulPersonID' => 'streamPost.tawasulPersonID'],
    'search' => ['streamPost.post'],
    'defaultSort' => 'streamPost.timestamp DESC',
],

'free-learning-units' => [
    'title' => 'Free Learning Units',
    'group' => 'Modules: Free Learning',
    'scope' => 'freelearning',
    'module' => 'Free Learning',
    'action' => 'Manage Units',
    'table' => 'freeLearningUnit',
    'primaryKey' => 'freeLearningUnitID',
    'description' => 'Self-directed learning units.',
    'select' => "SELECT freeLearningUnit.* FROM freeLearningUnit",
    'filters' => ['active' => 'freeLearningUnit.active'],
    'search' => ['freeLearningUnit.name'],
    'defaultSort' => 'freeLearningUnit.name',
],

'free-learning-progress' => [
    'title' => 'Free Learning Progress',
    'group' => 'Modules: Free Learning',
    'scope' => 'freelearning',
    'module' => 'Free Learning',
    'action' => 'Manage Units',
    'table' => 'freeLearningUnitStudent',
    'primaryKey' => 'freeLearningUnitStudentID',
    'description' => 'Student progress through free learning units.',
    'select' => "SELECT freeLearningUnitStudent.freeLearningUnitStudentID, freeLearningUnitStudent.tawasulPersonIDStudent, freeLearningUnitStudent.freeLearningUnitID, freeLearningUnitStudent.status, freeLearningUnitStudent.timestampJoined, freeLearningUnitStudent.timestampCompletePending, freeLearningUnitStudent.timestampCompleteApproved, tawasulPerson.surname, tawasulPerson.preferredName FROM freeLearningUnitStudent JOIN tawasulPerson ON (freeLearningUnitStudent.tawasulPersonIDStudent=tawasulPerson.tawasulPersonID)",
    'filters' => ['tawasulPersonIDStudent' => 'freeLearningUnitStudent.tawasulPersonIDStudent', 'freeLearningUnitID' => 'freeLearningUnitStudent.freeLearningUnitID', 'status' => 'freeLearningUnitStudent.status'],
    'search' => ['tawasulPerson.surname', 'tawasulPerson.preferredName'],
    'defaultSort' => 'freeLearningUnitStudent.timestampJoined DESC',
],

'workflow-definitions' => [
    'title' => 'Workflow Definitions',
    'group' => 'Modules: Workflow Engine',
    'scope' => 'workflows',
    'module' => 'Workflow Engine',
    'action' => 'Manage Workflows',
    'table' => 'workflowDefinition',
    'primaryKey' => 'workflowDefinitionID',
    'description' => 'Blueprint definitions for automated workflows with ordered steps.',
    'select' => "SELECT workflowDefinition.workflowDefinitionID, workflowDefinition.name, workflowDefinition.description, workflowDefinition.steps, workflowDefinition.active, workflowDefinition.createdBy, workflowDefinition.timestampCreated, workflowDefinition.timestampUpdated FROM workflowDefinition",
    'filters' => ['active' => 'workflowDefinition.active', 'createdBy' => 'workflowDefinition.createdBy'],
    'search' => ['workflowDefinition.name', 'workflowDefinition.description'],
    'sort' => ['name' => 'workflowDefinition.name', 'timestampCreated' => 'workflowDefinition.timestampCreated'],
    'defaultSort' => 'workflowDefinition.name',
    'writable' => ['name', 'description', 'steps', 'active', 'createdBy'],
    'required' => ['name', 'steps'],
    'methods' => ['GET', 'POST', 'PATCH', 'PUT', 'DELETE'],
],

'workflow-instances' => [
    'title' => 'Workflow Instances',
    'group' => 'Modules: Workflow Engine',
    'scope' => 'workflows',
    'module' => 'Workflow Engine',
    'action' => 'Workflow Instances',
    'table' => 'workflowInstance',
    'primaryKey' => 'workflowInstanceID',
    'description' => 'Running instances of workflows, with current step and status tracking.',
    'select' => "SELECT workflowInstance.workflowInstanceID, workflowInstance.workflowDefinitionID, workflowInstance.status, workflowInstance.startedBy, workflowInstance.startedByID, workflowInstance.contextType, workflowInstance.contextID, workflowInstance.contextName, workflowInstance.currentStep, workflowInstance.timestampCreated, workflowInstance.timestampCompleted, workflowDefinition.name AS workflowName FROM workflowInstance JOIN workflowDefinition ON (workflowInstance.workflowDefinitionID=workflowDefinition.workflowDefinitionID)",
    'filters' => ['workflowDefinitionID' => 'workflowInstance.workflowDefinitionID', 'status' => 'workflowInstance.status', 'startedBy' => 'workflowInstance.startedBy', 'contextType' => 'workflowInstance.contextType'],
    'search' => ['workflowInstance.contextName', 'workflowDefinition.name'],
    'sort' => ['timestampCreated' => 'workflowInstance.timestampCreated', 'status' => 'workflowInstance.status'],
    'defaultSort' => 'workflowInstance.timestampCreated DESC',
    'writable' => ['workflowDefinitionID', 'status', 'currentStep'],
    'methods' => ['GET', 'POST', 'PATCH', 'PUT', 'DELETE'],
],

'workflow-instance-steps' => [
    'title' => 'Workflow Instance Steps',
    'group' => 'Modules: Workflow Engine',
    'scope' => 'workflows',
    'module' => 'Workflow Engine',
    'action' => 'Workflow Instances',
    'table' => 'workflowInstanceStep',
    'primaryKey' => 'workflowInstanceStepID',
    'description' => 'Individual steps within workflow instances, with assignee and status.',
    'select' => "SELECT workflowInstanceStep.* FROM workflowInstanceStep",
    'filters' => ['workflowInstanceID' => 'workflowInstanceStep.workflowInstanceID', 'status' => 'workflowInstanceStep.status', 'stepNumber' => 'workflowInstanceStep.stepNumber'],
    'sort' => ['stepNumber' => 'workflowInstanceStep.stepNumber'],
    'defaultSort' => 'workflowInstanceStep.workflowInstanceID, workflowInstanceStep.stepNumber',
    'writable' => ['workflowInstanceID', 'stepNumber', 'stepName', 'status', 'comment', 'timestampCompleted'],
    'required' => ['workflowInstanceID', 'stepNumber', 'stepName'],
    'methods' => ['GET', 'POST', 'PATCH', 'PUT', 'DELETE'],
],

'workflow-instance-audit' => [
    'title' => 'Workflow Audit Trail',
    'group' => 'Modules: Workflow Engine',
    'scope' => 'workflows',
    'module' => 'Workflow Engine',
    'action' => 'Workflow Instances',
    'table' => 'workflowInstanceAudit',
    'primaryKey' => 'workflowInstanceAuditID',
    'description' => 'Read-only history of every state transition in workflow instances.',
    'select' => "SELECT workflowInstanceAudit.* FROM workflowInstanceAudit",
    'yearFilter' => 'workflowInstanceAudit.timestamp',
    'filters' => ['workflowInstanceID' => 'workflowInstanceAudit.workflowInstanceID', 'action' => 'workflowInstanceAudit.action'],
    'sort' => ['timestamp' => 'workflowInstanceAudit.timestamp'],
    'defaultSort' => 'workflowInstanceAudit.timestamp DESC',
    'methods' => ['GET', 'POST', 'PATCH', 'PUT', 'DELETE'],
],

'bulk-jobs' => [
    'title' => 'Bulk Jobs',
    'group' => 'Modules: Bulk Data Processor',
    'scope' => 'bulkjobs',
    'module' => 'Bulk Data Processor',
    'action' => 'Bulk Data Processor',
    'table' => 'bulkJob',
    'primaryKey' => 'bulkJobID',
    'description' => 'Background processing jobs for bulk imports and updates.',
    'select' => "SELECT bulkJob.* FROM bulkJob",
    'filters' => ['status' => 'bulkJob.status', 'type' => 'bulkJob.type', 'targetResource' => 'bulkJob.targetResource', 'startedBy' => 'bulkJob.startedBy'],
    'search' => ['bulkJob.name', 'bulkJob.sourceFile'],
    'sort' => ['timestampStarted' => 'bulkJob.timestampStarted', 'timestampCompleted' => 'bulkJob.timestampCompleted'],
    'defaultSort' => 'bulkJob.timestampStarted DESC',
    'writable' => ['name', 'type', 'targetResource', 'status', 'format', 'sourceFile'],
    'methods' => ['GET', 'POST', 'PATCH', 'PUT', 'DELETE'],
],

'bulk-job-errors' => [
    'title' => 'Bulk Job Errors',
    'group' => 'Modules: Bulk Data Processor',
    'scope' => 'bulkjobs',
    'module' => 'Bulk Data Processor',
    'action' => 'Bulk Data Processor',
    'table' => 'bulkJobError',
    'primaryKey' => 'bulkJobErrorID',
    'description' => 'Individual row errors recorded during bulk job processing.',
    'select' => "SELECT bulkJobError.* FROM bulkJobError",
    'filters' => ['bulkJobID' => 'bulkJobError.bulkJobID', 'rowNumber' => 'bulkJobError.rowNumber'],
    'defaultSort' => 'bulkJobError.timestamp DESC',
    'methods' => ['GET', 'POST', 'PATCH', 'PUT', 'DELETE'],
],

'message-templates' => [
    'title' => 'Message Templates',
    'group' => 'Modules: Communication Hub',
    'scope' => 'messaging',
    'module' => 'Communication Hub',
    'action' => 'Message Templates',
    'table' => 'commHubTemplate',
    'primaryKey' => 'commHubTemplateID',
    'description' => 'Reusable message templates with token replacement for email, SMS and message wall.',
    'select' => "SELECT commHubTemplate.* FROM commHubTemplate",
    'filters' => ['active' => 'commHubTemplate.active', 'channel' => 'commHubTemplate.channel', 'scope' => 'commHubTemplate.scope'],
    'search' => ['commHubTemplate.name', 'commHubTemplate.subject'],
    'sort' => ['name' => 'commHubTemplate.name', 'timestampCreated' => 'commHubTemplate.timestampCreated'],
    'defaultSort' => 'commHubTemplate.name',
    'writable' => ['name', 'subject', 'body', 'channel', 'scope', 'tokenHelp', 'active', 'tawasulPersonIDCreator'],
    'required' => ['name', 'subject', 'body', 'channel'],
    'methods' => ['GET', 'POST', 'PATCH', 'PUT', 'DELETE'],
],

'scheduled-messages' => [
    'title' => 'Scheduled Messages',
    'group' => 'Modules: Communication Hub',
    'scope' => 'messaging',
    'module' => 'Communication Hub',
    'action' => 'Scheduled Messages',
    'table' => 'commHubScheduled',
    'primaryKey' => 'commHubScheduledID',
    'description' => 'Messages queued for future delivery, with status tracking.',
    'select' => "SELECT commHubScheduled.* FROM commHubScheduled",
    'filters' => ['status' => 'commHubScheduled.status', 'channel' => 'commHubScheduled.channel', 'targetType' => 'commHubScheduled.targetType'],
    'search' => ['commHubScheduled.name', 'commHubScheduled.subject'],
    'sort' => ['scheduledTime' => 'commHubScheduled.scheduledTime', 'timestampCreated' => 'commHubScheduled.timestampCreated'],
    'defaultSort' => 'commHubScheduled.scheduledTime DESC',
    'writable' => ['name', 'subject', 'body', 'status', 'scheduledTime'],
    'methods' => ['GET', 'POST', 'PATCH', 'PUT', 'DELETE'],
],

'delivery-log' => [
    'title' => 'Delivery Log',
    'group' => 'Modules: Communication Hub',
    'scope' => 'messaging',
    'module' => 'Communication Hub',
    'action' => 'Scheduled Messages',
    'table' => 'commHubDeliveryLog',
    'primaryKey' => 'commHubDeliveryLogID',
    'description' => 'Delivery status and analytics for all sent messages.',
    'select' => "SELECT commHubDeliveryLog.* FROM commHubDeliveryLog",
    'filters' => ['status' => 'commHubDeliveryLog.status', 'channel' => 'commHubDeliveryLog.channel', 'tawasulMessengerID' => 'commHubDeliveryLog.tawasulMessengerID'],
    'search' => ['commHubDeliveryLog.messageSubject', 'commHubDeliveryLog.recipientEmail'],
    'sort' => ['timestampSent' => 'commHubDeliveryLog.timestampSent'],
    'defaultSort' => 'commHubDeliveryLog.timestampSent DESC',
    'methods' => ['GET', 'POST', 'PATCH', 'PUT', 'DELETE'],
],

];
