<?php
/*
People: users, roles, students, staff, families and personal records.
Columns verified against gibbon.sql (Gibbon v31 core schema).
*/

return [

'users' => [
    'title' => 'Users',
    'group' => 'People',
    'scope' => 'users',
    'module' => 'TawasulUserAdmin',
    'action' => 'Manage Users',
    'table' => 'tawasulPerson',
    'primaryKey' => 'tawasulPersonID',
    'description' => 'Every person record in Gibbon: staff, students, parents and other users.',
    'select' => "SELECT tawasulPerson.tawasulPersonID, tawasulPerson.username, tawasulPerson.title, tawasulPerson.surname, tawasulPerson.firstName, tawasulPerson.preferredName, tawasulPerson.officialName, tawasulPerson.gender, tawasulPerson.status, tawasulPerson.canLogin, tawasulPerson.email, tawasulPerson.emailAlternate, tawasulPerson.dob, tawasulPerson.image_240, tawasulPerson.studentID, tawasulPerson.dateStart, tawasulPerson.dateEnd, tawasulPerson.phone1, tawasulPerson.phone2, tawasulPerson.address1, tawasulPerson.address1District, tawasulPerson.address1Country, tawasulPerson.languageFirst, tawasulPerson.countryOfBirth, tawasulPerson.ethnicity, tawasulPerson.tawasulHouseID, tawasulHouse.name AS houseName, tawasulPerson.tawasulRoleIDPrimary, tawasulPerson.tawasulRoleIDAll, tawasulRole.name AS rolePrimary, tawasulRole.category AS roleCategory, tawasulPerson.lastTimestamp FROM tawasulPerson LEFT JOIN tawasulRole ON (tawasulPerson.tawasulRoleIDPrimary=tawasulRole.tawasulRoleID) LEFT JOIN tawasulHouse ON (tawasulPerson.tawasulHouseID=tawasulHouse.tawasulHouseID)",
    'idColumn' => 'tawasulPerson.tawasulPersonID',
    'filters' => [
        'status' => 'tawasulPerson.status',
        'canLogin' => 'tawasulPerson.canLogin',
        'tawasulRoleIDPrimary' => 'tawasulPerson.tawasulRoleIDPrimary',
        'roleCategory' => 'tawasulRole.category',
        'gender' => 'tawasulPerson.gender',
        'tawasulHouseID' => 'tawasulPerson.tawasulHouseID',
        'username' => 'tawasulPerson.username',
        'email' => 'tawasulPerson.email',
        'studentID' => 'tawasulPerson.studentID',
    ],
    'search' => ['tawasulPerson.surname', 'tawasulPerson.firstName', 'tawasulPerson.preferredName', 'tawasulPerson.username', 'tawasulPerson.email', 'tawasulPerson.studentID'],
    'sort' => ['surname' => 'tawasulPerson.surname', 'firstName' => 'tawasulPerson.firstName', 'username' => 'tawasulPerson.username', 'status' => 'tawasulPerson.status', 'dateStart' => 'tawasulPerson.dateStart'],
    'defaultSort' => 'tawasulPerson.surname, tawasulPerson.preferredName',
    'writable' => ['title', 'surname', 'firstName', 'preferredName', 'officialName', 'gender', 'username', 'status', 'canLogin', 'email', 'emailAlternate', 'dob', 'studentID', 'dateStart', 'dateEnd', 'phone1', 'phone1Type', 'phone2', 'address1', 'address1District', 'address1Country', 'languageFirst', 'countryOfBirth', 'tawasulHouseID', 'tawasulRoleIDPrimary', 'tawasulRoleIDAll', 'lockerNumber', 'transport', 'transportNotes'],
    'required' => ['surname', 'firstName', 'tawasulRoleIDPrimary'],
    'methods' => ['GET', 'POST', 'PATCH', 'PUT', 'DELETE'],
    'sensitive' => ['passwordStrong', 'passwordStrongSalt', 'mfaSecret', 'mfaToken', 'googleAPIRefreshToken', 'microsoftAPIRefreshToken', 'genericAPIRefreshToken'],
],

'roles' => [
    'title' => 'Roles',
    'group' => 'People',
    'scope' => 'roles',
    'module' => 'TawasulUserAdmin',
    'action' => 'Manage Roles',
    'table' => 'tawasulRole',
    'primaryKey' => 'tawasulRoleID',
    'description' => 'Gibbon roles and their categories, which drive all permissions.',
    'select' => "SELECT tawasulRole.tawasulRoleID, tawasulRole.name, tawasulRole.nameShort, tawasulRole.category, tawasulRole.description, tawasulRole.type, tawasulRole.canLoginRole, tawasulRole.futureYearsLogin, tawasulRole.pastYearsLogin, tawasulRole.restriction FROM tawasulRole",
    'filters' => ['category' => 'tawasulRole.category', 'type' => 'tawasulRole.type'],
    'search' => ['tawasulRole.name', 'tawasulRole.nameShort'],
    'sort' => ['name' => 'tawasulRole.name', 'category' => 'tawasulRole.category'],
    'defaultSort' => 'tawasulRole.category, tawasulRole.name',
],

    'students' => [
        'title' => 'Students',
        'group' => 'People',
        'scope' => 'students',
        'module' => 'TawasulStudents',
        'writeModule' => 'Admissions',
        'action' => 'View Student Profile',
        'writeAction' => 'Student Enrolment',
        'table' => 'tawasulStudentEnrolment',
    'primaryKey' => 'tawasulStudentEnrolmentID',
    'description' => 'Student enrolment records: one row per student per school year, joined to the person record.',
    'select' => "SELECT tawasulStudentEnrolment.tawasulStudentEnrolmentID, tawasulStudentEnrolment.tawasulSchoolYearID, tawasulStudentEnrolment.rollOrder, tawasulPerson.tawasulPersonID, tawasulPerson.username, tawasulPerson.studentID, tawasulPerson.surname, tawasulPerson.firstName, tawasulPerson.preferredName, tawasulPerson.officialName, tawasulPerson.gender, tawasulPerson.dob, tawasulPerson.email, tawasulPerson.status, tawasulPerson.image_240, tawasulPerson.dateStart, tawasulPerson.dateEnd, tawasulYearGroup.tawasulYearGroupID, tawasulYearGroup.name AS yearGroup, tawasulYearGroup.nameShort AS yearGroupShort, tawasulFormGroup.tawasulFormGroupID, tawasulFormGroup.name AS formGroup, tawasulFormGroup.nameShort AS formGroupShort, tawasulHouse.tawasulHouseID, tawasulHouse.name AS house FROM tawasulStudentEnrolment JOIN tawasulPerson ON (tawasulStudentEnrolment.tawasulPersonID=tawasulPerson.tawasulPersonID) LEFT JOIN tawasulYearGroup ON (tawasulStudentEnrolment.tawasulYearGroupID=tawasulYearGroup.tawasulYearGroupID) LEFT JOIN tawasulFormGroup ON (tawasulStudentEnrolment.tawasulFormGroupID=tawasulFormGroup.tawasulFormGroupID) LEFT JOIN tawasulHouse ON (tawasulPerson.tawasulHouseID=tawasulHouse.tawasulHouseID)",
    'yearFilter' => 'tawasulStudentEnrolment.tawasulSchoolYearID',
    'filters' => [
        'tawasulPersonID' => 'tawasulStudentEnrolment.tawasulPersonID',
        'tawasulYearGroupID' => 'tawasulStudentEnrolment.tawasulYearGroupID',
        'tawasulFormGroupID' => 'tawasulStudentEnrolment.tawasulFormGroupID',
        'tawasulHouseID' => 'tawasulPerson.tawasulHouseID',
        'status' => 'tawasulPerson.status',
        'gender' => 'tawasulPerson.gender',
        'studentID' => 'tawasulPerson.studentID',
    ],
    'search' => ['tawasulPerson.surname', 'tawasulPerson.firstName', 'tawasulPerson.preferredName', 'tawasulPerson.username', 'tawasulPerson.studentID'],
    'sort' => ['surname' => 'tawasulPerson.surname', 'rollOrder' => 'tawasulStudentEnrolment.rollOrder', 'yearGroup' => 'tawasulYearGroup.sequenceNumber', 'formGroup' => 'tawasulFormGroup.name'],
    'defaultSort' => 'tawasulYearGroup.sequenceNumber, tawasulPerson.surname, tawasulPerson.preferredName',
    'writable' => ['tawasulPersonID', 'tawasulSchoolYearID', 'tawasulYearGroupID', 'tawasulFormGroupID', 'rollOrder'],
    'required' => ['tawasulPersonID', 'tawasulSchoolYearID', 'tawasulYearGroupID', 'tawasulFormGroupID'],
    'methods' => ['GET', 'POST', 'PATCH', 'PUT', 'DELETE'],
],

'staff' => [
    'title' => 'Staff',
    'group' => 'People',
    'scope' => 'staff',
    'module' => 'TawasulStaff',
    'action' => 'Staff Directory',
    'table' => 'tawasulStaff',
    'primaryKey' => 'tawasulStaffID',
    'description' => 'Staff records joined to their person record.',
    'select' => "SELECT tawasulStaff.tawasulStaffID, tawasulStaff.type, tawasulStaff.initials, tawasulStaff.jobTitle, tawasulStaff.firstAidQualified, tawasulStaff.firstAidExpiry, tawasulStaff.biographicalGrouping, tawasulPerson.tawasulPersonID, tawasulPerson.username, tawasulPerson.title, tawasulPerson.surname, tawasulPerson.firstName, tawasulPerson.preferredName, tawasulPerson.email, tawasulPerson.status, tawasulPerson.image_240, tawasulPerson.dateStart, tawasulPerson.dateEnd, tawasulRole.name AS rolePrimary FROM tawasulStaff JOIN tawasulPerson ON (tawasulStaff.tawasulPersonID=tawasulPerson.tawasulPersonID) LEFT JOIN tawasulRole ON (tawasulPerson.tawasulRoleIDPrimary=tawasulRole.tawasulRoleID)",
    'filters' => ['type' => 'tawasulStaff.type', 'status' => 'tawasulPerson.status', 'tawasulPersonID' => 'tawasulStaff.tawasulPersonID', 'firstAidQualified' => 'tawasulStaff.firstAidQualified'],
    'search' => ['tawasulPerson.surname', 'tawasulPerson.firstName', 'tawasulPerson.preferredName', 'tawasulPerson.username', 'tawasulStaff.jobTitle'],
    'sort' => ['surname' => 'tawasulPerson.surname', 'jobTitle' => 'tawasulStaff.jobTitle', 'type' => 'tawasulStaff.type'],
    'defaultSort' => 'tawasulPerson.surname, tawasulPerson.preferredName',
    'writable' => ['tawasulPersonID', 'type', 'initials', 'jobTitle', 'firstAidQualified', 'firstAidQualification', 'firstAidExpiry', 'countryOfOrigin', 'qualifications', 'biography', 'biographicalGrouping', 'coverageExclude', 'coveragePriority'],
    'required' => ['tawasulPersonID', 'type'],
    'methods' => ['GET', 'POST', 'PATCH', 'PUT', 'DELETE'],
],

'staff-contracts' => [
    'title' => 'Staff Contracts',
    'group' => 'People',
    'scope' => 'staff.contracts',
    'module' => 'TawasulStaff',
    'action' => 'Manage Staff',
    'table' => 'tawasulStaffContract',
    'primaryKey' => 'tawasulStaffContractID',
    'description' => 'Employment contracts, including salary and allowance details. Highly sensitive.',
    'select' => "SELECT tawasulStaffContract.*, tawasulPerson.tawasulPersonID, tawasulPerson.surname, tawasulPerson.preferredName FROM tawasulStaffContract JOIN tawasulStaff ON (tawasulStaffContract.tawasulStaffID=tawasulStaff.tawasulStaffID) JOIN tawasulPerson ON (tawasulStaff.tawasulPersonID=tawasulPerson.tawasulPersonID)",
    'filters' => ['tawasulStaffID' => 'tawasulStaffContract.tawasulStaffID', 'status' => 'tawasulStaffContract.status', 'tawasulPersonID' => 'tawasulStaff.tawasulPersonID'],
    'sort' => ['dateStart' => 'tawasulStaffContract.dateStart'],
    'defaultSort' => 'tawasulStaffContract.dateStart DESC',
],

'families' => [
    'title' => 'Families',
    'group' => 'People',
    'scope' => 'families',
    'module' => 'TawasulUserAdmin',
    'action' => 'Manage Families',
    'table' => 'tawasulFamily',
    'primaryKey' => 'tawasulFamilyID',
    'description' => 'Family units, their home address and status.',
    'select' => "SELECT tawasulFamily.tawasulFamilyID, tawasulFamily.name, tawasulFamily.nameAddress, tawasulFamily.homeAddress, tawasulFamily.homeAddressDistrict, tawasulFamily.homeAddressCountry, tawasulFamily.status, tawasulFamily.languageHomePrimary, tawasulFamily.languageHomeSecondary FROM tawasulFamily",
    'filters' => ['status' => 'tawasulFamily.status'],
    'search' => ['tawasulFamily.name', 'tawasulFamily.nameAddress'],
    'sort' => ['name' => 'tawasulFamily.name'],
    'defaultSort' => 'tawasulFamily.name',
    'writable' => ['name', 'nameAddress', 'homeAddress', 'homeAddressDistrict', 'homeAddressCountry', 'status', 'languageHomePrimary', 'languageHomeSecondary'],
    'required' => ['name'],
    'methods' => ['GET', 'POST', 'PATCH', 'PUT', 'DELETE'],
],

'family-adults' => [
    'title' => 'Family Adults',
    'group' => 'People',
    'scope' => 'families',
    'module' => 'TawasulUserAdmin',
    'action' => 'Manage Families',
    'table' => 'tawasulFamilyAdult',
    'primaryKey' => 'tawasulFamilyAdultID',
    'description' => 'Adults (usually parents and guardians) attached to a family, with their contact priority.',
    'select' => "SELECT tawasulFamilyAdult.*, tawasulPerson.surname, tawasulPerson.preferredName, tawasulPerson.email, tawasulPerson.phone1, tawasulFamily.name AS familyName FROM tawasulFamilyAdult JOIN tawasulPerson ON (tawasulFamilyAdult.tawasulPersonID=tawasulPerson.tawasulPersonID) JOIN tawasulFamily ON (tawasulFamilyAdult.tawasulFamilyID=tawasulFamily.tawasulFamilyID)",
    'filters' => ['tawasulFamilyID' => 'tawasulFamilyAdult.tawasulFamilyID', 'tawasulPersonID' => 'tawasulFamilyAdult.tawasulPersonID', 'childDataAccess' => 'tawasulFamilyAdult.childDataAccess'],
    'sort' => ['contactPriority' => 'tawasulFamilyAdult.contactPriority'],
    'defaultSort' => 'tawasulFamilyAdult.contactPriority',
    'writable' => ['tawasulFamilyID', 'tawasulPersonID', 'comment', 'childDataAccess', 'contactPriority', 'contactCall', 'contactSMS', 'contactEmail', 'contactMail'],
    'required' => ['tawasulFamilyID', 'tawasulPersonID'],
    'methods' => ['GET', 'POST', 'PATCH', 'PUT', 'DELETE'],
],

'family-children' => [
    'title' => 'Family Children',
    'group' => 'People',
    'scope' => 'families',
    'module' => 'TawasulUserAdmin',
    'action' => 'Manage Families',
    'table' => 'tawasulFamilyChild',
    'primaryKey' => 'tawasulFamilyChildID',
    'description' => 'Children attached to a family.',
    'select' => "SELECT tawasulFamilyChild.*, tawasulPerson.surname, tawasulPerson.preferredName, tawasulPerson.studentID, tawasulFamily.name AS familyName FROM tawasulFamilyChild JOIN tawasulPerson ON (tawasulFamilyChild.tawasulPersonID=tawasulPerson.tawasulPersonID) JOIN tawasulFamily ON (tawasulFamilyChild.tawasulFamilyID=tawasulFamily.tawasulFamilyID)",
    'filters' => ['tawasulFamilyID' => 'tawasulFamilyChild.tawasulFamilyID', 'tawasulPersonID' => 'tawasulFamilyChild.tawasulPersonID'],
    'defaultSort' => 'tawasulPerson.surname',
    'writable' => ['tawasulFamilyID', 'tawasulPersonID', 'comment'],
    'required' => ['tawasulFamilyID', 'tawasulPersonID'],
    'methods' => ['GET', 'POST', 'PATCH', 'PUT', 'DELETE'],
],

'personal-documents' => [
    'title' => 'Personal Documents',
    'group' => 'People',
    'scope' => 'documents',
    'module' => 'TawasulUserAdmin',
    'action' => 'Manage Users',
    'table' => 'tawasulPersonalDocument',
    'primaryKey' => 'tawasulPersonalDocumentID',
    'description' => 'Passports, visas and other personal documents recorded against a person. Sensitive.',
    'select' => "SELECT tawasulPersonalDocument.*, tawasulPersonalDocumentType.name AS documentTypeName FROM tawasulPersonalDocument LEFT JOIN tawasulPersonalDocumentType ON (tawasulPersonalDocument.tawasulPersonalDocumentTypeID=tawasulPersonalDocumentType.tawasulPersonalDocumentTypeID)",
    'filters' => ['foreignTable' => 'tawasulPersonalDocument.foreignTable', 'foreignTableID' => 'tawasulPersonalDocument.foreignTableID', 'tawasulPersonalDocumentTypeID' => 'tawasulPersonalDocument.tawasulPersonalDocumentTypeID'],
    'sort' => ['dateExpiry' => 'tawasulPersonalDocument.dateExpiry'],
    'defaultSort' => 'tawasulPersonalDocument.dateExpiry',
],

];
