<?php
/*
School structure: years, terms, year groups, form groups, houses, spaces,
departments, grade scales and the calendar.
*/

return [

'school-years' => [
    'title' => 'School Years',
    'group' => 'School',
    'scope' => 'school',
    'module' => 'TawasulSchoolAdmin',
    'action' => 'Manage School Years',
    'table' => 'tawasulSchoolYear',
    'primaryKey' => 'tawasulSchoolYearID',
    'description' => 'Academic years, with the current year flagged by status.',
    'select' => "SELECT tawasulSchoolYear.tawasulSchoolYearID, tawasulSchoolYear.name, tawasulSchoolYear.status, tawasulSchoolYear.sequenceNumber, tawasulSchoolYear.firstDay, tawasulSchoolYear.lastDay FROM tawasulSchoolYear",
    'filters' => ['status' => 'tawasulSchoolYear.status'],
    'search' => ['tawasulSchoolYear.name'],
    'sort' => ['sequenceNumber' => 'tawasulSchoolYear.sequenceNumber', 'firstDay' => 'tawasulSchoolYear.firstDay'],
    'defaultSort' => 'tawasulSchoolYear.sequenceNumber',
],

'school-terms' => [
    'title' => 'School Terms',
    'group' => 'School',
    'scope' => 'school',
    'module' => 'TawasulSchoolAdmin',
    'action' => 'Manage School Years',
    'table' => 'tawasulSchoolYearTerm',
    'primaryKey' => 'tawasulSchoolYearTermID',
    'description' => 'Terms and semesters within a school year.',
    'select' => "SELECT tawasulSchoolYearTerm.* FROM tawasulSchoolYearTerm",
    'yearFilter' => 'tawasulSchoolYearTerm.tawasulSchoolYearID',
    'sort' => ['sequenceNumber' => 'tawasulSchoolYearTerm.sequenceNumber'],
    'defaultSort' => 'tawasulSchoolYearTerm.sequenceNumber',
],

'special-days' => [
    'title' => 'Special Days',
    'group' => 'School',
    'scope' => 'school',
    'module' => 'TawasulSchoolAdmin',
    'action' => 'Manage School Years',
    'table' => 'tawasulSchoolYearSpecialDay',
    'primaryKey' => 'tawasulSchoolYearSpecialDayID',
    'description' => 'School closures, holidays and timing variations.',
    'select' => "SELECT tawasulSchoolYearSpecialDay.*, tawasulSchoolYearTerm.tawasulSchoolYearID, tawasulSchoolYearTerm.name AS termName FROM tawasulSchoolYearSpecialDay JOIN tawasulSchoolYearTerm ON (tawasulSchoolYearSpecialDay.tawasulSchoolYearTermID=tawasulSchoolYearTerm.tawasulSchoolYearTermID)",
    'yearFilter' => 'tawasulSchoolYearTerm.tawasulSchoolYearID',
    'filters' => ['type' => 'tawasulSchoolYearSpecialDay.type', 'date' => 'tawasulSchoolYearSpecialDay.date'],
    'sort' => ['date' => 'tawasulSchoolYearSpecialDay.date'],
    'defaultSort' => 'tawasulSchoolYearSpecialDay.date',
],

'year-groups' => [
    'title' => 'Year Groups',
    'group' => 'School',
    'scope' => 'school',
    'module' => 'TawasulSchoolAdmin',
    'action' => 'Manage Year Groups',
    'writeAction' => 'Manage Year Groups',
    'table' => 'tawasulYearGroup',
    'primaryKey' => 'tawasulYearGroupID',
    'description' => 'Year groups (grades) and their head of year.',
    'select' => "SELECT tawasulYearGroup.tawasulYearGroupID, tawasulYearGroup.name, tawasulYearGroup.nameShort, tawasulYearGroup.sequenceNumber, tawasulYearGroup.tawasulPersonIDHOY, tawasulPerson.surname AS hoySurname, tawasulPerson.preferredName AS hoyPreferredName FROM tawasulYearGroup LEFT JOIN tawasulPerson ON (tawasulYearGroup.tawasulPersonIDHOY=tawasulPerson.tawasulPersonID)",
    'search' => ['tawasulYearGroup.name', 'tawasulYearGroup.nameShort'],
    'sort' => ['sequenceNumber' => 'tawasulYearGroup.sequenceNumber', 'name' => 'tawasulYearGroup.name'],
    'defaultSort' => 'tawasulYearGroup.sequenceNumber',
    'writable' => ['name', 'nameShort', 'sequenceNumber', 'tawasulPersonIDHOY'],
    'required' => ['name', 'nameShort', 'sequenceNumber'],
    'methods' => ['GET', 'POST', 'PATCH', 'PUT', 'DELETE'],
],

'form-groups' => [
    'title' => 'Form Groups',
    'group' => 'School',
    'scope' => 'school',
    'module' => 'TawasulSchoolAdmin',
    'action' => 'Manage Form Groups',
    'writeAction' => 'Manage Form Groups',
    'table' => 'tawasulFormGroup',
    'primaryKey' => 'tawasulFormGroupID',
    'description' => 'Form groups (tutor groups) for a school year, with tutors and room.',
    'select' => "SELECT tawasulFormGroup.tawasulFormGroupID, tawasulFormGroup.tawasulSchoolYearID, tawasulFormGroup.name, tawasulFormGroup.nameShort, tawasulFormGroup.attendance, tawasulFormGroup.website, tawasulFormGroup.tawasulSpaceID, tawasulSpace.name AS spaceName, tawasulFormGroup.tawasulPersonIDTutor, tutor.surname AS tutorSurname, tutor.preferredName AS tutorPreferredName, (SELECT COUNT(*) FROM tawasulStudentEnrolment WHERE tawasulStudentEnrolment.tawasulFormGroupID=tawasulFormGroup.tawasulFormGroupID) AS studentCount FROM tawasulFormGroup LEFT JOIN tawasulSpace ON (tawasulFormGroup.tawasulSpaceID=tawasulSpace.tawasulSpaceID) LEFT JOIN tawasulPerson AS tutor ON (tawasulFormGroup.tawasulPersonIDTutor=tutor.tawasulPersonID)",
    'yearFilter' => 'tawasulFormGroup.tawasulSchoolYearID',
    'filters' => ['tawasulPersonIDTutor' => 'tawasulFormGroup.tawasulPersonIDTutor'],
    'search' => ['tawasulFormGroup.name', 'tawasulFormGroup.nameShort'],
    'sort' => ['name' => 'tawasulFormGroup.name'],
    'defaultSort' => 'tawasulFormGroup.name',
    'writable' => ['tawasulSchoolYearID', 'name', 'nameShort', 'attendance', 'website', 'tawasulSpaceID', 'tawasulPersonIDTutor'],
    'required' => ['tawasulSchoolYearID', 'name', 'nameShort'],
    'methods' => ['GET', 'POST', 'PATCH', 'PUT', 'DELETE'],
],

'houses' => [
    'title' => 'Houses',
    'group' => 'School',
    'scope' => 'school',
    'module' => 'TawasulSchoolAdmin',
    'action' => 'Manage Houses',
    'table' => 'tawasulHouse',
    'primaryKey' => 'tawasulHouseID',
    'description' => 'School houses.',
    'select' => "SELECT tawasulHouse.tawasulHouseID, tawasulHouse.name, tawasulHouse.nameShort, tawasulHouse.logo, (SELECT COUNT(*) FROM tawasulPerson WHERE tawasulPerson.tawasulHouseID=tawasulHouse.tawasulHouseID AND tawasulPerson.status='Full') AS memberCount FROM tawasulHouse",
    'search' => ['tawasulHouse.name', 'tawasulHouse.nameShort'],
    'defaultSort' => 'tawasulHouse.name',
],

'spaces' => [
    'title' => 'Spaces',
    'group' => 'School',
    'scope' => 'school',
    'module' => 'TawasulSchoolAdmin',
    'action' => 'Manage Spaces',
    'table' => 'tawasulSpace',
    'primaryKey' => 'tawasulSpaceID',
    'description' => 'Rooms and facilities, including capacity and equipment.',
    'select' => "SELECT tawasulSpace.* FROM tawasulSpace",
    'filters' => ['active' => 'tawasulSpace.active', 'bookable' => 'tawasulSpace.bookable', 'type' => 'tawasulSpace.type'],
    'search' => ['tawasulSpace.name', 'tawasulSpace.type'],
    'defaultSort' => 'tawasulSpace.name',
],

'departments' => [
    'title' => 'Departments',
    'group' => 'School',
    'scope' => 'departments',
    'module' => 'TawasulDepartments',
    'action' => 'Departments',
    'table' => 'tawasulDepartment',
    'primaryKey' => 'tawasulDepartmentID',
    'description' => 'Learning areas and administrative departments.',
    'select' => "SELECT tawasulDepartment.tawasulDepartmentID, tawasulDepartment.type, tawasulDepartment.name, tawasulDepartment.nameShort, tawasulDepartment.subjectListing, tawasulDepartment.blurb, tawasulDepartment.logo, tawasulDepartment.sequenceNumber FROM tawasulDepartment",
    'filters' => ['type' => 'tawasulDepartment.type'],
    'search' => ['tawasulDepartment.name', 'tawasulDepartment.nameShort'],
    'defaultSort' => 'tawasulDepartment.name',
],

'department-staff' => [
    'title' => 'Department Staff',
    'group' => 'School',
    'scope' => 'departments',
    'module' => 'TawasulDepartments',
    'action' => 'Departments',
    'table' => 'tawasulDepartmentStaff',
    'primaryKey' => 'tawasulDepartmentStaffID',
    'description' => 'Staff membership of departments, with their departmental role.',
    'select' => "SELECT tawasulDepartmentStaff.*, tawasulDepartment.name AS departmentName, tawasulPerson.surname, tawasulPerson.preferredName, tawasulPerson.email FROM tawasulDepartmentStaff JOIN tawasulDepartment ON (tawasulDepartmentStaff.tawasulDepartmentID=tawasulDepartment.tawasulDepartmentID) JOIN tawasulPerson ON (tawasulDepartmentStaff.tawasulPersonID=tawasulPerson.tawasulPersonID)",
    'filters' => ['tawasulDepartmentID' => 'tawasulDepartmentStaff.tawasulDepartmentID', 'tawasulPersonID' => 'tawasulDepartmentStaff.tawasulPersonID', 'role' => 'tawasulDepartmentStaff.role'],
    'defaultSort' => 'tawasulDepartment.name, tawasulPerson.surname',
    'writable' => ['tawasulDepartmentID', 'tawasulPersonID', 'role'],
    'required' => ['tawasulDepartmentID', 'tawasulPersonID', 'role'],
    'methods' => ['GET', 'POST', 'PATCH', 'PUT', 'DELETE'],
],

'grade-scales' => [
    'title' => 'Grade Scales',
    'group' => 'School',
    'scope' => 'school',
    'module' => 'TawasulSchoolAdmin',
    'action' => 'Manage Grade Scales',
    'table' => 'tawasulScale',
    'primaryKey' => 'tawasulScaleID',
    'description' => 'Grading scales used across markbook and assessment.',
    'select' => "SELECT tawasulScale.* FROM tawasulScale",
    'filters' => ['active' => 'tawasulScale.active', 'usage' => 'tawasulScale.usage'],
    'search' => ['tawasulScale.name', 'tawasulScale.nameShort'],
    'defaultSort' => 'tawasulScale.name',
],

'grade-scale-grades' => [
    'title' => 'Grade Scale Grades',
    'group' => 'School',
    'scope' => 'school',
    'module' => 'TawasulSchoolAdmin',
    'action' => 'Manage Grade Scales',
    'table' => 'tawasulScaleGrade',
    'primaryKey' => 'tawasulScaleGradeID',
    'description' => 'Individual grades within a scale.',
    'select' => "SELECT tawasulScaleGrade.*, tawasulScale.name AS scaleName FROM tawasulScaleGrade JOIN tawasulScale ON (tawasulScaleGrade.tawasulScaleID=tawasulScale.tawasulScaleID)",
    'filters' => ['tawasulScaleID' => 'tawasulScaleGrade.tawasulScaleID'],
    'defaultSort' => 'tawasulScaleGrade.sequenceNumber',
],

'calendars' => [
    'title' => 'Calendars',
    'group' => 'School',
    'scope' => 'calendar',
    'module' => 'TawasulSchoolAdmin',
    'action' => 'Manage Calendars',
    'table' => 'tawasulCalendar',
    'primaryKey' => 'tawasulCalendarID',
    'description' => 'School calendars and their visibility settings.',
    'select' => "SELECT tawasulCalendar.* FROM tawasulCalendar",
    'yearFilter' => 'tawasulCalendar.tawasulSchoolYearID',
    'filters' => ['public' => 'tawasulCalendar.public'],
    'defaultSort' => 'tawasulCalendar.sequenceNumber, tawasulCalendar.name',
],

];
