<?php
/*
System: modules, actions, settings, notifications, custom fields and the
reference lists the rest of the API points at.

Nothing here is writable through the API. Changing modules, actions or
settings by HTTP would let a key holder grant itself permissions, so these
resources are read-only by design.
*/

return [

'modules' => [
    'title' => 'Modules',
    'group' => 'System',
    'scope' => 'system',
    'module' => 'TawasulSystemAdmin',
    'action' => 'Manage Modules',
    'table' => 'tawasulModule',
    'primaryKey' => 'tawasulModuleID',
    'description' => 'Installed modules, their version and whether they are active.',
    'select' => "SELECT tawasulModule.tawasulModuleID, tawasulModule.name, tawasulModule.description, tawasulModule.entryURL, tawasulModule.type, tawasulModule.active, tawasulModule.category, tawasulModule.version, tawasulModule.author, tawasulModule.url FROM tawasulModule",
    'filters' => ['active' => 'tawasulModule.active', 'type' => 'tawasulModule.type', 'category' => 'tawasulModule.category'],
    'search' => ['tawasulModule.name', 'tawasulModule.description'],
    'defaultSort' => 'tawasulModule.category, tawasulModule.name',
],

'actions' => [
    'title' => 'Actions',
    'group' => 'System',
    'scope' => 'system',
    'module' => 'TawasulSystemAdmin',
    'action' => 'Manage Modules',
    'table' => 'tawasulAction',
    'primaryKey' => 'tawasulActionID',
    'description' => 'Module actions, the unit Gibbon grants permissions against.',
    'select' => "SELECT tawasulAction.tawasulActionID, tawasulAction.tawasulModuleID, tawasulAction.name, tawasulAction.precedence, tawasulAction.category, tawasulAction.description, tawasulAction.URLList, tawasulAction.entryURL, tawasulAction.menuShow, tawasulModule.name AS moduleName FROM tawasulAction JOIN tawasulModule ON (tawasulAction.tawasulModuleID=tawasulModule.tawasulModuleID)",
    'filters' => ['tawasulModuleID' => 'tawasulAction.tawasulModuleID', 'category' => 'tawasulAction.category', 'menuShow' => 'tawasulAction.menuShow'],
    'search' => ['tawasulAction.name', 'tawasulAction.description'],
    'defaultSort' => 'tawasulModule.name, tawasulAction.name',
],

'permissions' => [
    'title' => 'Permissions',
    'group' => 'System',
    'scope' => 'system',
    'module' => 'TawasulUserAdmin',
    'action' => 'Manage Permissions',
    'table' => 'tawasulPermission',
    'primaryKey' => 'permissionID',
    'description' => 'Which roles hold which action, the raw permission matrix.',
    'select' => "SELECT tawasulPermission.permissionID, tawasulPermission.tawasulRoleID, tawasulPermission.tawasulActionID, tawasulRole.name AS roleName, tawasulRole.category AS roleCategory, tawasulAction.name AS actionName, tawasulModule.name AS moduleName FROM tawasulPermission JOIN tawasulRole ON (tawasulPermission.tawasulRoleID=tawasulRole.tawasulRoleID) JOIN tawasulAction ON (tawasulPermission.tawasulActionID=tawasulAction.tawasulActionID) JOIN tawasulModule ON (tawasulAction.tawasulModuleID=tawasulModule.tawasulModuleID)",
    'filters' => ['tawasulRoleID' => 'tawasulPermission.tawasulRoleID', 'tawasulActionID' => 'tawasulPermission.tawasulActionID', 'moduleName' => 'tawasulModule.name'],
    'defaultSort' => 'tawasulRole.name, tawasulModule.name, tawasulAction.name',
],

'settings' => [
    'title' => 'Settings',
    'group' => 'System',
    'scope' => 'system',
    'module' => 'TawasulSystemAdmin',
    'action' => 'Third Party Settings',
    'table' => 'tawasulSetting',
    'primaryKey' => 'tawasulSettingID',
    'description' => 'Gibbon settings by scope. Values known to hold credentials are redacted.',
    'select' => "SELECT tawasulSetting.tawasulSettingID, tawasulSetting.scope, tawasulSetting.name, tawasulSetting.nameDisplay, tawasulSetting.description, tawasulSetting.value FROM tawasulSetting",
    'where' => ["tawasulSetting.scope NOT IN ('System Admin','Rest API')", "tawasulSetting.name NOT LIKE '%ecret%'", "tawasulSetting.name NOT LIKE '%assword%'", "tawasulSetting.name NOT LIKE '%apiKey%'", "tawasulSetting.name NOT LIKE '%Token%'"],
    'filters' => ['scope' => 'tawasulSetting.scope', 'name' => 'tawasulSetting.name'],
    'search' => ['tawasulSetting.name', 'tawasulSetting.nameDisplay'],
    'defaultSort' => 'tawasulSetting.scope, tawasulSetting.name',
],

'notifications' => [
    'title' => 'Notifications',
    'group' => 'System',
    'scope' => 'notifications',
    'module' => null,
    'action' => null,
    'table' => 'tawasulNotification',
    'primaryKey' => 'tawasulNotificationID',
    'description' => 'In-app notifications raised for a person.',
    'select' => "SELECT tawasulNotification.tawasulNotificationID, tawasulNotification.tawasulPersonID, tawasulNotification.status, tawasulNotification.tawasulModuleID, tawasulNotification.count, tawasulNotification.text, tawasulNotification.actionLink, tawasulNotification.timestamp, tawasulModule.name AS moduleName FROM tawasulNotification LEFT JOIN tawasulModule ON (tawasulNotification.tawasulModuleID=tawasulModule.tawasulModuleID)",
    'filters' => ['tawasulPersonID' => 'tawasulNotification.tawasulPersonID', 'status' => 'tawasulNotification.status'],
    'defaultSort' => 'tawasulNotification.timestamp DESC',
    'writable' => ['tawasulPersonID', 'status', 'tawasulModuleID', 'text', 'actionLink'],
    'required' => ['tawasulPersonID', 'text', 'actionLink'],
    'methods' => ['GET', 'POST', 'PATCH', 'PUT', 'DELETE'],
],

'custom-fields' => [
    'title' => 'Custom Fields',
    'group' => 'System',
    'scope' => 'system',
    'module' => 'TawasulSystemAdmin',
    'action' => 'Manage Custom Fields',
    'table' => 'tawasulCustomField',
    'primaryKey' => 'tawasulCustomFieldID',
    'description' => 'Custom field definitions, needed to interpret the "fields" column on other resources.',
    'select' => "SELECT tawasulCustomField.tawasulCustomFieldID, tawasulCustomField.context, tawasulCustomField.name, tawasulCustomField.active, tawasulCustomField.description, tawasulCustomField.type, tawasulCustomField.options, tawasulCustomField.required, tawasulCustomField.heading, tawasulCustomField.sequenceNumber FROM tawasulCustomField",
    'filters' => ['context' => 'tawasulCustomField.context', 'active' => 'tawasulCustomField.active', 'type' => 'tawasulCustomField.type'],
    'search' => ['tawasulCustomField.name'],
    'defaultSort' => 'tawasulCustomField.context, tawasulCustomField.sequenceNumber',
],

'outcomes' => [
    'title' => 'Outcomes',
    'group' => 'System',
    'scope' => 'curriculum',
    'module' => 'TawasulPlanner',
    'action' => 'Manage Outcomes',
    'table' => 'tawasulOutcome',
    'primaryKey' => 'tawasulOutcomeID',
    'description' => 'Learning outcomes available to units and lessons.',
    'select' => "SELECT tawasulOutcome.tawasulOutcomeID, tawasulOutcome.name, tawasulOutcome.nameShort, tawasulOutcome.category, tawasulOutcome.description, tawasulOutcome.active, tawasulOutcome.scope, tawasulOutcome.tawasulDepartmentID, tawasulOutcome.tawasulYearGroupIDList FROM tawasulOutcome",
    'filters' => ['active' => 'tawasulOutcome.active', 'scope' => 'tawasulOutcome.scope', 'tawasulDepartmentID' => 'tawasulOutcome.tawasulDepartmentID', 'category' => 'tawasulOutcome.category'],
    'search' => ['tawasulOutcome.name', 'tawasulOutcome.nameShort'],
    'defaultSort' => 'tawasulOutcome.category, tawasulOutcome.name',
],

'rubrics' => [
    'title' => 'Rubrics',
    'group' => 'System',
    'scope' => 'curriculum',
    'module' => 'TawasulRubrics',
    'action' => 'Manage Rubrics',
    'table' => 'tawasulRubric',
    'primaryKey' => 'tawasulRubricID',
    'description' => 'Assessment rubrics.',
    'select' => "SELECT tawasulRubric.tawasulRubricID, tawasulRubric.name, tawasulRubric.category, tawasulRubric.description, tawasulRubric.active, tawasulRubric.scope, tawasulRubric.tawasulDepartmentID, tawasulRubric.tawasulYearGroupIDList, tawasulRubric.tawasulScaleID FROM tawasulRubric",
    'filters' => ['active' => 'tawasulRubric.active', 'scope' => 'tawasulRubric.scope', 'tawasulDepartmentID' => 'tawasulRubric.tawasulDepartmentID'],
    'search' => ['tawasulRubric.name'],
    'defaultSort' => 'tawasulRubric.name',
],

'api-logs' => [
    'title' => 'API Request Log',
    'group' => 'System',
    'scope' => 'apilogs',
    'module' => 'Rest API',
    'action' => 'View Request Log',
    'table' => 'restApiLog',
    'primaryKey' => 'restApiLogID',
    'description' => 'This add-on own request log: every API call, its key, status and duration.',
    'select' => "SELECT restApiLog.restApiLogID, restApiLog.restApiKeyID, restApiLog.tawasulPersonID, restApiLog.method, restApiLog.endpoint, restApiLog.resource, restApiLog.statusCode, restApiLog.durationMS, restApiLog.message, restApiLog.ipAddress, restApiLog.timestamp, restApiKey.name AS keyName FROM restApiLog LEFT JOIN restApiKey ON (restApiLog.restApiKeyID=restApiKey.restApiKeyID)",
    'filters' => ['restApiKeyID' => 'restApiLog.restApiKeyID', 'statusCode' => 'restApiLog.statusCode', 'method' => 'restApiLog.method', 'resource' => 'restApiLog.resource', 'tawasulPersonID' => 'restApiLog.tawasulPersonID'],
    'search' => ['restApiLog.endpoint', 'restApiLog.ipAddress'],
    'sort' => ['timestamp' => 'restApiLog.timestamp', 'durationMS' => 'restApiLog.durationMS'],
    'defaultSort' => 'restApiLog.timestamp DESC',
],

'notification-templates' => [
    'title' => 'Notification Templates',
    'group' => 'System',
    'scope' => 'notifications',
    'module' => 'Notification Center',
    'action' => 'Manage Notification Templates',
    'table' => 'notificationTemplate',
    'primaryKey' => 'notificationTemplateID',
    'description' => 'Custom templates that control the title and body of notifications sent when system events fire.',
    'select' => "SELECT notificationTemplate.notificationTemplateID, notificationTemplate.name, notificationTemplate.eventName, notificationTemplate.title, notificationTemplate.body, notificationTemplate.moduleName, notificationTemplate.actionName, notificationTemplate.scope, notificationTemplate.active, notificationTemplate.tawasulPersonIDCreator, notificationTemplate.timestampCreated, notificationTemplate.timestampUpdated FROM notificationTemplate",
    'filters' => ['active' => 'notificationTemplate.active', 'eventName' => 'notificationTemplate.eventName', 'moduleName' => 'notificationTemplate.moduleName'],
    'search' => ['notificationTemplate.name', 'notificationTemplate.eventName', 'notificationTemplate.title'],
    'sort' => ['name' => 'notificationTemplate.name', 'timestampCreated' => 'notificationTemplate.timestampCreated'],
    'defaultSort' => 'notificationTemplate.moduleName, notificationTemplate.name',
    'writable' => ['name', 'eventName', 'title', 'body', 'moduleName', 'actionName', 'scope', 'active', 'tawasulPersonIDCreator'],
    'required' => ['name', 'eventName', 'title', 'moduleName', 'actionName'],
    'methods' => ['GET', 'POST', 'PATCH', 'PUT', 'DELETE'],
],

'notification-events' => [
    'title' => 'Notification Events',
    'group' => 'System',
    'scope' => 'notifications',
    'module' => null,
    'action' => null,
    'table' => 'tawasulNotificationEvent',
    'primaryKey' => 'tawasulNotificationEventID',
    'description' => 'System events that can generate notifications, and the module/action/scope they target.',
    'select' => "SELECT tawasulNotificationEvent.* FROM tawasulNotificationEvent",
    'filters' => ['active' => 'tawasulNotificationEvent.active', 'moduleName' => 'tawasulNotificationEvent.moduleName', 'type' => 'tawasulNotificationEvent.type'],
    'search' => ['tawasulNotificationEvent.event', 'tawasulNotificationEvent.moduleName'],
    'sort' => ['event' => 'tawasulNotificationEvent.event'],
    'defaultSort' => 'tawasulNotificationEvent.moduleName, tawasulNotificationEvent.event',
],

'notification-listeners' => [
    'title' => 'Notification Listeners',
    'group' => 'System',
    'scope' => 'notifications',
    'module' => null,
    'action' => null,
    'table' => 'tawasulNotificationListener',
    'primaryKey' => 'tawasulNotificationListenerID',
    'description' => 'Who is listening to which notification events, with scope-based delivery rules.',
    'select' => "SELECT tawasulNotificationListener.*, e.event AS eventName, e.moduleName, e.actionName FROM tawasulNotificationListener LEFT JOIN tawasulNotificationEvent e ON (tawasulNotificationListener.tawasulNotificationEventID=e.tawasulNotificationEventID)",
    'filters' => ['tawasulNotificationEventID' => 'tawasulNotificationListener.tawasulNotificationEventID', 'tawasulPersonID' => 'tawasulNotificationListener.tawasulPersonID', 'scopeType' => 'tawasulNotificationListener.scopeType'],
    'defaultSort' => 'tawasulNotificationListener.tawasulNotificationEventID, tawasulNotificationListener.tawasulPersonID',
],

];
