<?php
/*
Wellbeing: attendance, behaviour, individual needs, medical and first aid.
These resources carry the most sensitive student data in Gibbon, so they sit
behind their own scopes and always honour Gibbon role permissions.
*/

return [

'attendance' => [
    'title' => 'Attendance',
    'group' => 'Wellbeing',
    'scope' => 'attendance',
    'module' => 'TawasulAttendance',
    'action' => 'Attendance By Person',
    'writeAction' => 'Manage Attendance Logs',
    'table' => 'tawasulAttendanceLogPerson',
    'primaryKey' => 'tawasulAttendanceLogPersonID',
    'description' => 'Per-person attendance log entries, the authoritative attendance record.',
    'select' => "SELECT tawasulAttendanceLogPerson.tawasulAttendanceLogPersonID, tawasulAttendanceLogPerson.tawasulPersonID, tawasulAttendanceLogPerson.date, tawasulAttendanceLogPerson.type, tawasulAttendanceLogPerson.reason, tawasulAttendanceLogPerson.comment, tawasulAttendanceLogPerson.direction, tawasulAttendanceLogPerson.context, tawasulAttendanceLogPerson.tawasulPersonIDTaker, tawasulAttendanceLogPerson.tawasulFormGroupID, tawasulAttendanceLogPerson.tawasulCourseClassID, tawasulAttendanceLogPerson.timestampTaken, tawasulAttendanceLogPerson.tawasulAttendanceCodeID, tawasulAttendanceCode.name AS codeName, tawasulAttendanceCode.nameShort AS codeNameShort, tawasulAttendanceCode.scope AS codeScope, tawasulPerson.surname, tawasulPerson.preferredName, tawasulPerson.studentID, taker.surname AS takerSurname, taker.preferredName AS takerPreferredName FROM tawasulAttendanceLogPerson JOIN tawasulPerson ON (tawasulAttendanceLogPerson.tawasulPersonID=tawasulPerson.tawasulPersonID) LEFT JOIN tawasulAttendanceCode ON (tawasulAttendanceLogPerson.tawasulAttendanceCodeID=tawasulAttendanceCode.tawasulAttendanceCodeID) LEFT JOIN tawasulPerson AS taker ON (tawasulAttendanceLogPerson.tawasulPersonIDTaker=taker.tawasulPersonID)",
    'filters' => [
        'tawasulPersonID' => 'tawasulAttendanceLogPerson.tawasulPersonID',
        'date' => 'tawasulAttendanceLogPerson.date',
        'type' => 'tawasulAttendanceLogPerson.type',
        'direction' => 'tawasulAttendanceLogPerson.direction',
        'context' => 'tawasulAttendanceLogPerson.context',
        'tawasulFormGroupID' => 'tawasulAttendanceLogPerson.tawasulFormGroupID',
        'tawasulCourseClassID' => 'tawasulAttendanceLogPerson.tawasulCourseClassID',
        'tawasulAttendanceCodeID' => 'tawasulAttendanceLogPerson.tawasulAttendanceCodeID',
    ],
    'search' => ['tawasulPerson.surname', 'tawasulPerson.preferredName', 'tawasulPerson.studentID'],
    'sort' => ['date' => 'tawasulAttendanceLogPerson.date', 'surname' => 'tawasulPerson.surname'],
    'defaultSort' => 'tawasulAttendanceLogPerson.date DESC, tawasulAttendanceLogPerson.timestampTaken DESC',
    'writable' => ['tawasulPersonID', 'tawasulAttendanceCodeID', 'date', 'direction', 'type', 'reason', 'context', 'comment', 'tawasulPersonIDTaker', 'tawasulFormGroupID', 'tawasulCourseClassID', 'tawasulTTDayRowClassID'],
    'required' => ['tawasulPersonID', 'date', 'type'],
    'methods' => ['GET', 'POST', 'PATCH', 'PUT', 'DELETE'],
],

'attendance-codes' => [
    'title' => 'Attendance Codes',
    'group' => 'Wellbeing',
    'scope' => 'attendance',
    'module' => 'TawasulAttendance',
    'action' => 'Manage Attendance Codes',
    'table' => 'tawasulAttendanceCode',
    'primaryKey' => 'tawasulAttendanceCodeID',
    'description' => 'Attendance codes and what each one counts as.',
    'select' => "SELECT tawasulAttendanceCode.* FROM tawasulAttendanceCode",
    'filters' => ['active' => 'tawasulAttendanceCode.active', 'type' => 'tawasulAttendanceCode.type', 'direction' => 'tawasulAttendanceCode.direction', 'scope' => 'tawasulAttendanceCode.scope', 'reportable' => 'tawasulAttendanceCode.reportable'],
    'search' => ['tawasulAttendanceCode.name', 'tawasulAttendanceCode.nameShort'],
    'defaultSort' => 'tawasulAttendanceCode.sequenceNumber',
],

'attendance-form-group-logs' => [
    'title' => 'Form Group Attendance Logs',
    'group' => 'Wellbeing',
    'scope' => 'attendance',
    'module' => 'TawasulAttendance',
    'action' => 'Attendance By Form Group',
    'table' => 'tawasulAttendanceLogFormGroup',
    'primaryKey' => 'tawasulAttendanceLogFormGroupID',
    'description' => 'Which form groups had attendance taken, by whom and when.',
    'select' => "SELECT tawasulAttendanceLogFormGroup.*, tawasulFormGroup.name AS formGroupName, tawasulFormGroup.tawasulSchoolYearID FROM tawasulAttendanceLogFormGroup JOIN tawasulFormGroup ON (tawasulAttendanceLogFormGroup.tawasulFormGroupID=tawasulFormGroup.tawasulFormGroupID)",
    'yearFilter' => 'tawasulFormGroup.tawasulSchoolYearID',
    'filters' => ['tawasulFormGroupID' => 'tawasulAttendanceLogFormGroup.tawasulFormGroupID', 'date' => 'tawasulAttendanceLogFormGroup.date'],
    'defaultSort' => 'tawasulAttendanceLogFormGroup.date DESC',
],

'attendance-class-logs' => [
    'title' => 'Class Attendance Logs',
    'group' => 'Wellbeing',
    'scope' => 'attendance',
    'module' => 'TawasulAttendance',
    'action' => 'Attendance By Class',
    'table' => 'tawasulAttendanceLogCourseClass',
    'primaryKey' => 'tawasulAttendanceLogCourseClassID',
    'description' => 'Which classes had attendance taken, by whom and when.',
    'select' => "SELECT tawasulAttendanceLogCourseClass.*, tawasulCourseClass.name AS className, tawasulCourse.nameShort AS courseNameShort, tawasulCourse.tawasulSchoolYearID FROM tawasulAttendanceLogCourseClass JOIN tawasulCourseClass ON (tawasulAttendanceLogCourseClass.tawasulCourseClassID=tawasulCourseClass.tawasulCourseClassID) JOIN tawasulCourse ON (tawasulCourseClass.tawasulCourseID=tawasulCourse.tawasulCourseID)",
    'yearFilter' => 'tawasulCourse.tawasulSchoolYearID',
    'filters' => ['tawasulCourseClassID' => 'tawasulAttendanceLogCourseClass.tawasulCourseClassID', 'date' => 'tawasulAttendanceLogCourseClass.date'],
    'defaultSort' => 'tawasulAttendanceLogCourseClass.date DESC',
],

'behaviour' => [
    'title' => 'Behaviour Records',
    'group' => 'Wellbeing',
    'scope' => 'behaviour',
    'module' => 'TawasulBehaviour',
    'action' => 'Manage Behaviour Records',
    'table' => 'tawasulBehaviour',
    'primaryKey' => 'tawasulBehaviourID',
    'description' => 'Positive and negative behaviour records against a student.',
    'select' => "SELECT tawasulBehaviour.tawasulBehaviourID, tawasulBehaviour.tawasulSchoolYearID, tawasulBehaviour.date, tawasulBehaviour.tawasulPersonID, tawasulBehaviour.type, tawasulBehaviour.descriptor, tawasulBehaviour.level, tawasulBehaviour.comment, tawasulBehaviour.followup, tawasulBehaviour.tawasulPlannerEntryID, tawasulBehaviour.tawasulPersonIDCreator, tawasulBehaviour.timestamp, tawasulPerson.surname, tawasulPerson.preferredName, tawasulPerson.studentID, creator.surname AS creatorSurname, creator.preferredName AS creatorPreferredName FROM tawasulBehaviour JOIN tawasulPerson ON (tawasulBehaviour.tawasulPersonID=tawasulPerson.tawasulPersonID) LEFT JOIN tawasulPerson AS creator ON (tawasulBehaviour.tawasulPersonIDCreator=creator.tawasulPersonID)",
    'yearFilter' => 'tawasulBehaviour.tawasulSchoolYearID',
    'filters' => ['tawasulPersonID' => 'tawasulBehaviour.tawasulPersonID', 'type' => 'tawasulBehaviour.type', 'descriptor' => 'tawasulBehaviour.descriptor', 'level' => 'tawasulBehaviour.level', 'date' => 'tawasulBehaviour.date'],
    'search' => ['tawasulPerson.surname', 'tawasulPerson.preferredName', 'tawasulBehaviour.comment', 'tawasulBehaviour.descriptor'],
    'sort' => ['date' => 'tawasulBehaviour.date', 'type' => 'tawasulBehaviour.type'],
    'defaultSort' => 'tawasulBehaviour.date DESC',
    'writable' => ['tawasulSchoolYearID', 'date', 'tawasulPersonID', 'type', 'descriptor', 'level', 'comment', 'followup', 'tawasulPlannerEntryID', 'tawasulPersonIDCreator'],
    'required' => ['tawasulSchoolYearID', 'date', 'tawasulPersonID', 'type'],
    'methods' => ['GET', 'POST', 'PATCH', 'PUT', 'DELETE'],
],

'behaviour-letters' => [
    'title' => 'Behaviour Letters',
    'group' => 'Wellbeing',
    'scope' => 'behaviour',
    'module' => 'TawasulBehaviour',
    'action' => 'Behaviour Letters',
    'table' => 'tawasulBehaviourLetter',
    'primaryKey' => 'tawasulBehaviourLetterID',
    'description' => 'Escalation letters generated from behaviour records.',
    'select' => "SELECT tawasulBehaviourLetter.tawasulBehaviourLetterID, tawasulBehaviourLetter.tawasulSchoolYearID, tawasulBehaviourLetter.tawasulPersonID, tawasulBehaviourLetter.letterLevel, tawasulBehaviourLetter.status, tawasulBehaviourLetter.type, tawasulBehaviourLetter.timestamp, tawasulPerson.surname, tawasulPerson.preferredName FROM tawasulBehaviourLetter JOIN tawasulPerson ON (tawasulBehaviourLetter.tawasulPersonID=tawasulPerson.tawasulPersonID)",
    'yearFilter' => 'tawasulBehaviourLetter.tawasulSchoolYearID',
    'filters' => ['tawasulPersonID' => 'tawasulBehaviourLetter.tawasulPersonID', 'status' => 'tawasulBehaviourLetter.status', 'letterLevel' => 'tawasulBehaviourLetter.letterLevel'],
    'defaultSort' => 'tawasulBehaviourLetter.timestamp DESC',
],

'alert-levels' => [
    'title' => 'Alert Levels',
    'group' => 'Wellbeing',
    'scope' => 'wellbeing',
    'module' => null,
    'action' => null,
    'table' => 'tawasulAlertLevel',
    'primaryKey' => 'tawasulAlertLevelID',
    'description' => 'Severity levels (low, medium, high) used by medical and individual needs alerts.',
    'select' => "SELECT tawasulAlertLevel.* FROM tawasulAlertLevel",
    'defaultSort' => 'tawasulAlertLevel.sequenceNumber',
],

'individual-needs' => [
    'title' => 'Individual Needs',
    'group' => 'Wellbeing',
    'scope' => 'individualneeds',
    'module' => 'TawasulIndividualNeeds',
    'action' => 'Individual Needs Records_view',
    'table' => 'tawasulIN',
    'primaryKey' => 'tawasulINID',
    'description' => 'Individual needs plans: strategies, targets and notes. Highly sensitive.',
    'select' => "SELECT tawasulIN.tawasulINID, tawasulIN.tawasulPersonID, tawasulIN.strategies, tawasulIN.targets, tawasulIN.notes, tawasulPerson.surname, tawasulPerson.preferredName, tawasulPerson.studentID FROM tawasulIN JOIN tawasulPerson ON (tawasulIN.tawasulPersonID=tawasulPerson.tawasulPersonID)",
    'filters' => ['tawasulPersonID' => 'tawasulIN.tawasulPersonID'],
    'search' => ['tawasulPerson.surname', 'tawasulPerson.preferredName'],
    'defaultSort' => 'tawasulPerson.surname',
],

'individual-needs-descriptors' => [
    'title' => 'Individual Needs Descriptors',
    'group' => 'Wellbeing',
    'scope' => 'individualneeds',
    'module' => 'TawasulIndividualNeeds',
    'action' => 'Individual Needs Records_view',
    'table' => 'tawasulINPersonDescriptor',
    'primaryKey' => 'tawasulINPersonDescriptorID',
    'description' => 'Individual needs descriptors assigned to a student, with alert level.',
    'select' => "SELECT tawasulINPersonDescriptor.*, tawasulINDescriptor.name AS descriptorName, tawasulAlertLevel.name AS alertLevelName, tawasulAlertLevel.color AS alertLevelColor, tawasulPerson.surname, tawasulPerson.preferredName FROM tawasulINPersonDescriptor JOIN tawasulINDescriptor ON (tawasulINPersonDescriptor.tawasulINDescriptorID=tawasulINDescriptor.tawasulINDescriptorID) JOIN tawasulPerson ON (tawasulINPersonDescriptor.tawasulPersonID=tawasulPerson.tawasulPersonID) LEFT JOIN tawasulAlertLevel ON (tawasulINPersonDescriptor.tawasulAlertLevelID=tawasulAlertLevel.tawasulAlertLevelID)",
    'filters' => ['tawasulPersonID' => 'tawasulINPersonDescriptor.tawasulPersonID', 'tawasulINDescriptorID' => 'tawasulINPersonDescriptor.tawasulINDescriptorID', 'tawasulAlertLevelID' => 'tawasulINPersonDescriptor.tawasulAlertLevelID'],
    'defaultSort' => 'tawasulPerson.surname',
],

'medical' => [
    'title' => 'Medical Records',
    'group' => 'Wellbeing',
    'scope' => 'medical',
    'module' => 'Medical',
    'action' => 'Manage Medical Records',
    'table' => 'tawasulPersonMedical',
    'primaryKey' => 'tawasulPersonMedicalID',
    'description' => 'Medical summary for a person, including long-term medication. Highly sensitive.',
    'select' => "SELECT tawasulPersonMedical.tawasulPersonMedicalID, tawasulPersonMedical.tawasulPersonID, tawasulPersonMedical.longTermMedication, tawasulPersonMedical.longTermMedicationDetails, tawasulPersonMedical.comment, tawasulPerson.surname, tawasulPerson.preferredName, tawasulPerson.studentID FROM tawasulPersonMedical JOIN tawasulPerson ON (tawasulPersonMedical.tawasulPersonID=tawasulPerson.tawasulPersonID)",
    'filters' => ['tawasulPersonID' => 'tawasulPersonMedical.tawasulPersonID', 'longTermMedication' => 'tawasulPersonMedical.longTermMedication'],
    'search' => ['tawasulPerson.surname', 'tawasulPerson.preferredName'],
    'defaultSort' => 'tawasulPerson.surname',
],

'medical-conditions' => [
    'title' => 'Medical Conditions',
    'group' => 'Wellbeing',
    'scope' => 'medical',
    'module' => 'Medical',
    'action' => 'Manage Medical Records',
    'table' => 'tawasulPersonMedicalCondition',
    'primaryKey' => 'tawasulPersonMedicalConditionID',
    'description' => 'Conditions recorded against a medical record, with triggers and response plan.',
    'select' => "SELECT tawasulPersonMedicalCondition.tawasulPersonMedicalConditionID, tawasulPersonMedicalCondition.tawasulPersonMedicalID, tawasulPersonMedicalCondition.name, tawasulPersonMedicalCondition.tawasulAlertLevelID, tawasulPersonMedicalCondition.triggers, tawasulPersonMedicalCondition.reaction, tawasulPersonMedicalCondition.response, tawasulPersonMedicalCondition.medication, tawasulPersonMedicalCondition.lastEpisode, tawasulPersonMedicalCondition.comment, tawasulPersonMedical.tawasulPersonID, tawasulAlertLevel.name AS alertLevelName, tawasulAlertLevel.color AS alertLevelColor FROM tawasulPersonMedicalCondition JOIN tawasulPersonMedical ON (tawasulPersonMedicalCondition.tawasulPersonMedicalID=tawasulPersonMedical.tawasulPersonMedicalID) LEFT JOIN tawasulAlertLevel ON (tawasulPersonMedicalCondition.tawasulAlertLevelID=tawasulAlertLevel.tawasulAlertLevelID)",
    'filters' => ['tawasulPersonMedicalID' => 'tawasulPersonMedicalCondition.tawasulPersonMedicalID', 'tawasulPersonID' => 'tawasulPersonMedical.tawasulPersonID', 'tawasulAlertLevelID' => 'tawasulPersonMedicalCondition.tawasulAlertLevelID'],
    'search' => ['tawasulPersonMedicalCondition.name'],
    'defaultSort' => 'tawasulPersonMedicalCondition.name',
],

'first-aid' => [
    'title' => 'First Aid Records',
    'group' => 'Wellbeing',
    'scope' => 'firstaid',
    'module' => 'TawasulStudents',
    'action' => 'First Aid Record',
    'writeAction' => 'First Aid Record',
    'table' => 'tawasulFirstAid',
    'primaryKey' => 'tawasulFirstAidID',
    'description' => 'First aid incidents, treatment given and follow-up.',
    'select' => "SELECT tawasulFirstAid.tawasulFirstAidID, tawasulFirstAid.tawasulSchoolYearID, tawasulFirstAid.tawasulPersonIDPatient, tawasulFirstAid.tawasulPersonIDFirstAider, tawasulFirstAid.tawasulCourseClassID, tawasulFirstAid.description, tawasulFirstAid.actionTaken, tawasulFirstAid.followUp, tawasulFirstAid.date, tawasulFirstAid.timeIn, tawasulFirstAid.timeOut, patient.surname AS patientSurname, patient.preferredName AS patientPreferredName, aider.surname AS firstAiderSurname, aider.preferredName AS firstAiderPreferredName FROM tawasulFirstAid JOIN tawasulPerson AS patient ON (tawasulFirstAid.tawasulPersonIDPatient=patient.tawasulPersonID) LEFT JOIN tawasulPerson AS aider ON (tawasulFirstAid.tawasulPersonIDFirstAider=aider.tawasulPersonID)",
    'yearFilter' => 'tawasulFirstAid.tawasulSchoolYearID',
    'filters' => ['tawasulPersonIDPatient' => 'tawasulFirstAid.tawasulPersonIDPatient', 'tawasulPersonIDFirstAider' => 'tawasulFirstAid.tawasulPersonIDFirstAider', 'date' => 'tawasulFirstAid.date'],
    'search' => ['patient.surname', 'patient.preferredName', 'tawasulFirstAid.description'],
    'sort' => ['date' => 'tawasulFirstAid.date'],
    'defaultSort' => 'tawasulFirstAid.date DESC, tawasulFirstAid.timeIn DESC',
    'writable' => ['tawasulSchoolYearID', 'tawasulPersonIDPatient', 'tawasulPersonIDFirstAider', 'tawasulCourseClassID', 'description', 'actionTaken', 'followUp', 'date', 'timeIn', 'timeOut'],
    'required' => ['tawasulSchoolYearID', 'tawasulPersonIDPatient', 'description', 'date'],
    'methods' => ['GET', 'POST', 'PATCH', 'PUT', 'DELETE'],
],

];
