-- Rename an existing tos_* (snake) database to the tawasul* naming used by the code.
SET FOREIGN_KEY_CHECKS=0;
RENAME TABLE `tos_action` TO `tawasulAction`;
ALTER TABLE `tawasulAction` RENAME COLUMN `action_id` TO `tawasulActionID`;
ALTER TABLE `tawasulAction` RENAME COLUMN `module_id` TO `tawasulModuleID`;
RENAME TABLE `tos_activity` TO `tawasulActivity`;
ALTER TABLE `tawasulActivity` RENAME COLUMN `activity_id` TO `tawasulActivityID`;
ALTER TABLE `tawasulActivity` RENAME COLUMN `school_year_id` TO `tawasulSchoolYearID`;
ALTER TABLE `tawasulActivity` RENAME COLUMN `activity_category_id` TO `tawasulActivityCategoryID`;
ALTER TABLE `tawasulActivity` RENAME COLUMN `school_year_term_id_list` TO `tawasulSchoolYearTermIDList`;
ALTER TABLE `tawasulActivity` RENAME COLUMN `year_group_id_list` TO `tawasulYearGroupIDList`;
RENAME TABLE `tos_activity_attendance` TO `tawasulActivityAttendance`;
ALTER TABLE `tawasulActivityAttendance` RENAME COLUMN `activity_attendance_id` TO `tawasulActivityAttendanceID`;
ALTER TABLE `tawasulActivityAttendance` RENAME COLUMN `activity_id` TO `tawasulActivityID`;
ALTER TABLE `tawasulActivityAttendance` RENAME COLUMN `person_id_taker` TO `tawasulPersonIDTaker`;
RENAME TABLE `tos_activity_category` TO `tawasulActivityCategory`;
ALTER TABLE `tawasulActivityCategory` RENAME COLUMN `activity_category_id` TO `tawasulActivityCategoryID`;
ALTER TABLE `tawasulActivityCategory` RENAME COLUMN `school_year_id` TO `tawasulSchoolYearID`;
ALTER TABLE `tawasulActivityCategory` RENAME COLUMN `year_group_id_parent_register` TO `tawasulYearGroupIDParentRegister`;
RENAME TABLE `tos_activity_choice` TO `tawasulActivityChoice`;
ALTER TABLE `tawasulActivityChoice` RENAME COLUMN `activity_choice_id` TO `tawasulActivityChoiceID`;
ALTER TABLE `tawasulActivityChoice` RENAME COLUMN `activity_category_id` TO `tawasulActivityCategoryID`;
ALTER TABLE `tawasulActivityChoice` RENAME COLUMN `activity_id` TO `tawasulActivityID`;
ALTER TABLE `tawasulActivityChoice` RENAME COLUMN `person_id` TO `tawasulPersonID`;
ALTER TABLE `tawasulActivityChoice` RENAME COLUMN `person_id_created` TO `tawasulPersonIDCreated`;
ALTER TABLE `tawasulActivityChoice` RENAME COLUMN `person_id_modified` TO `tawasulPersonIDModified`;
RENAME TABLE `tos_activity_photo` TO `tawasulActivityPhoto`;
ALTER TABLE `tawasulActivityPhoto` RENAME COLUMN `activity_photo_id` TO `tawasulActivityPhotoID`;
ALTER TABLE `tawasulActivityPhoto` RENAME COLUMN `activity_id` TO `tawasulActivityID`;
RENAME TABLE `tos_activity_slot` TO `tawasulActivitySlot`;
ALTER TABLE `tawasulActivitySlot` RENAME COLUMN `activity_slot_id` TO `tawasulActivitySlotID`;
ALTER TABLE `tawasulActivitySlot` RENAME COLUMN `activity_id` TO `tawasulActivityID`;
ALTER TABLE `tawasulActivitySlot` RENAME COLUMN `space_id` TO `tawasulSpaceID`;
ALTER TABLE `tawasulActivitySlot` RENAME COLUMN `days_of_week_id` TO `tawasulDaysOfWeekID`;
RENAME TABLE `tos_activity_staff` TO `tawasulActivityStaff`;
ALTER TABLE `tawasulActivityStaff` RENAME COLUMN `activity_staff_id` TO `tawasulActivityStaffID`;
ALTER TABLE `tawasulActivityStaff` RENAME COLUMN `activity_id` TO `tawasulActivityID`;
ALTER TABLE `tawasulActivityStaff` RENAME COLUMN `person_id` TO `tawasulPersonID`;
RENAME TABLE `tos_activity_student` TO `tawasulActivityStudent`;
ALTER TABLE `tawasulActivityStudent` RENAME COLUMN `activity_student_id` TO `tawasulActivityStudentID`;
ALTER TABLE `tawasulActivityStudent` RENAME COLUMN `activity_id` TO `tawasulActivityID`;
ALTER TABLE `tawasulActivityStudent` RENAME COLUMN `person_id` TO `tawasulPersonID`;
ALTER TABLE `tawasulActivityStudent` RENAME COLUMN `activity_id_backup` TO `tawasulActivityIDBackup`;
ALTER TABLE `tawasulActivityStudent` RENAME COLUMN `finance_invoice_id` TO `tawasulFinanceInvoiceID`;
ALTER TABLE `tawasulActivityStudent` RENAME COLUMN `activity_choice_id` TO `tawasulActivityChoiceID`;
RENAME TABLE `tos_activity_type` TO `tawasulActivityType`;
ALTER TABLE `tawasulActivityType` RENAME COLUMN `activity_type_id` TO `tawasulActivityTypeID`;
RENAME TABLE `tos_admissions_account` TO `tawasulAdmissionsAccount`;
ALTER TABLE `tawasulAdmissionsAccount` RENAME COLUMN `admissions_account_id` TO `tawasulAdmissionsAccountID`;
ALTER TABLE `tawasulAdmissionsAccount` RENAME COLUMN `person_id` TO `tawasulPersonID`;
ALTER TABLE `tawasulAdmissionsAccount` RENAME COLUMN `family_id` TO `tawasulFamilyID`;
RENAME TABLE `tos_admissions_application` TO `tawasulAdmissionsApplication`;
ALTER TABLE `tawasulAdmissionsApplication` RENAME COLUMN `admissions_application_id` TO `tawasulAdmissionsApplicationID`;
ALTER TABLE `tawasulAdmissionsApplication` RENAME COLUMN `form_id` TO `tawasulFormID`;
ALTER TABLE `tawasulAdmissionsApplication` RENAME COLUMN `form_page_id` TO `tawasulFormPageID`;
ALTER TABLE `tawasulAdmissionsApplication` RENAME COLUMN `school_year_id` TO `tawasulSchoolYearID`;
ALTER TABLE `tawasulAdmissionsApplication` RENAME COLUMN `year_group_id` TO `tawasulYearGroupID`;
ALTER TABLE `tawasulAdmissionsApplication` RENAME COLUMN `form_group_id` TO `tawasulFormGroupID`;
ALTER TABLE `tawasulAdmissionsApplication` RENAME COLUMN `payment_id_submit` TO `tawasulPaymentIDSubmit`;
ALTER TABLE `tawasulAdmissionsApplication` RENAME COLUMN `payment_id_process` TO `tawasulPaymentIDProcess`;
ALTER TABLE `tawasulAdmissionsApplication` RENAME COLUMN `person_id_modified` TO `tawasulPersonIDModified`;
RENAME TABLE `tos_alarm` TO `tawasulAlarm`;
ALTER TABLE `tawasulAlarm` RENAME COLUMN `alarm_id` TO `tawasulAlarmID`;
ALTER TABLE `tawasulAlarm` RENAME COLUMN `person_id` TO `tawasulPersonID`;
RENAME TABLE `tos_alarm_confirm` TO `tawasulAlarmConfirm`;
ALTER TABLE `tawasulAlarmConfirm` RENAME COLUMN `alarm_confirm_id` TO `tawasulAlarmConfirmID`;
ALTER TABLE `tawasulAlarmConfirm` RENAME COLUMN `alarm_id` TO `tawasulAlarmID`;
ALTER TABLE `tawasulAlarmConfirm` RENAME COLUMN `person_id` TO `tawasulPersonID`;
RENAME TABLE `tos_alert` TO `tawasulAlert`;
ALTER TABLE `tawasulAlert` RENAME COLUMN `alert_id` TO `tawasulAlertID`;
ALTER TABLE `tawasulAlert` RENAME COLUMN `school_year_id` TO `tawasulSchoolYearID`;
ALTER TABLE `tawasulAlert` RENAME COLUMN `person_id` TO `tawasulPersonID`;
ALTER TABLE `tawasulAlert` RENAME COLUMN `course_class_id` TO `tawasulCourseClassID`;
ALTER TABLE `tawasulAlert` RENAME COLUMN `alert_level_id` TO `tawasulAlertLevelID`;
ALTER TABLE `tawasulAlert` RENAME COLUMN `alert_type_id` TO `tawasulAlertTypeID`;
ALTER TABLE `tawasulAlert` RENAME COLUMN `person_id_created` TO `tawasulPersonIDCreated`;
ALTER TABLE `tawasulAlert` RENAME COLUMN `person_id_status` TO `tawasulPersonIDStatus`;
RENAME TABLE `tos_alert_level` TO `tawasulAlertLevel`;
ALTER TABLE `tawasulAlertLevel` RENAME COLUMN `alert_level_id` TO `tawasulAlertLevelID`;
RENAME TABLE `tos_alert_type` TO `tawasulAlertType`;
ALTER TABLE `tawasulAlertType` RENAME COLUMN `alert_type_id` TO `tawasulAlertTypeID`;
ALTER TABLE `tawasulAlertType` RENAME COLUMN `person_id_creator` TO `tawasulPersonIDCreator`;
RENAME TABLE `tos_application_form` TO `tawasulApplicationForm`;
ALTER TABLE `tawasulApplicationForm` RENAME COLUMN `application_form_id` TO `tawasulApplicationFormID`;
ALTER TABLE `tawasulApplicationForm` RENAME COLUMN `tos_application_form_hash` TO `tawasulApplicationFormHash`;
ALTER TABLE `tawasulApplicationForm` RENAME COLUMN `school_year_id_entry` TO `tawasulSchoolYearIDEntry`;
ALTER TABLE `tawasulApplicationForm` RENAME COLUMN `year_group_id_entry` TO `tawasulYearGroupIDEntry`;
ALTER TABLE `tawasulApplicationForm` RENAME COLUMN `family_id` TO `tawasulFamilyID`;
ALTER TABLE `tawasulApplicationForm` RENAME COLUMN `finance_fee_category_id_list` TO `tawasulFinanceFeeCategoryIDList`;
ALTER TABLE `tawasulApplicationForm` RENAME COLUMN `parent1_person_id` TO `parent1tawasulPersonID`;
ALTER TABLE `tawasulApplicationForm` RENAME COLUMN `form_group_id` TO `tawasulFormGroupID`;
ALTER TABLE `tawasulApplicationForm` RENAME COLUMN `payment_id` TO `tawasulPaymentID`;
ALTER TABLE `tawasulApplicationForm` RENAME COLUMN `payment_id2` TO `tawasulPaymentID2`;
RENAME TABLE `tos_application_form_file` TO `tawasulApplicationFormFile`;
ALTER TABLE `tawasulApplicationFormFile` RENAME COLUMN `application_form_file_id` TO `tawasulApplicationFormFileID`;
ALTER TABLE `tawasulApplicationFormFile` RENAME COLUMN `application_form_id` TO `tawasulApplicationFormID`;
RENAME TABLE `tos_application_form_link` TO `tawasulApplicationFormLink`;
ALTER TABLE `tawasulApplicationFormLink` RENAME COLUMN `application_form_link_id` TO `tawasulApplicationFormLinkID`;
ALTER TABLE `tawasulApplicationFormLink` RENAME COLUMN `application_form_id1` TO `tawasulApplicationFormID1`;
ALTER TABLE `tawasulApplicationFormLink` RENAME COLUMN `application_form_id2` TO `tawasulApplicationFormID2`;
RENAME TABLE `tos_application_form_relationship` TO `tawasulApplicationFormRelationship`;
ALTER TABLE `tawasulApplicationFormRelationship` RENAME COLUMN `application_form_relationship_id` TO `tawasulApplicationFormRelationshipID`;
ALTER TABLE `tawasulApplicationFormRelationship` RENAME COLUMN `application_form_id` TO `tawasulApplicationFormID`;
ALTER TABLE `tawasulApplicationFormRelationship` RENAME COLUMN `person_id` TO `tawasulPersonID`;
RENAME TABLE `tos_attendance_code` TO `tawasulAttendanceCode`;
ALTER TABLE `tawasulAttendanceCode` RENAME COLUMN `attendance_code_id` TO `tawasulAttendanceCodeID`;
ALTER TABLE `tawasulAttendanceCode` RENAME COLUMN `role_id_all` TO `tawasulRoleIDAll`;
RENAME TABLE `tos_attendance_log_course_class` TO `tawasulAttendanceLogCourseClass`;
ALTER TABLE `tawasulAttendanceLogCourseClass` RENAME COLUMN `attendance_log_course_class_id` TO `tawasulAttendanceLogCourseClassID`;
ALTER TABLE `tawasulAttendanceLogCourseClass` RENAME COLUMN `course_class_id` TO `tawasulCourseClassID`;
ALTER TABLE `tawasulAttendanceLogCourseClass` RENAME COLUMN `timetable_day_row_class_id` TO `tawasulTTDayRowClassID`;
ALTER TABLE `tawasulAttendanceLogCourseClass` RENAME COLUMN `person_id_taker` TO `tawasulPersonIDTaker`;
RENAME TABLE `tos_attendance_log_form_group` TO `tawasulAttendanceLogFormGroup`;
ALTER TABLE `tawasulAttendanceLogFormGroup` RENAME COLUMN `attendance_log_form_group_id` TO `tawasulAttendanceLogFormGroupID`;
ALTER TABLE `tawasulAttendanceLogFormGroup` RENAME COLUMN `form_group_id` TO `tawasulFormGroupID`;
ALTER TABLE `tawasulAttendanceLogFormGroup` RENAME COLUMN `person_id_taker` TO `tawasulPersonIDTaker`;
RENAME TABLE `tos_attendance_log_person` TO `tawasulAttendanceLogPerson`;
ALTER TABLE `tawasulAttendanceLogPerson` RENAME COLUMN `attendance_log_person_id` TO `tawasulAttendanceLogPersonID`;
ALTER TABLE `tawasulAttendanceLogPerson` RENAME COLUMN `attendance_code_id` TO `tawasulAttendanceCodeID`;
ALTER TABLE `tawasulAttendanceLogPerson` RENAME COLUMN `person_id` TO `tawasulPersonID`;
ALTER TABLE `tawasulAttendanceLogPerson` RENAME COLUMN `person_id_taker` TO `tawasulPersonIDTaker`;
ALTER TABLE `tawasulAttendanceLogPerson` RENAME COLUMN `form_group_id` TO `tawasulFormGroupID`;
ALTER TABLE `tawasulAttendanceLogPerson` RENAME COLUMN `course_class_id` TO `tawasulCourseClassID`;
ALTER TABLE `tawasulAttendanceLogPerson` RENAME COLUMN `timetable_day_row_class_id` TO `tawasulTTDayRowClassID`;
RENAME TABLE `tos_behaviour` TO `tawasulBehaviour`;
ALTER TABLE `tawasulBehaviour` RENAME COLUMN `behaviour_id` TO `tawasulBehaviourID`;
ALTER TABLE `tawasulBehaviour` RENAME COLUMN `school_year_id` TO `tawasulSchoolYearID`;
ALTER TABLE `tawasulBehaviour` RENAME COLUMN `person_id` TO `tawasulPersonID`;
ALTER TABLE `tawasulBehaviour` RENAME COLUMN `planner_entry_id` TO `tawasulPlannerEntryID`;
ALTER TABLE `tawasulBehaviour` RENAME COLUMN `person_id_creator` TO `tawasulPersonIDCreator`;
ALTER TABLE `tawasulBehaviour` RENAME COLUMN `multi_incident_id` TO `tawasulMultiIncidentID`;
RENAME TABLE `tos_behaviour_follow_up` TO `tawasulBehaviourFollowUp`;
ALTER TABLE `tawasulBehaviourFollowUp` RENAME COLUMN `behaviour_follow_up_id` TO `tawasulBehaviourFollowUpID`;
ALTER TABLE `tawasulBehaviourFollowUp` RENAME COLUMN `behaviour_id` TO `tawasulBehaviourID`;
ALTER TABLE `tawasulBehaviourFollowUp` RENAME COLUMN `person_id` TO `tawasulPersonID`;
RENAME TABLE `tos_behaviour_letter` TO `tawasulBehaviourLetter`;
ALTER TABLE `tawasulBehaviourLetter` RENAME COLUMN `behaviour_letter_id` TO `tawasulBehaviourLetterID`;
ALTER TABLE `tawasulBehaviourLetter` RENAME COLUMN `school_year_id` TO `tawasulSchoolYearID`;
ALTER TABLE `tawasulBehaviourLetter` RENAME COLUMN `person_id` TO `tawasulPersonID`;
RENAME TABLE `tos_calendar` TO `tawasulCalendar`;
ALTER TABLE `tawasulCalendar` RENAME COLUMN `calendar_id` TO `tawasulCalendarID`;
ALTER TABLE `tawasulCalendar` RENAME COLUMN `school_year_id` TO `tawasulSchoolYearID`;
RENAME TABLE `tos_calendar_editor` TO `tawasulCalendarEditor`;
ALTER TABLE `tawasulCalendarEditor` RENAME COLUMN `calendar_editor_id` TO `tawasulCalendarEditorID`;
ALTER TABLE `tawasulCalendarEditor` RENAME COLUMN `calendar_id` TO `tawasulCalendarID`;
ALTER TABLE `tawasulCalendarEditor` RENAME COLUMN `person_id` TO `tawasulPersonID`;
RENAME TABLE `tos_calendar_event` TO `tawasulCalendarEvent`;
ALTER TABLE `tawasulCalendarEvent` RENAME COLUMN `calendar_event_id` TO `tawasulCalendarEventID`;
ALTER TABLE `tawasulCalendarEvent` RENAME COLUMN `calendar_id` TO `tawasulCalendarID`;
ALTER TABLE `tawasulCalendarEvent` RENAME COLUMN `calendar_event_type_id` TO `tawasulCalendarEventTypeID`;
ALTER TABLE `tawasulCalendarEvent` RENAME COLUMN `space_id` TO `tawasulSpaceID`;
ALTER TABLE `tawasulCalendarEvent` RENAME COLUMN `person_id_created` TO `tawasulPersonIDCreated`;
ALTER TABLE `tawasulCalendarEvent` RENAME COLUMN `person_id_modified` TO `tawasulPersonIDModified`;
ALTER TABLE `tawasulCalendarEvent` RENAME COLUMN `person_id_organiser` TO `tawasulPersonIDOrganiser`;
RENAME TABLE `tos_calendar_event_person` TO `tawasulCalendarEventPerson`;
ALTER TABLE `tawasulCalendarEventPerson` RENAME COLUMN `calendar_event_person_id` TO `tawasulCalendarEventPersonID`;
ALTER TABLE `tawasulCalendarEventPerson` RENAME COLUMN `calendar_event_id` TO `tawasulCalendarEventID`;
ALTER TABLE `tawasulCalendarEventPerson` RENAME COLUMN `person_id` TO `tawasulPersonID`;
ALTER TABLE `tawasulCalendarEventPerson` RENAME COLUMN `person_id_created` TO `tawasulPersonIDCreated`;
ALTER TABLE `tawasulCalendarEventPerson` RENAME COLUMN `person_id_modified` TO `tawasulPersonIDModified`;
RENAME TABLE `tos_calendar_event_type` TO `tawasulCalendarEventType`;
ALTER TABLE `tawasulCalendarEventType` RENAME COLUMN `calendar_event_type_id` TO `tawasulCalendarEventTypeID`;
RENAME TABLE `tos_country` TO `tawasulCountry`;
RENAME TABLE `tos_course` TO `tawasulCourse`;
ALTER TABLE `tawasulCourse` RENAME COLUMN `course_id` TO `tawasulCourseID`;
ALTER TABLE `tawasulCourse` RENAME COLUMN `school_year_id` TO `tawasulSchoolYearID`;
ALTER TABLE `tawasulCourse` RENAME COLUMN `department_id` TO `tawasulDepartmentID`;
ALTER TABLE `tawasulCourse` RENAME COLUMN `year_group_id_list` TO `tawasulYearGroupIDList`;
RENAME TABLE `tos_course_class` TO `tawasulCourseClass`;
ALTER TABLE `tawasulCourseClass` RENAME COLUMN `course_class_id` TO `tawasulCourseClassID`;
ALTER TABLE `tawasulCourseClass` RENAME COLUMN `course_id` TO `tawasulCourseID`;
ALTER TABLE `tawasulCourseClass` RENAME COLUMN `scale_id_target` TO `tawasulScaleIDTarget`;
RENAME TABLE `tos_course_class_map` TO `tawasulCourseClassMap`;
ALTER TABLE `tawasulCourseClassMap` RENAME COLUMN `course_class_map_id` TO `tawasulCourseClassMapID`;
ALTER TABLE `tawasulCourseClassMap` RENAME COLUMN `course_class_id` TO `tawasulCourseClassID`;
ALTER TABLE `tawasulCourseClassMap` RENAME COLUMN `form_group_id` TO `tawasulFormGroupID`;
ALTER TABLE `tawasulCourseClassMap` RENAME COLUMN `year_group_id` TO `tawasulYearGroupID`;
RENAME TABLE `tos_course_class_person` TO `tawasulCourseClassPerson`;
ALTER TABLE `tawasulCourseClassPerson` RENAME COLUMN `course_class_person_id` TO `tawasulCourseClassPersonID`;
ALTER TABLE `tawasulCourseClassPerson` RENAME COLUMN `course_class_id` TO `tawasulCourseClassID`;
ALTER TABLE `tawasulCourseClassPerson` RENAME COLUMN `person_id` TO `tawasulPersonID`;
RENAME TABLE `tos_crowd_assess_discuss` TO `tawasulCrowdAssessDiscuss`;
ALTER TABLE `tawasulCrowdAssessDiscuss` RENAME COLUMN `crowd_assess_discuss_id` TO `tawasulCrowdAssessDiscussID`;
ALTER TABLE `tawasulCrowdAssessDiscuss` RENAME COLUMN `planner_entry_homework_id` TO `tawasulPlannerEntryHomeworkID`;
ALTER TABLE `tawasulCrowdAssessDiscuss` RENAME COLUMN `person_id` TO `tawasulPersonID`;
ALTER TABLE `tawasulCrowdAssessDiscuss` RENAME COLUMN `crowd_assess_discuss_id_reply_to` TO `tawasulCrowdAssessDiscussIDReplyTo`;
RENAME TABLE `tos_custom_field` TO `tawasulCustomField`;
ALTER TABLE `tawasulCustomField` RENAME COLUMN `custom_field_id` TO `tawasulCustomFieldID`;
RENAME TABLE `tos_data_retention` TO `tawasulDataRetention`;
ALTER TABLE `tawasulDataRetention` RENAME COLUMN `data_retention_id` TO `tawasulDataRetentionID`;
ALTER TABLE `tawasulDataRetention` RENAME COLUMN `person_id` TO `tawasulPersonID`;
ALTER TABLE `tawasulDataRetention` RENAME COLUMN `person_id_operator` TO `tawasulPersonIDOperator`;
RENAME TABLE `tos_days_of_week` TO `tawasulDaysOfWeek`;
ALTER TABLE `tawasulDaysOfWeek` RENAME COLUMN `days_of_week_id` TO `tawasulDaysOfWeekID`;
RENAME TABLE `tos_department` TO `tawasulDepartment`;
ALTER TABLE `tawasulDepartment` RENAME COLUMN `department_id` TO `tawasulDepartmentID`;
RENAME TABLE `tos_department_resource` TO `tawasulDepartmentResource`;
ALTER TABLE `tawasulDepartmentResource` RENAME COLUMN `department_resource_id` TO `tawasulDepartmentResourceID`;
ALTER TABLE `tawasulDepartmentResource` RENAME COLUMN `department_id` TO `tawasulDepartmentID`;
RENAME TABLE `tos_department_staff` TO `tawasulDepartmentStaff`;
ALTER TABLE `tawasulDepartmentStaff` RENAME COLUMN `department_staff_id` TO `tawasulDepartmentStaffID`;
ALTER TABLE `tawasulDepartmentStaff` RENAME COLUMN `department_id` TO `tawasulDepartmentID`;
ALTER TABLE `tawasulDepartmentStaff` RENAME COLUMN `person_id` TO `tawasulPersonID`;
RENAME TABLE `tos_discussion` TO `tawasulDiscussion`;
ALTER TABLE `tawasulDiscussion` RENAME COLUMN `discussion_id` TO `tawasulDiscussionID`;
ALTER TABLE `tawasulDiscussion` RENAME COLUMN `module_id` TO `tawasulModuleID`;
ALTER TABLE `tawasulDiscussion` RENAME COLUMN `person_id` TO `tawasulPersonID`;
ALTER TABLE `tawasulDiscussion` RENAME COLUMN `person_id_target` TO `tawasulPersonIDTarget`;
ALTER TABLE `tawasulDiscussion` RENAME COLUMN `discussion_id_reply_to` TO `tawasulDiscussionIDReplyTo`;
RENAME TABLE `tos_district` TO `tawasulDistrict`;
ALTER TABLE `tawasulDistrict` RENAME COLUMN `district_id` TO `tawasulDistrictID`;
RENAME TABLE `tos_email_template` TO `tawasulEmailTemplate`;
ALTER TABLE `tawasulEmailTemplate` RENAME COLUMN `email_template_id` TO `tawasulEmailTemplateID`;
RENAME TABLE `tos_external_assessment` TO `tawasulExternalAssessment`;
ALTER TABLE `tawasulExternalAssessment` RENAME COLUMN `external_assessment_id` TO `tawasulExternalAssessmentID`;
RENAME TABLE `tos_external_assessment_field` TO `tawasulExternalAssessmentField`;
ALTER TABLE `tawasulExternalAssessmentField` RENAME COLUMN `external_assessment_field_id` TO `tawasulExternalAssessmentFieldID`;
ALTER TABLE `tawasulExternalAssessmentField` RENAME COLUMN `external_assessment_id` TO `tawasulExternalAssessmentID`;
ALTER TABLE `tawasulExternalAssessmentField` RENAME COLUMN `scale_id` TO `tawasulScaleID`;
ALTER TABLE `tawasulExternalAssessmentField` RENAME COLUMN `year_group_id_list` TO `tawasulYearGroupIDList`;
RENAME TABLE `tos_external_assessment_student` TO `tawasulExternalAssessmentStudent`;
ALTER TABLE `tawasulExternalAssessmentStudent` RENAME COLUMN `external_assessment_student_id` TO `tawasulExternalAssessmentStudentID`;
ALTER TABLE `tawasulExternalAssessmentStudent` RENAME COLUMN `external_assessment_id` TO `tawasulExternalAssessmentID`;
ALTER TABLE `tawasulExternalAssessmentStudent` RENAME COLUMN `person_id` TO `tawasulPersonID`;
RENAME TABLE `tos_external_assessment_student_entry` TO `tawasulExternalAssessmentStudentEntry`;
ALTER TABLE `tawasulExternalAssessmentStudentEntry` RENAME COLUMN `external_assessment_student_entry_id` TO `tawasulExternalAssessmentStudentEntryID`;
ALTER TABLE `tawasulExternalAssessmentStudentEntry` RENAME COLUMN `external_assessment_student_id` TO `tawasulExternalAssessmentStudentID`;
ALTER TABLE `tawasulExternalAssessmentStudentEntry` RENAME COLUMN `external_assessment_field_id` TO `tawasulExternalAssessmentFieldID`;
ALTER TABLE `tawasulExternalAssessmentStudentEntry` RENAME COLUMN `scale_grade_id` TO `tawasulScaleGradeID`;
RENAME TABLE `tos_family` TO `tawasulFamily`;
ALTER TABLE `tawasulFamily` RENAME COLUMN `family_id` TO `tawasulFamilyID`;
RENAME TABLE `tos_family_adult` TO `tawasulFamilyAdult`;
ALTER TABLE `tawasulFamilyAdult` RENAME COLUMN `family_adult_id` TO `tawasulFamilyAdultID`;
ALTER TABLE `tawasulFamilyAdult` RENAME COLUMN `family_id` TO `tawasulFamilyID`;
ALTER TABLE `tawasulFamilyAdult` RENAME COLUMN `person_id` TO `tawasulPersonID`;
RENAME TABLE `tos_family_child` TO `tawasulFamilyChild`;
ALTER TABLE `tawasulFamilyChild` RENAME COLUMN `family_child_id` TO `tawasulFamilyChildID`;
ALTER TABLE `tawasulFamilyChild` RENAME COLUMN `family_id` TO `tawasulFamilyID`;
ALTER TABLE `tawasulFamilyChild` RENAME COLUMN `person_id` TO `tawasulPersonID`;
RENAME TABLE `tos_family_relationship` TO `tawasulFamilyRelationship`;
ALTER TABLE `tawasulFamilyRelationship` RENAME COLUMN `family_relationship_id` TO `tawasulFamilyRelationshipID`;
ALTER TABLE `tawasulFamilyRelationship` RENAME COLUMN `family_id` TO `tawasulFamilyID`;
ALTER TABLE `tawasulFamilyRelationship` RENAME COLUMN `person_id1` TO `tawasulPersonID1`;
ALTER TABLE `tawasulFamilyRelationship` RENAME COLUMN `person_id2` TO `tawasulPersonID2`;
RENAME TABLE `tos_family_update` TO `tawasulFamilyUpdate`;
ALTER TABLE `tawasulFamilyUpdate` RENAME COLUMN `family_update_id` TO `tawasulFamilyUpdateID`;
ALTER TABLE `tawasulFamilyUpdate` RENAME COLUMN `school_year_id` TO `tawasulSchoolYearID`;
ALTER TABLE `tawasulFamilyUpdate` RENAME COLUMN `family_id` TO `tawasulFamilyID`;
ALTER TABLE `tawasulFamilyUpdate` RENAME COLUMN `person_id_updater` TO `tawasulPersonIDUpdater`;
RENAME TABLE `tos_file_extension` TO `tawasulFileExtension`;
ALTER TABLE `tawasulFileExtension` RENAME COLUMN `file_extension_id` TO `tawasulFileExtensionID`;
RENAME TABLE `tos_finance_billing_schedule` TO `tawasulFinanceBillingSchedule`;
ALTER TABLE `tawasulFinanceBillingSchedule` RENAME COLUMN `finance_billing_schedule_id` TO `tawasulFinanceBillingScheduleID`;
ALTER TABLE `tawasulFinanceBillingSchedule` RENAME COLUMN `school_year_id` TO `tawasulSchoolYearID`;
ALTER TABLE `tawasulFinanceBillingSchedule` RENAME COLUMN `person_id_creator` TO `tawasulPersonIDCreator`;
ALTER TABLE `tawasulFinanceBillingSchedule` RENAME COLUMN `person_id_update` TO `tawasulPersonIDUpdate`;
RENAME TABLE `tos_finance_budget` TO `tawasulFinanceBudget`;
ALTER TABLE `tawasulFinanceBudget` RENAME COLUMN `finance_budget_id` TO `tawasulFinanceBudgetID`;
ALTER TABLE `tawasulFinanceBudget` RENAME COLUMN `person_id_creator` TO `tawasulPersonIDCreator`;
ALTER TABLE `tawasulFinanceBudget` RENAME COLUMN `person_id_update` TO `tawasulPersonIDUpdate`;
RENAME TABLE `tos_finance_budget_cycle` TO `tawasulFinanceBudgetCycle`;
ALTER TABLE `tawasulFinanceBudgetCycle` RENAME COLUMN `finance_budget_cycle_id` TO `tawasulFinanceBudgetCycleID`;
ALTER TABLE `tawasulFinanceBudgetCycle` RENAME COLUMN `person_id_creator` TO `tawasulPersonIDCreator`;
ALTER TABLE `tawasulFinanceBudgetCycle` RENAME COLUMN `person_id_update` TO `tawasulPersonIDUpdate`;
RENAME TABLE `tos_finance_budget_cycle_allocation` TO `tawasulFinanceBudgetCycleAllocation`;
ALTER TABLE `tawasulFinanceBudgetCycleAllocation` RENAME COLUMN `finance_budget_cycle_allocation_id` TO `tawasulFinanceBudgetCycleAllocationID`;
ALTER TABLE `tawasulFinanceBudgetCycleAllocation` RENAME COLUMN `finance_budget_id` TO `tawasulFinanceBudgetID`;
ALTER TABLE `tawasulFinanceBudgetCycleAllocation` RENAME COLUMN `finance_budget_cycle_id` TO `tawasulFinanceBudgetCycleID`;
RENAME TABLE `tos_finance_budget_person` TO `tawasulFinanceBudgetPerson`;
ALTER TABLE `tawasulFinanceBudgetPerson` RENAME COLUMN `finance_budget_person_id` TO `tawasulFinanceBudgetPersonID`;
ALTER TABLE `tawasulFinanceBudgetPerson` RENAME COLUMN `finance_budget_id` TO `tawasulFinanceBudgetID`;
ALTER TABLE `tawasulFinanceBudgetPerson` RENAME COLUMN `person_id` TO `tawasulPersonID`;
RENAME TABLE `tos_finance_expense` TO `tawasulFinanceExpense`;
ALTER TABLE `tawasulFinanceExpense` RENAME COLUMN `finance_expense_id` TO `tawasulFinanceExpenseID`;
ALTER TABLE `tawasulFinanceExpense` RENAME COLUMN `finance_budget_id` TO `tawasulFinanceBudgetID`;
ALTER TABLE `tawasulFinanceExpense` RENAME COLUMN `finance_budget_cycle_id` TO `tawasulFinanceBudgetCycleID`;
ALTER TABLE `tawasulFinanceExpense` RENAME COLUMN `person_id_payment` TO `tawasulPersonIDPayment`;
ALTER TABLE `tawasulFinanceExpense` RENAME COLUMN `person_id_creator` TO `tawasulPersonIDCreator`;
RENAME TABLE `tos_finance_expense_approver` TO `tawasulFinanceExpenseApprover`;
ALTER TABLE `tawasulFinanceExpenseApprover` RENAME COLUMN `finance_expense_approver_id` TO `tawasulFinanceExpenseApproverID`;
ALTER TABLE `tawasulFinanceExpenseApprover` RENAME COLUMN `person_id` TO `tawasulPersonID`;
ALTER TABLE `tawasulFinanceExpenseApprover` RENAME COLUMN `person_id_creator` TO `tawasulPersonIDCreator`;
ALTER TABLE `tawasulFinanceExpenseApprover` RENAME COLUMN `person_id_update` TO `tawasulPersonIDUpdate`;
RENAME TABLE `tos_finance_expense_log` TO `tawasulFinanceExpenseLog`;
ALTER TABLE `tawasulFinanceExpenseLog` RENAME COLUMN `finance_expense_log_id` TO `tawasulFinanceExpenseLogID`;
ALTER TABLE `tawasulFinanceExpenseLog` RENAME COLUMN `finance_expense_id` TO `tawasulFinanceExpenseID`;
ALTER TABLE `tawasulFinanceExpenseLog` RENAME COLUMN `person_id` TO `tawasulPersonID`;
RENAME TABLE `tos_finance_fee` TO `tawasulFinanceFee`;
ALTER TABLE `tawasulFinanceFee` RENAME COLUMN `finance_fee_id` TO `tawasulFinanceFeeID`;
ALTER TABLE `tawasulFinanceFee` RENAME COLUMN `school_year_id` TO `tawasulSchoolYearID`;
ALTER TABLE `tawasulFinanceFee` RENAME COLUMN `finance_fee_category_id` TO `tawasulFinanceFeeCategoryID`;
ALTER TABLE `tawasulFinanceFee` RENAME COLUMN `person_id_creator` TO `tawasulPersonIDCreator`;
ALTER TABLE `tawasulFinanceFee` RENAME COLUMN `person_id_update` TO `tawasulPersonIDUpdate`;
RENAME TABLE `tos_finance_fee_category` TO `tawasulFinanceFeeCategory`;
ALTER TABLE `tawasulFinanceFeeCategory` RENAME COLUMN `finance_fee_category_id` TO `tawasulFinanceFeeCategoryID`;
ALTER TABLE `tawasulFinanceFeeCategory` RENAME COLUMN `person_id_creator` TO `tawasulPersonIDCreator`;
ALTER TABLE `tawasulFinanceFeeCategory` RENAME COLUMN `person_id_update` TO `tawasulPersonIDUpdate`;
RENAME TABLE `tos_finance_invoice` TO `tawasulFinanceInvoice`;
ALTER TABLE `tawasulFinanceInvoice` RENAME COLUMN `finance_invoice_id` TO `tawasulFinanceInvoiceID`;
ALTER TABLE `tawasulFinanceInvoice` RENAME COLUMN `school_year_id` TO `tawasulSchoolYearID`;
ALTER TABLE `tawasulFinanceInvoice` RENAME COLUMN `finance_invoicee_id` TO `tawasulFinanceInvoiceeID`;
ALTER TABLE `tawasulFinanceInvoice` RENAME COLUMN `finance_billing_schedule_id` TO `tawasulFinanceBillingScheduleID`;
ALTER TABLE `tawasulFinanceInvoice` RENAME COLUMN `finance_fee_category_id_list` TO `tawasulFinanceFeeCategoryIDList`;
ALTER TABLE `tawasulFinanceInvoice` RENAME COLUMN `payment_id` TO `tawasulPaymentID`;
ALTER TABLE `tawasulFinanceInvoice` RENAME COLUMN `person_id_creator` TO `tawasulPersonIDCreator`;
ALTER TABLE `tawasulFinanceInvoice` RENAME COLUMN `person_id_update` TO `tawasulPersonIDUpdate`;
RENAME TABLE `tos_finance_invoicee` TO `tawasulFinanceInvoicee`;
ALTER TABLE `tawasulFinanceInvoicee` RENAME COLUMN `finance_invoicee_id` TO `tawasulFinanceInvoiceeID`;
ALTER TABLE `tawasulFinanceInvoicee` RENAME COLUMN `person_id` TO `tawasulPersonID`;
ALTER TABLE `tawasulFinanceInvoicee` RENAME COLUMN `finance_fee_category_id_list` TO `tawasulFinanceFeeCategoryIDList`;
RENAME TABLE `tos_finance_invoicee_update` TO `tawasulFinanceInvoiceeUpdate`;
ALTER TABLE `tawasulFinanceInvoiceeUpdate` RENAME COLUMN `finance_invoicee_update_id` TO `tawasulFinanceInvoiceeUpdateID`;
ALTER TABLE `tawasulFinanceInvoiceeUpdate` RENAME COLUMN `school_year_id` TO `tawasulSchoolYearID`;
ALTER TABLE `tawasulFinanceInvoiceeUpdate` RENAME COLUMN `finance_invoicee_id` TO `tawasulFinanceInvoiceeID`;
ALTER TABLE `tawasulFinanceInvoiceeUpdate` RENAME COLUMN `finance_fee_category_id_list` TO `tawasulFinanceFeeCategoryIDList`;
ALTER TABLE `tawasulFinanceInvoiceeUpdate` RENAME COLUMN `person_id_updater` TO `tawasulPersonIDUpdater`;
RENAME TABLE `tos_finance_invoice_fee` TO `tawasulFinanceInvoiceFee`;
ALTER TABLE `tawasulFinanceInvoiceFee` RENAME COLUMN `finance_invoice_fee_id` TO `tawasulFinanceInvoiceFeeID`;
ALTER TABLE `tawasulFinanceInvoiceFee` RENAME COLUMN `finance_invoice_id` TO `tawasulFinanceInvoiceID`;
ALTER TABLE `tawasulFinanceInvoiceFee` RENAME COLUMN `finance_fee_id` TO `tawasulFinanceFeeID`;
ALTER TABLE `tawasulFinanceInvoiceFee` RENAME COLUMN `finance_fee_category_id` TO `tawasulFinanceFeeCategoryID`;
RENAME TABLE `tos_finance_petty_cash` TO `tawasulFinancePettyCash`;
ALTER TABLE `tawasulFinancePettyCash` RENAME COLUMN `finance_petty_cash_id` TO `tawasulFinancePettyCashID`;
ALTER TABLE `tawasulFinancePettyCash` RENAME COLUMN `school_year_id` TO `tawasulSchoolYearID`;
ALTER TABLE `tawasulFinancePettyCash` RENAME COLUMN `person_id` TO `tawasulPersonID`;
ALTER TABLE `tawasulFinancePettyCash` RENAME COLUMN `person_id_created` TO `tawasulPersonIDCreated`;
ALTER TABLE `tawasulFinancePettyCash` RENAME COLUMN `person_id_status` TO `tawasulPersonIDStatus`;
RENAME TABLE `tos_first_aid` TO `tawasulFirstAid`;
ALTER TABLE `tawasulFirstAid` RENAME COLUMN `first_aid_id` TO `tawasulFirstAidID`;
ALTER TABLE `tawasulFirstAid` RENAME COLUMN `person_id_patient` TO `tawasulPersonIDPatient`;
ALTER TABLE `tawasulFirstAid` RENAME COLUMN `course_class_id` TO `tawasulCourseClassID`;
ALTER TABLE `tawasulFirstAid` RENAME COLUMN `person_id_first_aider` TO `tawasulPersonIDFirstAider`;
ALTER TABLE `tawasulFirstAid` RENAME COLUMN `person_id_follow_up` TO `tawasulPersonIDFollowUp`;
ALTER TABLE `tawasulFirstAid` RENAME COLUMN `school_year_id` TO `tawasulSchoolYearID`;
RENAME TABLE `tos_first_aid_follow_up` TO `tawasulFirstAidFollowUp`;
ALTER TABLE `tawasulFirstAidFollowUp` RENAME COLUMN `first_aid_follow_up_id` TO `tawasulFirstAidFollowUpID`;
ALTER TABLE `tawasulFirstAidFollowUp` RENAME COLUMN `first_aid_id` TO `tawasulFirstAidID`;
ALTER TABLE `tawasulFirstAidFollowUp` RENAME COLUMN `person_id` TO `tawasulPersonID`;
RENAME TABLE `tos_form` TO `tawasulForm`;
ALTER TABLE `tawasulForm` RENAME COLUMN `form_id` TO `tawasulFormID`;
ALTER TABLE `tawasulForm` RENAME COLUMN `year_group_id_list` TO `tawasulYearGroupIDList`;
RENAME TABLE `tos_form_field` TO `tawasulFormField`;
ALTER TABLE `tawasulFormField` RENAME COLUMN `form_field_id` TO `tawasulFormFieldID`;
ALTER TABLE `tawasulFormField` RENAME COLUMN `form_page_id` TO `tawasulFormPageID`;
RENAME TABLE `tos_form_group` TO `tawasulFormGroup`;
ALTER TABLE `tawasulFormGroup` RENAME COLUMN `form_group_id` TO `tawasulFormGroupID`;
ALTER TABLE `tawasulFormGroup` RENAME COLUMN `school_year_id` TO `tawasulSchoolYearID`;
ALTER TABLE `tawasulFormGroup` RENAME COLUMN `person_id_tutor` TO `tawasulPersonIDTutor`;
ALTER TABLE `tawasulFormGroup` RENAME COLUMN `person_id_tutor2` TO `tawasulPersonIDTutor2`;
ALTER TABLE `tawasulFormGroup` RENAME COLUMN `person_id_tutor3` TO `tawasulPersonIDTutor3`;
ALTER TABLE `tawasulFormGroup` RENAME COLUMN `person_id_ea` TO `tawasulPersonIDEA`;
ALTER TABLE `tawasulFormGroup` RENAME COLUMN `person_id_ea2` TO `tawasulPersonIDEA2`;
ALTER TABLE `tawasulFormGroup` RENAME COLUMN `person_id_ea3` TO `tawasulPersonIDEA3`;
ALTER TABLE `tawasulFormGroup` RENAME COLUMN `space_id` TO `tawasulSpaceID`;
ALTER TABLE `tawasulFormGroup` RENAME COLUMN `form_group_id_next` TO `tawasulFormGroupIDNext`;
RENAME TABLE `tos_form_page` TO `tawasulFormPage`;
ALTER TABLE `tawasulFormPage` RENAME COLUMN `form_page_id` TO `tawasulFormPageID`;
ALTER TABLE `tawasulFormPage` RENAME COLUMN `form_id` TO `tawasulFormID`;
RENAME TABLE `tos_form_submission` TO `tawasulFormSubmission`;
ALTER TABLE `tawasulFormSubmission` RENAME COLUMN `form_submission_id` TO `tawasulFormSubmissionID`;
ALTER TABLE `tawasulFormSubmission` RENAME COLUMN `form_id` TO `tawasulFormID`;
ALTER TABLE `tawasulFormSubmission` RENAME COLUMN `form_page_id` TO `tawasulFormPageID`;
ALTER TABLE `tawasulFormSubmission` RENAME COLUMN `person_id_modified` TO `tawasulPersonIDModified`;
RENAME TABLE `tos_form_upload` TO `tawasulFormUpload`;
ALTER TABLE `tawasulFormUpload` RENAME COLUMN `form_upload_id` TO `tawasulFormUploadID`;
ALTER TABLE `tawasulFormUpload` RENAME COLUMN `form_id` TO `tawasulFormID`;
ALTER TABLE `tawasulFormUpload` RENAME COLUMN `form_field_id` TO `tawasulFormFieldID`;
RENAME TABLE `tos_group` TO `tawasulGroup`;
ALTER TABLE `tawasulGroup` RENAME COLUMN `group_id` TO `tawasulGroupID`;
ALTER TABLE `tawasulGroup` RENAME COLUMN `person_id_owner` TO `tawasulPersonIDOwner`;
ALTER TABLE `tawasulGroup` RENAME COLUMN `school_year_id` TO `tawasulSchoolYearID`;
RENAME TABLE `tos_group_person` TO `tawasulGroupPerson`;
ALTER TABLE `tawasulGroupPerson` RENAME COLUMN `group_person_id` TO `tawasulGroupPersonID`;
ALTER TABLE `tawasulGroupPerson` RENAME COLUMN `group_id` TO `tawasulGroupID`;
ALTER TABLE `tawasulGroupPerson` RENAME COLUMN `person_id` TO `tawasulPersonID`;
RENAME TABLE `tos_hook` TO `tawasulHook`;
ALTER TABLE `tawasulHook` RENAME COLUMN `hook_id` TO `tawasulHookID`;
ALTER TABLE `tawasulHook` RENAME COLUMN `module_id` TO `tawasulModuleID`;
RENAME TABLE `tos_house` TO `tawasulHouse`;
ALTER TABLE `tawasulHouse` RENAME COLUMN `house_id` TO `tawasulHouseID`;
RENAME TABLE `tos_i18n` TO `tawasuli18n`;
ALTER TABLE `tawasuli18n` RENAME COLUMN `i18n_id` TO `tawasuli18nID`;
RENAME TABLE `tos_individual_needs` TO `tawasulIN`;
ALTER TABLE `tawasulIN` RENAME COLUMN `individual_needs_id` TO `tawasulINID`;
ALTER TABLE `tawasulIN` RENAME COLUMN `person_id` TO `tawasulPersonID`;
RENAME TABLE `tos_individual_needs_archive` TO `tawasulINArchive`;
ALTER TABLE `tawasulINArchive` RENAME COLUMN `individual_needs_archive_id` TO `tawasulINArchiveID`;
ALTER TABLE `tawasulINArchive` RENAME COLUMN `person_id` TO `tawasulPersonID`;
RENAME TABLE `tos_individual_needs_assistant` TO `tawasulINAssistant`;
ALTER TABLE `tawasulINAssistant` RENAME COLUMN `individual_needs_assistant_id` TO `tawasulINAssistantID`;
ALTER TABLE `tawasulINAssistant` RENAME COLUMN `person_id_student` TO `tawasulPersonIDStudent`;
ALTER TABLE `tawasulINAssistant` RENAME COLUMN `person_id_assistant` TO `tawasulPersonIDAssistant`;
RENAME TABLE `tos_individual_needs_descriptor` TO `tawasulINDescriptor`;
ALTER TABLE `tawasulINDescriptor` RENAME COLUMN `individual_needs_descriptor_id` TO `tawasulINDescriptorID`;
RENAME TABLE `tos_individual_needs_investigation` TO `tawasulINInvestigation`;
ALTER TABLE `tawasulINInvestigation` RENAME COLUMN `individual_needs_investigation_id` TO `tawasulINInvestigationID`;
ALTER TABLE `tawasulINInvestigation` RENAME COLUMN `school_year_id` TO `tawasulSchoolYearID`;
ALTER TABLE `tawasulINInvestigation` RENAME COLUMN `person_id_creator` TO `tawasulPersonIDCreator`;
ALTER TABLE `tawasulINInvestigation` RENAME COLUMN `person_id_student` TO `tawasulPersonIDStudent`;
RENAME TABLE `tos_individual_needs_investigation_contribution` TO `tawasulINInvestigationContribution`;
ALTER TABLE `tawasulINInvestigationContribution` RENAME COLUMN `individual_needs_investigation_contribution_id` TO `tawasulINInvestigationContributionID`;
ALTER TABLE `tawasulINInvestigationContribution` RENAME COLUMN `individual_needs_investigation_id` TO `tawasulINInvestigationID`;
ALTER TABLE `tawasulINInvestigationContribution` RENAME COLUMN `person_id` TO `tawasulPersonID`;
ALTER TABLE `tawasulINInvestigationContribution` RENAME COLUMN `course_class_person_id` TO `tawasulCourseClassPersonID`;
RENAME TABLE `tos_individual_needs_person_descriptor` TO `tawasulINPersonDescriptor`;
ALTER TABLE `tawasulINPersonDescriptor` RENAME COLUMN `individual_needs_person_descriptor_id` TO `tawasulINPersonDescriptorID`;
ALTER TABLE `tawasulINPersonDescriptor` RENAME COLUMN `person_id` TO `tawasulPersonID`;
ALTER TABLE `tawasulINPersonDescriptor` RENAME COLUMN `individual_needs_descriptor_id` TO `tawasulINDescriptorID`;
ALTER TABLE `tawasulINPersonDescriptor` RENAME COLUMN `alert_level_id` TO `tawasulAlertLevelID`;
RENAME TABLE `tos_internal_assessment_column` TO `tawasulInternalAssessmentColumn`;
ALTER TABLE `tawasulInternalAssessmentColumn` RENAME COLUMN `internal_assessment_column_id` TO `tawasulInternalAssessmentColumnID`;
ALTER TABLE `tawasulInternalAssessmentColumn` RENAME COLUMN `course_class_id` TO `tawasulCourseClassID`;
ALTER TABLE `tawasulInternalAssessmentColumn` RENAME COLUMN `scale_id_attainment` TO `tawasulScaleIDAttainment`;
ALTER TABLE `tawasulInternalAssessmentColumn` RENAME COLUMN `scale_id_effort` TO `tawasulScaleIDEffort`;
ALTER TABLE `tawasulInternalAssessmentColumn` RENAME COLUMN `person_id_creator` TO `tawasulPersonIDCreator`;
ALTER TABLE `tawasulInternalAssessmentColumn` RENAME COLUMN `person_id_last_edit` TO `tawasulPersonIDLastEdit`;
RENAME TABLE `tos_internal_assessment_entry` TO `tawasulInternalAssessmentEntry`;
ALTER TABLE `tawasulInternalAssessmentEntry` RENAME COLUMN `internal_assessment_entry_id` TO `tawasulInternalAssessmentEntryID`;
ALTER TABLE `tawasulInternalAssessmentEntry` RENAME COLUMN `internal_assessment_column_id` TO `tawasulInternalAssessmentColumnID`;
ALTER TABLE `tawasulInternalAssessmentEntry` RENAME COLUMN `person_id_student` TO `tawasulPersonIDStudent`;
ALTER TABLE `tawasulInternalAssessmentEntry` RENAME COLUMN `person_id_last_edit` TO `tawasulPersonIDLastEdit`;
RENAME TABLE `tos_language` TO `tawasulLanguage`;
ALTER TABLE `tawasulLanguage` RENAME COLUMN `language_id` TO `tawasulLanguageID`;
RENAME TABLE `tos_library_item` TO `tawasulLibraryItem`;
ALTER TABLE `tawasulLibraryItem` RENAME COLUMN `library_item_id` TO `tawasulLibraryItemID`;
ALTER TABLE `tawasulLibraryItem` RENAME COLUMN `library_item_id_parent` TO `tawasulLibraryItemIDParent`;
ALTER TABLE `tawasulLibraryItem` RENAME COLUMN `library_type_id` TO `tawasulLibraryTypeID`;
ALTER TABLE `tawasulLibraryItem` RENAME COLUMN `space_id` TO `tawasulSpaceID`;
ALTER TABLE `tawasulLibraryItem` RENAME COLUMN `person_id_ownership` TO `tawasulPersonIDOwnership`;
ALTER TABLE `tawasulLibraryItem` RENAME COLUMN `department_id` TO `tawasulDepartmentID`;
ALTER TABLE `tawasulLibraryItem` RENAME COLUMN `school_year_id_replacement` TO `tawasulSchoolYearIDReplacement`;
ALTER TABLE `tawasulLibraryItem` RENAME COLUMN `person_id_status_responsible` TO `tawasulPersonIDStatusResponsible`;
ALTER TABLE `tawasulLibraryItem` RENAME COLUMN `person_id_status_recorder` TO `tawasulPersonIDStatusRecorder`;
ALTER TABLE `tawasulLibraryItem` RENAME COLUMN `person_id_return_action` TO `tawasulPersonIDReturnAction`;
ALTER TABLE `tawasulLibraryItem` RENAME COLUMN `person_id_creator` TO `tawasulPersonIDCreator`;
ALTER TABLE `tawasulLibraryItem` RENAME COLUMN `person_id_update` TO `tawasulPersonIDUpdate`;
RENAME TABLE `tos_library_item_event` TO `tawasulLibraryItemEvent`;
ALTER TABLE `tawasulLibraryItemEvent` RENAME COLUMN `library_item_event_id` TO `tawasulLibraryItemEventID`;
ALTER TABLE `tawasulLibraryItemEvent` RENAME COLUMN `library_item_id` TO `tawasulLibraryItemID`;
ALTER TABLE `tawasulLibraryItemEvent` RENAME COLUMN `person_id_status_responsible` TO `tawasulPersonIDStatusResponsible`;
ALTER TABLE `tawasulLibraryItemEvent` RENAME COLUMN `person_id_out` TO `tawasulPersonIDOut`;
ALTER TABLE `tawasulLibraryItemEvent` RENAME COLUMN `person_id_return_action` TO `tawasulPersonIDReturnAction`;
ALTER TABLE `tawasulLibraryItemEvent` RENAME COLUMN `person_id_in` TO `tawasulPersonIDIn`;
RENAME TABLE `tos_library_shelf` TO `tawasulLibraryShelf`;
ALTER TABLE `tawasulLibraryShelf` RENAME COLUMN `library_shelf_id` TO `tawasulLibraryShelfID`;
RENAME TABLE `tos_library_shelf_item` TO `tawasulLibraryShelfItem`;
ALTER TABLE `tawasulLibraryShelfItem` RENAME COLUMN `library_shelf_item_id` TO `tawasulLibraryShelfItemID`;
ALTER TABLE `tawasulLibraryShelfItem` RENAME COLUMN `library_item_id` TO `tawasulLibraryItemID`;
ALTER TABLE `tawasulLibraryShelfItem` RENAME COLUMN `library_shelf_id` TO `tawasulLibraryShelfID`;
RENAME TABLE `tos_library_type` TO `tawasulLibraryType`;
ALTER TABLE `tawasulLibraryType` RENAME COLUMN `library_type_id` TO `tawasulLibraryTypeID`;
RENAME TABLE `tos_log` TO `tawasulLog`;
ALTER TABLE `tawasulLog` RENAME COLUMN `log_id` TO `tawasulLogID`;
ALTER TABLE `tawasulLog` RENAME COLUMN `module_id` TO `tawasulModuleID`;
ALTER TABLE `tawasulLog` RENAME COLUMN `person_id` TO `tawasulPersonID`;
ALTER TABLE `tawasulLog` RENAME COLUMN `school_year_id` TO `tawasulSchoolYearID`;
RENAME TABLE `tos_markbook_column` TO `tawasulMarkbookColumn`;
ALTER TABLE `tawasulMarkbookColumn` RENAME COLUMN `markbook_column_id` TO `tawasulMarkbookColumnID`;
ALTER TABLE `tawasulMarkbookColumn` RENAME COLUMN `course_class_id` TO `tawasulCourseClassID`;
ALTER TABLE `tawasulMarkbookColumn` RENAME COLUMN `hook_id` TO `tawasulHookID`;
ALTER TABLE `tawasulMarkbookColumn` RENAME COLUMN `unit_id` TO `tawasulUnitID`;
ALTER TABLE `tawasulMarkbookColumn` RENAME COLUMN `planner_entry_id` TO `tawasulPlannerEntryID`;
ALTER TABLE `tawasulMarkbookColumn` RENAME COLUMN `school_year_term_id` TO `tawasulSchoolYearTermID`;
ALTER TABLE `tawasulMarkbookColumn` RENAME COLUMN `scale_id_attainment` TO `tawasulScaleIDAttainment`;
ALTER TABLE `tawasulMarkbookColumn` RENAME COLUMN `scale_id_effort` TO `tawasulScaleIDEffort`;
ALTER TABLE `tawasulMarkbookColumn` RENAME COLUMN `rubric_id_attainment` TO `tawasulRubricIDAttainment`;
ALTER TABLE `tawasulMarkbookColumn` RENAME COLUMN `rubric_id_effort` TO `tawasulRubricIDEffort`;
ALTER TABLE `tawasulMarkbookColumn` RENAME COLUMN `person_id_creator` TO `tawasulPersonIDCreator`;
ALTER TABLE `tawasulMarkbookColumn` RENAME COLUMN `person_id_last_edit` TO `tawasulPersonIDLastEdit`;
RENAME TABLE `tos_markbook_entry` TO `tawasulMarkbookEntry`;
ALTER TABLE `tawasulMarkbookEntry` RENAME COLUMN `markbook_entry_id` TO `tawasulMarkbookEntryID`;
ALTER TABLE `tawasulMarkbookEntry` RENAME COLUMN `markbook_column_id` TO `tawasulMarkbookColumnID`;
ALTER TABLE `tawasulMarkbookEntry` RENAME COLUMN `person_id_student` TO `tawasulPersonIDStudent`;
ALTER TABLE `tawasulMarkbookEntry` RENAME COLUMN `person_id_last_edit` TO `tawasulPersonIDLastEdit`;
RENAME TABLE `tos_markbook_target` TO `tawasulMarkbookTarget`;
ALTER TABLE `tawasulMarkbookTarget` RENAME COLUMN `markbook_target_id` TO `tawasulMarkbookTargetID`;
ALTER TABLE `tawasulMarkbookTarget` RENAME COLUMN `course_class_id` TO `tawasulCourseClassID`;
ALTER TABLE `tawasulMarkbookTarget` RENAME COLUMN `person_id_student` TO `tawasulPersonIDStudent`;
ALTER TABLE `tawasulMarkbookTarget` RENAME COLUMN `scale_grade_id` TO `tawasulScaleGradeID`;
RENAME TABLE `tos_markbook_weight` TO `tawasulMarkbookWeight`;
ALTER TABLE `tawasulMarkbookWeight` RENAME COLUMN `markbook_weight_id` TO `tawasulMarkbookWeightID`;
ALTER TABLE `tawasulMarkbookWeight` RENAME COLUMN `course_class_id` TO `tawasulCourseClassID`;
RENAME TABLE `tos_medical_condition` TO `tawasulMedicalCondition`;
ALTER TABLE `tawasulMedicalCondition` RENAME COLUMN `medical_condition_id` TO `tawasulMedicalConditionID`;
RENAME TABLE `tos_messenger` TO `tawasulMessenger`;
ALTER TABLE `tawasulMessenger` RENAME COLUMN `messenger_id` TO `tawasulMessengerID`;
ALTER TABLE `tawasulMessenger` RENAME COLUMN `school_year_id` TO `tawasulSchoolYearID`;
ALTER TABLE `tawasulMessenger` RENAME COLUMN `person_id` TO `tawasulPersonID`;
RENAME TABLE `tos_messenger_canned_response` TO `tawasulMessengerCannedResponse`;
ALTER TABLE `tawasulMessengerCannedResponse` RENAME COLUMN `messenger_canned_response_id` TO `tawasulMessengerCannedResponseID`;
ALTER TABLE `tawasulMessengerCannedResponse` RENAME COLUMN `person_id_creator` TO `tawasulPersonIDCreator`;
RENAME TABLE `tos_messenger_mailing_list` TO `tawasulMessengerMailingList`;
ALTER TABLE `tawasulMessengerMailingList` RENAME COLUMN `messenger_mailing_list_id` TO `tawasulMessengerMailingListID`;
RENAME TABLE `tos_messenger_mailing_list_recipient` TO `tawasulMessengerMailingListRecipient`;
ALTER TABLE `tawasulMessengerMailingListRecipient` RENAME COLUMN `messenger_mailing_list_recipient_id` TO `tawasulMessengerMailingListRecipientID`;
ALTER TABLE `tawasulMessengerMailingListRecipient` RENAME COLUMN `messenger_mailing_list_id_list` TO `tawasulMessengerMailingListIDList`;
RENAME TABLE `tos_messenger_receipt` TO `tawasulMessengerReceipt`;
ALTER TABLE `tawasulMessengerReceipt` RENAME COLUMN `messenger_receipt_id` TO `tawasulMessengerReceiptID`;
ALTER TABLE `tawasulMessengerReceipt` RENAME COLUMN `messenger_id` TO `tawasulMessengerID`;
ALTER TABLE `tawasulMessengerReceipt` RENAME COLUMN `person_id` TO `tawasulPersonID`;
ALTER TABLE `tawasulMessengerReceipt` RENAME COLUMN `person_id_list_student` TO `tawasulPersonIDListStudent`;
RENAME TABLE `tos_messenger_target` TO `tawasulMessengerTarget`;
ALTER TABLE `tawasulMessengerTarget` RENAME COLUMN `messenger_target_id` TO `tawasulMessengerTargetID`;
ALTER TABLE `tawasulMessengerTarget` RENAME COLUMN `messenger_id` TO `tawasulMessengerID`;
RENAME TABLE `tos_migration` TO `tawasulMigration`;
ALTER TABLE `tawasulMigration` RENAME COLUMN `migration_id` TO `tawasulMigrationID`;
RENAME TABLE `tos_module` TO `tawasulModule`;
ALTER TABLE `tawasulModule` RENAME COLUMN `module_id` TO `tawasulModuleID`;
RENAME TABLE `tos_notification` TO `tawasulNotification`;
ALTER TABLE `tawasulNotification` RENAME COLUMN `notification_id` TO `tawasulNotificationID`;
ALTER TABLE `tawasulNotification` RENAME COLUMN `person_id` TO `tawasulPersonID`;
ALTER TABLE `tawasulNotification` RENAME COLUMN `module_id` TO `tawasulModuleID`;
RENAME TABLE `tos_notification_event` TO `tawasulNotificationEvent`;
ALTER TABLE `tawasulNotificationEvent` RENAME COLUMN `notification_event_id` TO `tawasulNotificationEventID`;
RENAME TABLE `tos_notification_listener` TO `tawasulNotificationListener`;
ALTER TABLE `tawasulNotificationListener` RENAME COLUMN `notification_listener_id` TO `tawasulNotificationListenerID`;
ALTER TABLE `tawasulNotificationListener` RENAME COLUMN `notification_event_id` TO `tawasulNotificationEventID`;
ALTER TABLE `tawasulNotificationListener` RENAME COLUMN `person_id` TO `tawasulPersonID`;
RENAME TABLE `tos_outcome` TO `tawasulOutcome`;
ALTER TABLE `tawasulOutcome` RENAME COLUMN `outcome_id` TO `tawasulOutcomeID`;
ALTER TABLE `tawasulOutcome` RENAME COLUMN `department_id` TO `tawasulDepartmentID`;
ALTER TABLE `tawasulOutcome` RENAME COLUMN `year_group_id_list` TO `tawasulYearGroupIDList`;
ALTER TABLE `tawasulOutcome` RENAME COLUMN `person_id_creator` TO `tawasulPersonIDCreator`;
RENAME TABLE `tos_payment` TO `tawasulPayment`;
ALTER TABLE `tawasulPayment` RENAME COLUMN `payment_id` TO `tawasulPaymentID`;
ALTER TABLE `tawasulPayment` RENAME COLUMN `person_id` TO `tawasulPersonID`;
RENAME TABLE `tos_permission` TO `tawasulPermission`;
ALTER TABLE `tawasulPermission` RENAME COLUMN `role_id` TO `tawasulRoleID`;
ALTER TABLE `tawasulPermission` RENAME COLUMN `action_id` TO `tawasulActionID`;
RENAME TABLE `tos_person` TO `tawasulPerson`;
ALTER TABLE `tawasulPerson` RENAME COLUMN `person_id` TO `tawasulPersonID`;
ALTER TABLE `tawasulPerson` RENAME COLUMN `role_id_primary` TO `tawasulRoleIDPrimary`;
ALTER TABLE `tawasulPerson` RENAME COLUMN `role_id_all` TO `tawasulRoleIDAll`;
ALTER TABLE `tawasulPerson` RENAME COLUMN `house_id` TO `tawasulHouseID`;
ALTER TABLE `tawasulPerson` RENAME COLUMN `school_year_id_class_of` TO `tawasulSchoolYearIDClassOf`;
ALTER TABLE `tawasulPerson` RENAME COLUMN `application_form_id` TO `tawasulApplicationFormID`;
ALTER TABLE `tawasulPerson` RENAME COLUMN `theme_id_personal` TO `tawasulThemeIDPersonal`;
ALTER TABLE `tawasulPerson` RENAME COLUMN `i18n_id_personal` TO `tawasuli18nIDPersonal`;
RENAME TABLE `tos_personal_document` TO `tawasulPersonalDocument`;
ALTER TABLE `tawasulPersonalDocument` RENAME COLUMN `personal_document_id` TO `tawasulPersonalDocumentID`;
ALTER TABLE `tawasulPersonalDocument` RENAME COLUMN `personal_document_type_id` TO `tawasulPersonalDocumentTypeID`;
ALTER TABLE `tawasulPersonalDocument` RENAME COLUMN `person_id_updater` TO `tawasulPersonIDUpdater`;
RENAME TABLE `tos_personal_document_type` TO `tawasulPersonalDocumentType`;
ALTER TABLE `tawasulPersonalDocumentType` RENAME COLUMN `personal_document_type_id` TO `tawasulPersonalDocumentTypeID`;
RENAME TABLE `tos_person_medical` TO `tawasulPersonMedical`;
ALTER TABLE `tawasulPersonMedical` RENAME COLUMN `person_medical_id` TO `tawasulPersonMedicalID`;
ALTER TABLE `tawasulPersonMedical` RENAME COLUMN `person_id` TO `tawasulPersonID`;
RENAME TABLE `tos_person_medical_condition` TO `tawasulPersonMedicalCondition`;
ALTER TABLE `tawasulPersonMedicalCondition` RENAME COLUMN `person_medical_condition_id` TO `tawasulPersonMedicalConditionID`;
ALTER TABLE `tawasulPersonMedicalCondition` RENAME COLUMN `person_medical_id` TO `tawasulPersonMedicalID`;
ALTER TABLE `tawasulPersonMedicalCondition` RENAME COLUMN `alert_level_id` TO `tawasulAlertLevelID`;
RENAME TABLE `tos_person_medical_condition_update` TO `tawasulPersonMedicalConditionUpdate`;
ALTER TABLE `tawasulPersonMedicalConditionUpdate` RENAME COLUMN `person_medical_condition_update_id` TO `tawasulPersonMedicalConditionUpdateID`;
ALTER TABLE `tawasulPersonMedicalConditionUpdate` RENAME COLUMN `person_medical_update_id` TO `tawasulPersonMedicalUpdateID`;
ALTER TABLE `tawasulPersonMedicalConditionUpdate` RENAME COLUMN `person_medical_condition_id` TO `tawasulPersonMedicalConditionID`;
ALTER TABLE `tawasulPersonMedicalConditionUpdate` RENAME COLUMN `person_medical_id` TO `tawasulPersonMedicalID`;
ALTER TABLE `tawasulPersonMedicalConditionUpdate` RENAME COLUMN `alert_level_id` TO `tawasulAlertLevelID`;
ALTER TABLE `tawasulPersonMedicalConditionUpdate` RENAME COLUMN `person_id_updater` TO `tawasulPersonIDUpdater`;
RENAME TABLE `tos_person_medical_update` TO `tawasulPersonMedicalUpdate`;
ALTER TABLE `tawasulPersonMedicalUpdate` RENAME COLUMN `person_medical_update_id` TO `tawasulPersonMedicalUpdateID`;
ALTER TABLE `tawasulPersonMedicalUpdate` RENAME COLUMN `school_year_id` TO `tawasulSchoolYearID`;
ALTER TABLE `tawasulPersonMedicalUpdate` RENAME COLUMN `person_medical_id` TO `tawasulPersonMedicalID`;
ALTER TABLE `tawasulPersonMedicalUpdate` RENAME COLUMN `person_id` TO `tawasulPersonID`;
ALTER TABLE `tawasulPersonMedicalUpdate` RENAME COLUMN `person_id_updater` TO `tawasulPersonIDUpdater`;
RENAME TABLE `tos_person_photo` TO `tawasulPersonPhoto`;
ALTER TABLE `tawasulPersonPhoto` RENAME COLUMN `person_photo_id` TO `tawasulPersonPhotoID`;
ALTER TABLE `tawasulPersonPhoto` RENAME COLUMN `school_year_id` TO `tawasulSchoolYearID`;
ALTER TABLE `tawasulPersonPhoto` RENAME COLUMN `person_id` TO `tawasulPersonID`;
ALTER TABLE `tawasulPersonPhoto` RENAME COLUMN `person_id_created` TO `tawasulPersonIDCreated`;
RENAME TABLE `tos_person_reset` TO `tawasulPersonReset`;
ALTER TABLE `tawasulPersonReset` RENAME COLUMN `person_reset_id` TO `tawasulPersonResetID`;
ALTER TABLE `tawasulPersonReset` RENAME COLUMN `person_id` TO `tawasulPersonID`;
RENAME TABLE `tos_person_status_log` TO `tawasulPersonStatusLog`;
ALTER TABLE `tawasulPersonStatusLog` RENAME COLUMN `person_status_log_id` TO `tawasulPersonStatusLogID`;
ALTER TABLE `tawasulPersonStatusLog` RENAME COLUMN `person_id` TO `tawasulPersonID`;
ALTER TABLE `tawasulPersonStatusLog` RENAME COLUMN `person_id_modified` TO `tawasulPersonIDModified`;
RENAME TABLE `tos_person_update` TO `tawasulPersonUpdate`;
ALTER TABLE `tawasulPersonUpdate` RENAME COLUMN `person_update_id` TO `tawasulPersonUpdateID`;
ALTER TABLE `tawasulPersonUpdate` RENAME COLUMN `school_year_id` TO `tawasulSchoolYearID`;
ALTER TABLE `tawasulPersonUpdate` RENAME COLUMN `person_id` TO `tawasulPersonID`;
ALTER TABLE `tawasulPersonUpdate` RENAME COLUMN `person_id_updater` TO `tawasulPersonIDUpdater`;
RENAME TABLE `tos_planner_entry` TO `tawasulPlannerEntry`;
ALTER TABLE `tawasulPlannerEntry` RENAME COLUMN `planner_entry_id` TO `tawasulPlannerEntryID`;
ALTER TABLE `tawasulPlannerEntry` RENAME COLUMN `course_class_id` TO `tawasulCourseClassID`;
ALTER TABLE `tawasulPlannerEntry` RENAME COLUMN `unit_id` TO `tawasulUnitID`;
ALTER TABLE `tawasulPlannerEntry` RENAME COLUMN `person_id_creator` TO `tawasulPersonIDCreator`;
ALTER TABLE `tawasulPlannerEntry` RENAME COLUMN `person_id_last_edit` TO `tawasulPersonIDLastEdit`;
RENAME TABLE `tos_planner_entry_discuss` TO `tawasulPlannerEntryDiscuss`;
ALTER TABLE `tawasulPlannerEntryDiscuss` RENAME COLUMN `planner_entry_discuss_id` TO `tawasulPlannerEntryDiscussID`;
ALTER TABLE `tawasulPlannerEntryDiscuss` RENAME COLUMN `planner_entry_id` TO `tawasulPlannerEntryID`;
ALTER TABLE `tawasulPlannerEntryDiscuss` RENAME COLUMN `person_id` TO `tawasulPersonID`;
ALTER TABLE `tawasulPlannerEntryDiscuss` RENAME COLUMN `planner_entry_discuss_id_reply_to` TO `tawasulPlannerEntryDiscussIDReplyTo`;
RENAME TABLE `tos_planner_entry_guest` TO `tawasulPlannerEntryGuest`;
ALTER TABLE `tawasulPlannerEntryGuest` RENAME COLUMN `planner_entry_guest_id` TO `tawasulPlannerEntryGuestID`;
ALTER TABLE `tawasulPlannerEntryGuest` RENAME COLUMN `planner_entry_id` TO `tawasulPlannerEntryID`;
ALTER TABLE `tawasulPlannerEntryGuest` RENAME COLUMN `person_id` TO `tawasulPersonID`;
RENAME TABLE `tos_planner_entry_homework` TO `tawasulPlannerEntryHomework`;
ALTER TABLE `tawasulPlannerEntryHomework` RENAME COLUMN `planner_entry_homework_id` TO `tawasulPlannerEntryHomeworkID`;
ALTER TABLE `tawasulPlannerEntryHomework` RENAME COLUMN `planner_entry_id` TO `tawasulPlannerEntryID`;
ALTER TABLE `tawasulPlannerEntryHomework` RENAME COLUMN `person_id` TO `tawasulPersonID`;
RENAME TABLE `tos_planner_entry_outcome` TO `tawasulPlannerEntryOutcome`;
ALTER TABLE `tawasulPlannerEntryOutcome` RENAME COLUMN `planner_entry_outcome_id` TO `tawasulPlannerEntryOutcomeID`;
ALTER TABLE `tawasulPlannerEntryOutcome` RENAME COLUMN `planner_entry_id` TO `tawasulPlannerEntryID`;
ALTER TABLE `tawasulPlannerEntryOutcome` RENAME COLUMN `outcome_id` TO `tawasulOutcomeID`;
RENAME TABLE `tos_planner_entry_student_homework` TO `tawasulPlannerEntryStudentHomework`;
ALTER TABLE `tawasulPlannerEntryStudentHomework` RENAME COLUMN `planner_entry_student_homework_id` TO `tawasulPlannerEntryStudentHomeworkID`;
ALTER TABLE `tawasulPlannerEntryStudentHomework` RENAME COLUMN `planner_entry_id` TO `tawasulPlannerEntryID`;
ALTER TABLE `tawasulPlannerEntryStudentHomework` RENAME COLUMN `person_id` TO `tawasulPersonID`;
RENAME TABLE `tos_planner_entry_student_tracker` TO `tawasulPlannerEntryStudentTracker`;
ALTER TABLE `tawasulPlannerEntryStudentTracker` RENAME COLUMN `planner_entry_student_tracker_id` TO `tawasulPlannerEntryStudentTrackerID`;
ALTER TABLE `tawasulPlannerEntryStudentTracker` RENAME COLUMN `planner_entry_id` TO `tawasulPlannerEntryID`;
ALTER TABLE `tawasulPlannerEntryStudentTracker` RENAME COLUMN `person_id` TO `tawasulPersonID`;
RENAME TABLE `tos_planner_parent_weekly_email_summary` TO `tawasulPlannerParentWeeklyEmailSummary`;
ALTER TABLE `tawasulPlannerParentWeeklyEmailSummary` RENAME COLUMN `planner_parent_weekly_email_summary_id` TO `tawasulPlannerParentWeeklyEmailSummaryID`;
ALTER TABLE `tawasulPlannerParentWeeklyEmailSummary` RENAME COLUMN `school_year_id` TO `tawasulSchoolYearID`;
ALTER TABLE `tawasulPlannerParentWeeklyEmailSummary` RENAME COLUMN `person_id_parent` TO `tawasulPersonIDParent`;
ALTER TABLE `tawasulPlannerParentWeeklyEmailSummary` RENAME COLUMN `person_id_student` TO `tawasulPersonIDStudent`;
RENAME TABLE `tos_report` TO `tawasulReport`;
ALTER TABLE `tawasulReport` RENAME COLUMN `report_id` TO `tawasulReportID`;
ALTER TABLE `tawasulReport` RENAME COLUMN `report_archive_id` TO `tawasulReportArchiveID`;
ALTER TABLE `tawasulReport` RENAME COLUMN `report_template_id` TO `tawasulReportTemplateID`;
ALTER TABLE `tawasulReport` RENAME COLUMN `school_year_id` TO `tawasulSchoolYearID`;
ALTER TABLE `tawasulReport` RENAME COLUMN `reporting_cycle_id` TO `tawasulReportingCycleID`;
ALTER TABLE `tawasulReport` RENAME COLUMN `year_group_id_list` TO `tawasulYearGroupIDList`;
RENAME TABLE `tos_report_archive` TO `tawasulReportArchive`;
ALTER TABLE `tawasulReportArchive` RENAME COLUMN `report_archive_id` TO `tawasulReportArchiveID`;
RENAME TABLE `tos_report_archive_entry` TO `tawasulReportArchiveEntry`;
ALTER TABLE `tawasulReportArchiveEntry` RENAME COLUMN `report_archive_entry_id` TO `tawasulReportArchiveEntryID`;
ALTER TABLE `tawasulReportArchiveEntry` RENAME COLUMN `report_archive_id` TO `tawasulReportArchiveID`;
ALTER TABLE `tawasulReportArchiveEntry` RENAME COLUMN `report_id` TO `tawasulReportID`;
ALTER TABLE `tawasulReportArchiveEntry` RENAME COLUMN `school_year_id` TO `tawasulSchoolYearID`;
ALTER TABLE `tawasulReportArchiveEntry` RENAME COLUMN `year_group_id` TO `tawasulYearGroupID`;
ALTER TABLE `tawasulReportArchiveEntry` RENAME COLUMN `form_group_id` TO `tawasulFormGroupID`;
ALTER TABLE `tawasulReportArchiveEntry` RENAME COLUMN `person_id` TO `tawasulPersonID`;
ALTER TABLE `tawasulReportArchiveEntry` RENAME COLUMN `person_id_accessed` TO `tawasulPersonIDAccessed`;
RENAME TABLE `tos_reporting_access` TO `tawasulReportingAccess`;
ALTER TABLE `tawasulReportingAccess` RENAME COLUMN `reporting_access_id` TO `tawasulReportingAccessID`;
ALTER TABLE `tawasulReportingAccess` RENAME COLUMN `reporting_cycle_id` TO `tawasulReportingCycleID`;
ALTER TABLE `tawasulReportingAccess` RENAME COLUMN `reporting_scope_id_list` TO `tawasulReportingScopeIDList`;
ALTER TABLE `tawasulReportingAccess` RENAME COLUMN `role_id_list` TO `tawasulRoleIDList`;
ALTER TABLE `tawasulReportingAccess` RENAME COLUMN `person_id_list` TO `tawasulPersonIDList`;
RENAME TABLE `tos_reporting_criteria` TO `tawasulReportingCriteria`;
ALTER TABLE `tawasulReportingCriteria` RENAME COLUMN `reporting_criteria_id` TO `tawasulReportingCriteriaID`;
ALTER TABLE `tawasulReportingCriteria` RENAME COLUMN `reporting_cycle_id` TO `tawasulReportingCycleID`;
ALTER TABLE `tawasulReportingCriteria` RENAME COLUMN `reporting_scope_id` TO `tawasulReportingScopeID`;
ALTER TABLE `tawasulReportingCriteria` RENAME COLUMN `reporting_criteria_type_id` TO `tawasulReportingCriteriaTypeID`;
ALTER TABLE `tawasulReportingCriteria` RENAME COLUMN `year_group_id` TO `tawasulYearGroupID`;
ALTER TABLE `tawasulReportingCriteria` RENAME COLUMN `form_group_id` TO `tawasulFormGroupID`;
ALTER TABLE `tawasulReportingCriteria` RENAME COLUMN `course_id` TO `tawasulCourseID`;
ALTER TABLE `tawasulReportingCriteria` RENAME COLUMN `scale_id` TO `tawasulScaleID`;
RENAME TABLE `tos_reporting_criteria_type` TO `tawasulReportingCriteriaType`;
ALTER TABLE `tawasulReportingCriteriaType` RENAME COLUMN `reporting_criteria_type_id` TO `tawasulReportingCriteriaTypeID`;
ALTER TABLE `tawasulReportingCriteriaType` RENAME COLUMN `scale_id` TO `tawasulScaleID`;
RENAME TABLE `tos_reporting_cycle` TO `tawasulReportingCycle`;
ALTER TABLE `tawasulReportingCycle` RENAME COLUMN `reporting_cycle_id` TO `tawasulReportingCycleID`;
ALTER TABLE `tawasulReportingCycle` RENAME COLUMN `school_year_id` TO `tawasulSchoolYearID`;
ALTER TABLE `tawasulReportingCycle` RENAME COLUMN `year_group_id_list` TO `tawasulYearGroupIDList`;
RENAME TABLE `tos_reporting_progress` TO `tawasulReportingProgress`;
ALTER TABLE `tawasulReportingProgress` RENAME COLUMN `reporting_progress_id` TO `tawasulReportingProgressID`;
ALTER TABLE `tawasulReportingProgress` RENAME COLUMN `reporting_scope_id` TO `tawasulReportingScopeID`;
ALTER TABLE `tawasulReportingProgress` RENAME COLUMN `year_group_id` TO `tawasulYearGroupID`;
ALTER TABLE `tawasulReportingProgress` RENAME COLUMN `form_group_id` TO `tawasulFormGroupID`;
ALTER TABLE `tawasulReportingProgress` RENAME COLUMN `course_class_id` TO `tawasulCourseClassID`;
ALTER TABLE `tawasulReportingProgress` RENAME COLUMN `person_id_student` TO `tawasulPersonIDStudent`;
RENAME TABLE `tos_reporting_proof` TO `tawasulReportingProof`;
ALTER TABLE `tawasulReportingProof` RENAME COLUMN `reporting_proof_id` TO `tawasulReportingProofID`;
ALTER TABLE `tawasulReportingProof` RENAME COLUMN `reporting_value_id` TO `tawasulReportingValueID`;
ALTER TABLE `tawasulReportingProof` RENAME COLUMN `person_id_proofed` TO `tawasulPersonIDProofed`;
ALTER TABLE `tawasulReportingProof` RENAME COLUMN `person_id_actioned` TO `tawasulPersonIDActioned`;
RENAME TABLE `tos_reporting_scope` TO `tawasulReportingScope`;
ALTER TABLE `tawasulReportingScope` RENAME COLUMN `reporting_scope_id` TO `tawasulReportingScopeID`;
ALTER TABLE `tawasulReportingScope` RENAME COLUMN `reporting_cycle_id` TO `tawasulReportingCycleID`;
RENAME TABLE `tos_reporting_value` TO `tawasulReportingValue`;
ALTER TABLE `tawasulReportingValue` RENAME COLUMN `reporting_value_id` TO `tawasulReportingValueID`;
ALTER TABLE `tawasulReportingValue` RENAME COLUMN `reporting_cycle_id` TO `tawasulReportingCycleID`;
ALTER TABLE `tawasulReportingValue` RENAME COLUMN `reporting_criteria_id` TO `tawasulReportingCriteriaID`;
ALTER TABLE `tawasulReportingValue` RENAME COLUMN `school_year_id` TO `tawasulSchoolYearID`;
ALTER TABLE `tawasulReportingValue` RENAME COLUMN `course_class_id` TO `tawasulCourseClassID`;
ALTER TABLE `tawasulReportingValue` RENAME COLUMN `person_id_student` TO `tawasulPersonIDStudent`;
ALTER TABLE `tawasulReportingValue` RENAME COLUMN `scale_grade_id` TO `tawasulScaleGradeID`;
ALTER TABLE `tawasulReportingValue` RENAME COLUMN `person_id_created` TO `tawasulPersonIDCreated`;
ALTER TABLE `tawasulReportingValue` RENAME COLUMN `person_id_modified` TO `tawasulPersonIDModified`;
RENAME TABLE `tos_report_prototype_section` TO `tawasulReportPrototypeSection`;
ALTER TABLE `tawasulReportPrototypeSection` RENAME COLUMN `report_prototype_section_id` TO `tawasulReportPrototypeSectionID`;
ALTER TABLE `tawasulReportPrototypeSection` RENAME COLUMN `person_id_last_edit` TO `tawasulPersonIDLastEdit`;
RENAME TABLE `tos_report_template` TO `tawasulReportTemplate`;
ALTER TABLE `tawasulReportTemplate` RENAME COLUMN `report_template_id` TO `tawasulReportTemplateID`;
RENAME TABLE `tos_report_template_font` TO `tawasulReportTemplateFont`;
ALTER TABLE `tawasulReportTemplateFont` RENAME COLUMN `report_template_font_id` TO `tawasulReportTemplateFontID`;
RENAME TABLE `tos_report_template_section` TO `tawasulReportTemplateSection`;
ALTER TABLE `tawasulReportTemplateSection` RENAME COLUMN `report_template_section_id` TO `tawasulReportTemplateSectionID`;
ALTER TABLE `tawasulReportTemplateSection` RENAME COLUMN `report_template_id` TO `tawasulReportTemplateID`;
ALTER TABLE `tawasulReportTemplateSection` RENAME COLUMN `report_prototype_section_id` TO `tawasulReportPrototypeSectionID`;
RENAME TABLE `tos_resource` TO `tawasulResource`;
ALTER TABLE `tawasulResource` RENAME COLUMN `resource_id` TO `tawasulResourceID`;
ALTER TABLE `tawasulResource` RENAME COLUMN `year_group_id_list` TO `tawasulYearGroupIDList`;
ALTER TABLE `tawasulResource` RENAME COLUMN `person_id` TO `tawasulPersonID`;
RENAME TABLE `tos_resource_tag` TO `tawasulResourceTag`;
ALTER TABLE `tawasulResourceTag` RENAME COLUMN `resource_tag_id` TO `tawasulResourceTagID`;
RENAME TABLE `tos_role` TO `tawasulRole`;
ALTER TABLE `tawasulRole` RENAME COLUMN `role_id` TO `tawasulRoleID`;
RENAME TABLE `tos_rubric` TO `tawasulRubric`;
ALTER TABLE `tawasulRubric` RENAME COLUMN `rubric_id` TO `tawasulRubricID`;
ALTER TABLE `tawasulRubric` RENAME COLUMN `department_id` TO `tawasulDepartmentID`;
ALTER TABLE `tawasulRubric` RENAME COLUMN `year_group_id_list` TO `tawasulYearGroupIDList`;
ALTER TABLE `tawasulRubric` RENAME COLUMN `scale_id` TO `tawasulScaleID`;
ALTER TABLE `tawasulRubric` RENAME COLUMN `person_id_creator` TO `tawasulPersonIDCreator`;
RENAME TABLE `tos_rubric_cell` TO `tawasulRubricCell`;
ALTER TABLE `tawasulRubricCell` RENAME COLUMN `rubric_cell_id` TO `tawasulRubricCellID`;
ALTER TABLE `tawasulRubricCell` RENAME COLUMN `rubric_id` TO `tawasulRubricID`;
ALTER TABLE `tawasulRubricCell` RENAME COLUMN `rubric_column_id` TO `tawasulRubricColumnID`;
ALTER TABLE `tawasulRubricCell` RENAME COLUMN `rubric_row_id` TO `tawasulRubricRowID`;
RENAME TABLE `tos_rubric_column` TO `tawasulRubricColumn`;
ALTER TABLE `tawasulRubricColumn` RENAME COLUMN `rubric_column_id` TO `tawasulRubricColumnID`;
ALTER TABLE `tawasulRubricColumn` RENAME COLUMN `rubric_id` TO `tawasulRubricID`;
ALTER TABLE `tawasulRubricColumn` RENAME COLUMN `scale_grade_id` TO `tawasulScaleGradeID`;
RENAME TABLE `tos_rubric_entry` TO `tawasulRubricEntry`;
ALTER TABLE `tawasulRubricEntry` RENAME COLUMN `tos_rubric_entry` TO `tawasulRubricEntry`;
ALTER TABLE `tawasulRubricEntry` RENAME COLUMN `rubric_id` TO `tawasulRubricID`;
ALTER TABLE `tawasulRubricEntry` RENAME COLUMN `person_id` TO `tawasulPersonID`;
ALTER TABLE `tawasulRubricEntry` RENAME COLUMN `rubric_cell_id` TO `tawasulRubricCellID`;
RENAME TABLE `tos_rubric_row` TO `tawasulRubricRow`;
ALTER TABLE `tawasulRubricRow` RENAME COLUMN `rubric_row_id` TO `tawasulRubricRowID`;
ALTER TABLE `tawasulRubricRow` RENAME COLUMN `rubric_id` TO `tawasulRubricID`;
ALTER TABLE `tawasulRubricRow` RENAME COLUMN `outcome_id` TO `tawasulOutcomeID`;
RENAME TABLE `tos_scale` TO `tawasulScale`;
ALTER TABLE `tawasulScale` RENAME COLUMN `scale_id` TO `tawasulScaleID`;
RENAME TABLE `tos_scale_grade` TO `tawasulScaleGrade`;
ALTER TABLE `tawasulScaleGrade` RENAME COLUMN `scale_grade_id` TO `tawasulScaleGradeID`;
ALTER TABLE `tawasulScaleGrade` RENAME COLUMN `scale_id` TO `tawasulScaleID`;
RENAME TABLE `tos_school_year` TO `tawasulSchoolYear`;
ALTER TABLE `tawasulSchoolYear` RENAME COLUMN `school_year_id` TO `tawasulSchoolYearID`;
RENAME TABLE `tos_school_year_special_day` TO `tawasulSchoolYearSpecialDay`;
ALTER TABLE `tawasulSchoolYearSpecialDay` RENAME COLUMN `school_year_special_day_id` TO `tawasulSchoolYearSpecialDayID`;
ALTER TABLE `tawasulSchoolYearSpecialDay` RENAME COLUMN `school_year_term_id` TO `tawasulSchoolYearTermID`;
ALTER TABLE `tawasulSchoolYearSpecialDay` RENAME COLUMN `year_group_id_list` TO `tawasulYearGroupIDList`;
ALTER TABLE `tawasulSchoolYearSpecialDay` RENAME COLUMN `form_group_id_list` TO `tawasulFormGroupIDList`;
RENAME TABLE `tos_school_year_term` TO `tawasulSchoolYearTerm`;
ALTER TABLE `tawasulSchoolYearTerm` RENAME COLUMN `school_year_term_id` TO `tawasulSchoolYearTermID`;
ALTER TABLE `tawasulSchoolYearTerm` RENAME COLUMN `school_year_id` TO `tawasulSchoolYearID`;
RENAME TABLE `tos_session` TO `tawasulSession`;
ALTER TABLE `tawasulSession` RENAME COLUMN `session_id` TO `tawasulSessionID`;
ALTER TABLE `tawasulSession` RENAME COLUMN `person_id` TO `tawasulPersonID`;
ALTER TABLE `tawasulSession` RENAME COLUMN `action_id` TO `tawasulActionID`;
RENAME TABLE `tos_setting` TO `tawasulSetting`;
ALTER TABLE `tawasulSetting` RENAME COLUMN `setting_id` TO `tawasulSettingID`;
RENAME TABLE `tos_space` TO `tawasulSpace`;
ALTER TABLE `tawasulSpace` RENAME COLUMN `space_id` TO `tawasulSpaceID`;
RENAME TABLE `tos_space_person` TO `tawasulSpacePerson`;
ALTER TABLE `tawasulSpacePerson` RENAME COLUMN `space_person_id` TO `tawasulSpacePersonID`;
ALTER TABLE `tawasulSpacePerson` RENAME COLUMN `space_id` TO `tawasulSpaceID`;
ALTER TABLE `tawasulSpacePerson` RENAME COLUMN `person_id` TO `tawasulPersonID`;
RENAME TABLE `tos_staff` TO `tawasulStaff`;
ALTER TABLE `tawasulStaff` RENAME COLUMN `staff_id` TO `tawasulStaffID`;
ALTER TABLE `tawasulStaff` RENAME COLUMN `person_id` TO `tawasulPersonID`;
RENAME TABLE `tos_staff_absence` TO `tawasulStaffAbsence`;
ALTER TABLE `tawasulStaffAbsence` RENAME COLUMN `staff_absence_id` TO `tawasulStaffAbsenceID`;
ALTER TABLE `tawasulStaffAbsence` RENAME COLUMN `staff_absence_type_id` TO `tawasulStaffAbsenceTypeID`;
ALTER TABLE `tawasulStaffAbsence` RENAME COLUMN `school_year_id` TO `tawasulSchoolYearID`;
ALTER TABLE `tawasulStaffAbsence` RENAME COLUMN `person_id` TO `tawasulPersonID`;
ALTER TABLE `tawasulStaffAbsence` RENAME COLUMN `person_id_approval` TO `tawasulPersonIDApproval`;
ALTER TABLE `tawasulStaffAbsence` RENAME COLUMN `person_id_creator` TO `tawasulPersonIDCreator`;
ALTER TABLE `tawasulStaffAbsence` RENAME COLUMN `group_id` TO `tawasulGroupID`;
RENAME TABLE `tos_staff_absence_date` TO `tawasulStaffAbsenceDate`;
ALTER TABLE `tawasulStaffAbsenceDate` RENAME COLUMN `staff_absence_date_id` TO `tawasulStaffAbsenceDateID`;
ALTER TABLE `tawasulStaffAbsenceDate` RENAME COLUMN `staff_absence_id` TO `tawasulStaffAbsenceID`;
RENAME TABLE `tos_staff_absence_type` TO `tawasulStaffAbsenceType`;
ALTER TABLE `tawasulStaffAbsenceType` RENAME COLUMN `staff_absence_type_id` TO `tawasulStaffAbsenceTypeID`;
RENAME TABLE `tos_staff_application_form` TO `tawasulStaffApplicationForm`;
ALTER TABLE `tawasulStaffApplicationForm` RENAME COLUMN `staff_application_form_id` TO `tawasulStaffApplicationFormID`;
ALTER TABLE `tawasulStaffApplicationForm` RENAME COLUMN `staff_job_opening_id` TO `tawasulStaffJobOpeningID`;
ALTER TABLE `tawasulStaffApplicationForm` RENAME COLUMN `person_id` TO `tawasulPersonID`;
RENAME TABLE `tos_staff_application_form_file` TO `tawasulStaffApplicationFormFile`;
ALTER TABLE `tawasulStaffApplicationFormFile` RENAME COLUMN `staff_application_form_file_id` TO `tawasulStaffApplicationFormFileID`;
ALTER TABLE `tawasulStaffApplicationFormFile` RENAME COLUMN `staff_application_form_id` TO `tawasulStaffApplicationFormID`;
RENAME TABLE `tos_staff_contract` TO `tawasulStaffContract`;
ALTER TABLE `tawasulStaffContract` RENAME COLUMN `staff_contract_id` TO `tawasulStaffContractID`;
ALTER TABLE `tawasulStaffContract` RENAME COLUMN `staff_id` TO `tawasulStaffID`;
ALTER TABLE `tawasulStaffContract` RENAME COLUMN `person_id_creator` TO `tawasulPersonIDCreator`;
RENAME TABLE `tos_staff_coverage` TO `tawasulStaffCoverage`;
ALTER TABLE `tawasulStaffCoverage` RENAME COLUMN `staff_coverage_id` TO `tawasulStaffCoverageID`;
ALTER TABLE `tawasulStaffCoverage` RENAME COLUMN `staff_absence_id` TO `tawasulStaffAbsenceID`;
ALTER TABLE `tawasulStaffCoverage` RENAME COLUMN `school_year_id` TO `tawasulSchoolYearID`;
ALTER TABLE `tawasulStaffCoverage` RENAME COLUMN `person_id` TO `tawasulPersonID`;
ALTER TABLE `tawasulStaffCoverage` RENAME COLUMN `person_id_status` TO `tawasulPersonIDStatus`;
ALTER TABLE `tawasulStaffCoverage` RENAME COLUMN `person_id_coverage` TO `tawasulPersonIDCoverage`;
RENAME TABLE `tos_staff_coverage_date` TO `tawasulStaffCoverageDate`;
ALTER TABLE `tawasulStaffCoverageDate` RENAME COLUMN `staff_coverage_date_id` TO `tawasulStaffCoverageDateID`;
ALTER TABLE `tawasulStaffCoverageDate` RENAME COLUMN `staff_coverage_id` TO `tawasulStaffCoverageID`;
ALTER TABLE `tawasulStaffCoverageDate` RENAME COLUMN `staff_absence_date_id` TO `tawasulStaffAbsenceDateID`;
ALTER TABLE `tawasulStaffCoverageDate` RENAME COLUMN `person_id_unavailable` TO `tawasulPersonIDUnavailable`;
RENAME TABLE `tos_staff_duty` TO `tawasulStaffDuty`;
ALTER TABLE `tawasulStaffDuty` RENAME COLUMN `staff_duty_id` TO `tawasulStaffDutyID`;
ALTER TABLE `tawasulStaffDuty` RENAME COLUMN `days_of_week_id_list` TO `tawasulDaysOfWeekIDList`;
RENAME TABLE `tos_staff_duty_person` TO `tawasulStaffDutyPerson`;
ALTER TABLE `tawasulStaffDutyPerson` RENAME COLUMN `staff_duty_person_id` TO `tawasulStaffDutyPersonID`;
ALTER TABLE `tawasulStaffDutyPerson` RENAME COLUMN `staff_duty_id` TO `tawasulStaffDutyID`;
ALTER TABLE `tawasulStaffDutyPerson` RENAME COLUMN `days_of_week_id` TO `tawasulDaysOfWeekID`;
ALTER TABLE `tawasulStaffDutyPerson` RENAME COLUMN `person_id` TO `tawasulPersonID`;
RENAME TABLE `tos_staff_job_opening` TO `tawasulStaffJobOpening`;
ALTER TABLE `tawasulStaffJobOpening` RENAME COLUMN `staff_job_opening_id` TO `tawasulStaffJobOpeningID`;
ALTER TABLE `tawasulStaffJobOpening` RENAME COLUMN `person_id_creator` TO `tawasulPersonIDCreator`;
RENAME TABLE `tos_staff_update` TO `tawasulStaffUpdate`;
ALTER TABLE `tawasulStaffUpdate` RENAME COLUMN `staff_update_id` TO `tawasulStaffUpdateID`;
ALTER TABLE `tawasulStaffUpdate` RENAME COLUMN `school_year_id` TO `tawasulSchoolYearID`;
ALTER TABLE `tawasulStaffUpdate` RENAME COLUMN `staff_id` TO `tawasulStaffID`;
ALTER TABLE `tawasulStaffUpdate` RENAME COLUMN `person_id_updater` TO `tawasulPersonIDUpdater`;
RENAME TABLE `tos_string` TO `tawasulString`;
ALTER TABLE `tawasulString` RENAME COLUMN `string_id` TO `tawasulStringID`;
RENAME TABLE `tos_student_enrolment` TO `tawasulStudentEnrolment`;
ALTER TABLE `tawasulStudentEnrolment` RENAME COLUMN `student_enrolment_id` TO `tawasulStudentEnrolmentID`;
ALTER TABLE `tawasulStudentEnrolment` RENAME COLUMN `person_id` TO `tawasulPersonID`;
ALTER TABLE `tawasulStudentEnrolment` RENAME COLUMN `school_year_id` TO `tawasulSchoolYearID`;
ALTER TABLE `tawasulStudentEnrolment` RENAME COLUMN `year_group_id` TO `tawasulYearGroupID`;
ALTER TABLE `tawasulStudentEnrolment` RENAME COLUMN `form_group_id` TO `tawasulFormGroupID`;
RENAME TABLE `tos_student_note` TO `tawasulStudentNote`;
ALTER TABLE `tawasulStudentNote` RENAME COLUMN `student_note_id` TO `tawasulStudentNoteID`;
ALTER TABLE `tawasulStudentNote` RENAME COLUMN `person_id` TO `tawasulPersonID`;
ALTER TABLE `tawasulStudentNote` RENAME COLUMN `student_note_category_id` TO `tawasulStudentNoteCategoryID`;
ALTER TABLE `tawasulStudentNote` RENAME COLUMN `person_id_creator` TO `tawasulPersonIDCreator`;
RENAME TABLE `tos_student_note_category` TO `tawasulStudentNoteCategory`;
ALTER TABLE `tawasulStudentNoteCategory` RENAME COLUMN `student_note_category_id` TO `tawasulStudentNoteCategoryID`;
RENAME TABLE `tos_substitute` TO `tawasulSubstitute`;
ALTER TABLE `tawasulSubstitute` RENAME COLUMN `substitute_id` TO `tawasulSubstituteID`;
ALTER TABLE `tawasulSubstitute` RENAME COLUMN `person_id` TO `tawasulPersonID`;
RENAME TABLE `tos_theme` TO `tawasulTheme`;
ALTER TABLE `tawasulTheme` RENAME COLUMN `theme_id` TO `tawasulThemeID`;
RENAME TABLE `tos_timetable` TO `tawasulTT`;
ALTER TABLE `tawasulTT` RENAME COLUMN `timetable_id` TO `tawasulTTID`;
ALTER TABLE `tawasulTT` RENAME COLUMN `school_year_id` TO `tawasulSchoolYearID`;
ALTER TABLE `tawasulTT` RENAME COLUMN `year_group_id_list` TO `tawasulYearGroupIDList`;
RENAME TABLE `tos_timetable_column` TO `tawasulTTColumn`;
ALTER TABLE `tawasulTTColumn` RENAME COLUMN `timetable_column_id` TO `tawasulTTColumnID`;
RENAME TABLE `tos_timetable_column_row` TO `tawasulTTColumnRow`;
ALTER TABLE `tawasulTTColumnRow` RENAME COLUMN `timetable_column_row_id` TO `tawasulTTColumnRowID`;
ALTER TABLE `tawasulTTColumnRow` RENAME COLUMN `timetable_column_id` TO `tawasulTTColumnID`;
RENAME TABLE `tos_timetable_day` TO `tawasulTTDay`;
ALTER TABLE `tawasulTTDay` RENAME COLUMN `timetable_day_id` TO `tawasulTTDayID`;
ALTER TABLE `tawasulTTDay` RENAME COLUMN `timetable_id` TO `tawasulTTID`;
ALTER TABLE `tawasulTTDay` RENAME COLUMN `timetable_column_id` TO `tawasulTTColumnID`;
RENAME TABLE `tos_timetable_day_date` TO `tawasulTTDayDate`;
ALTER TABLE `tawasulTTDayDate` RENAME COLUMN `timetable_day_date_id` TO `tawasulTTDayDateID`;
ALTER TABLE `tawasulTTDayDate` RENAME COLUMN `timetable_day_id` TO `tawasulTTDayID`;
RENAME TABLE `tos_timetable_day_row_class` TO `tawasulTTDayRowClass`;
ALTER TABLE `tawasulTTDayRowClass` RENAME COLUMN `timetable_day_row_class_id` TO `tawasulTTDayRowClassID`;
ALTER TABLE `tawasulTTDayRowClass` RENAME COLUMN `timetable_column_row_id` TO `tawasulTTColumnRowID`;
ALTER TABLE `tawasulTTDayRowClass` RENAME COLUMN `timetable_day_id` TO `tawasulTTDayID`;
ALTER TABLE `tawasulTTDayRowClass` RENAME COLUMN `course_class_id` TO `tawasulCourseClassID`;
ALTER TABLE `tawasulTTDayRowClass` RENAME COLUMN `space_id` TO `tawasulSpaceID`;
RENAME TABLE `tos_timetable_day_row_class_exception` TO `tawasulTTDayRowClassException`;
ALTER TABLE `tawasulTTDayRowClassException` RENAME COLUMN `timetable_day_row_class_exception_id` TO `tawasulTTDayRowClassExceptionID`;
ALTER TABLE `tawasulTTDayRowClassException` RENAME COLUMN `timetable_day_row_class_id` TO `tawasulTTDayRowClassID`;
ALTER TABLE `tawasulTTDayRowClassException` RENAME COLUMN `person_id` TO `tawasulPersonID`;
RENAME TABLE `tos_timetable_import` TO `tawasulTTImport`;
ALTER TABLE `tawasulTTImport` RENAME COLUMN `timetable_import_id` TO `tawasulTTImportID`;
RENAME TABLE `tos_timetable_space_booking` TO `tawasulTTSpaceBooking`;
ALTER TABLE `tawasulTTSpaceBooking` RENAME COLUMN `timetable_space_booking_id` TO `tawasulTTSpaceBookingID`;
ALTER TABLE `tawasulTTSpaceBooking` RENAME COLUMN `person_id` TO `tawasulPersonID`;
RENAME TABLE `tos_timetable_space_change` TO `tawasulTTSpaceChange`;
ALTER TABLE `tawasulTTSpaceChange` RENAME COLUMN `timetable_space_change_id` TO `tawasulTTSpaceChangeID`;
ALTER TABLE `tawasulTTSpaceChange` RENAME COLUMN `timetable_day_row_class_id` TO `tawasulTTDayRowClassID`;
ALTER TABLE `tawasulTTSpaceChange` RENAME COLUMN `space_id` TO `tawasulSpaceID`;
ALTER TABLE `tawasulTTSpaceChange` RENAME COLUMN `person_id` TO `tawasulPersonID`;
RENAME TABLE `tos_unit` TO `tawasulUnit`;
ALTER TABLE `tawasulUnit` RENAME COLUMN `unit_id` TO `tawasulUnitID`;
ALTER TABLE `tawasulUnit` RENAME COLUMN `course_id` TO `tawasulCourseID`;
ALTER TABLE `tawasulUnit` RENAME COLUMN `person_id_creator` TO `tawasulPersonIDCreator`;
ALTER TABLE `tawasulUnit` RENAME COLUMN `person_id_last_edit` TO `tawasulPersonIDLastEdit`;
RENAME TABLE `tos_unit_block` TO `tawasulUnitBlock`;
ALTER TABLE `tawasulUnitBlock` RENAME COLUMN `unit_block_id` TO `tawasulUnitBlockID`;
ALTER TABLE `tawasulUnitBlock` RENAME COLUMN `unit_id` TO `tawasulUnitID`;
RENAME TABLE `tos_unit_class` TO `tawasulUnitClass`;
ALTER TABLE `tawasulUnitClass` RENAME COLUMN `unit_class_id` TO `tawasulUnitClassID`;
ALTER TABLE `tawasulUnitClass` RENAME COLUMN `unit_id` TO `tawasulUnitID`;
ALTER TABLE `tawasulUnitClass` RENAME COLUMN `course_class_id` TO `tawasulCourseClassID`;
RENAME TABLE `tos_unit_class_block` TO `tawasulUnitClassBlock`;
ALTER TABLE `tawasulUnitClassBlock` RENAME COLUMN `unit_class_block_id` TO `tawasulUnitClassBlockID`;
ALTER TABLE `tawasulUnitClassBlock` RENAME COLUMN `unit_class_id` TO `tawasulUnitClassID`;
ALTER TABLE `tawasulUnitClassBlock` RENAME COLUMN `planner_entry_id` TO `tawasulPlannerEntryID`;
ALTER TABLE `tawasulUnitClassBlock` RENAME COLUMN `unit_block_id` TO `tawasulUnitBlockID`;
RENAME TABLE `tos_unit_outcome` TO `tawasulUnitOutcome`;
ALTER TABLE `tawasulUnitOutcome` RENAME COLUMN `unit_outcome_id` TO `tawasulUnitOutcomeID`;
ALTER TABLE `tawasulUnitOutcome` RENAME COLUMN `unit_id` TO `tawasulUnitID`;
ALTER TABLE `tawasulUnitOutcome` RENAME COLUMN `outcome_id` TO `tawasulOutcomeID`;
RENAME TABLE `tos_username_format` TO `tawasulUsernameFormat`;
ALTER TABLE `tawasulUsernameFormat` RENAME COLUMN `username_format_id` TO `tawasulUsernameFormatID`;
ALTER TABLE `tawasulUsernameFormat` RENAME COLUMN `role_id_list` TO `tawasulRoleIDList`;
RENAME TABLE `tos_year_group` TO `tawasulYearGroup`;
ALTER TABLE `tawasulYearGroup` RENAME COLUMN `year_group_id` TO `tawasulYearGroupID`;
ALTER TABLE `tawasulYearGroup` RENAME COLUMN `person_id_hoy` TO `tawasulPersonIDHOY`;
SET FOREIGN_KEY_CHECKS=1;
