<?php
// Generated by tools/merge/column_map.php, then reviewed.
//
// Every entry is a column rename that means the same thing in all 28 tables, so it
// is safe to apply as a single global rewrite while porting the code. Renames
// belonging to Invoice and InvoiceLine are withheld: those two tables are
// rewritten onto the surviving invoice model rather than renamed, and their
// names ('amount', 'feePlanID', 'feeItemID') collide with columns that must keep
// their existing meaning elsewhere.

return array (
);
