<?php
/*
Table => Gibbon module/action mapping used for role-permission enforcement.

GENERATED FILE — do not edit by hand.
Run: node "tools/generate-action-map.mjs" from the module folder.
Derived statically from core/tawasul.sql (tawasulAction.URLList) and the PHP
pages of each core module — see tools/generate-action-map.mjs for the method.
*/

return [
    'tawasulAction' => ['module' => 'System Admin', 'action' => 'Manage Modules', 'writeAction' => 'Manage Modules', 'confidence' => 'curated'],
    'tawasulActivity' => ['module' => 'Activities', 'action' => 'Manage Activities', 'writeAction' => 'Manage Activities', 'confidence' => 'curated'],
    'tawasulActivityAttendance' => ['module' => 'Activities', 'action' => 'Enter Activity Attendance', 'writeAction' => 'Enter Activity Attendance', 'confidence' => 'curated'],
    'tawasulActivityCategory' => ['module' => 'Activities', 'action' => 'Manage Categories', 'writeAction' => 'Manage Categories', 'confidence' => 'curated'],
    'tawasulActivityChoice' => ['module' => 'Activities', 'action' => 'Students Not Signed Up', 'writeAction' => 'Manage Choices', 'confidence' => 'low'],
    'tawasulActivityPhoto' => ['module' => 'Activities', 'action' => 'Manage Activities', 'writeAction' => 'Manage Activities', 'confidence' => 'low'],
    'tawasulActivitySlot' => ['module' => 'Activities', 'action' => 'Manage Activities', 'writeAction' => 'Manage Activities', 'confidence' => 'curated'],
    'tawasulActivityStaff' => ['module' => 'Activities', 'action' => 'Manage Staffing', 'writeAction' => 'Manage Staffing', 'confidence' => 'curated'],
    'tawasulActivityStudent' => ['module' => 'Activities', 'action' => 'Manage Activities', 'writeAction' => 'Manage Activities', 'confidence' => 'curated'],
    'tawasulActivityType' => ['module' => 'School Admin', 'action' => 'Activity Settings', 'writeAction' => 'Activity Settings', 'confidence' => 'curated'],
    'tawasulAdmissionsAccount' => ['module' => 'Admissions', 'action' => 'Manage Applications', 'writeAction' => 'Manage Applications', 'confidence' => 'medium'],
    'tawasulAdmissionsApplication' => ['module' => 'Admissions', 'action' => 'Manage Applications', 'writeAction' => 'Manage Applications', 'confidence' => 'medium'],
    'tawasulAlarm' => ['module' => 'System Admin', 'action' => 'Sound Alarm', 'writeAction' => 'Sound Alarm', 'confidence' => 'curated'],
    'tawasulAlarmConfirm' => ['module' => 'System Admin', 'action' => 'Sound Alarm', 'writeAction' => 'Sound Alarm', 'confidence' => 'curated'],
    'tawasulAlert' => ['module' => 'School Admin', 'action' => 'Student Alert Settings', 'writeAction' => 'Student Alert Settings', 'confidence' => 'curated', 'readActions' => [['module' => 'Student Alerts', 'action' => 'Manage Student Alerts'], ['module' => 'Student Alerts', 'action' => 'Student Alerts by Class'], ['module' => 'Student Alerts', 'action' => 'Student Alerts by Form Group']], 'writeActions' => [['module' => 'Student Alerts', 'action' => 'Manage Student Alerts']]],
    'tawasulAlertLevel' => ['module' => 'School Admin', 'action' => 'Student Alert Settings', 'writeAction' => 'Student Alert Settings', 'confidence' => 'high'],
    'tawasulAlertType' => ['module' => 'School Admin', 'action' => 'Student Alert Settings', 'writeAction' => 'Student Alert Settings', 'confidence' => 'medium'],
    'tawasulApplicationForm' => ['module' => 'Students', 'action' => 'Manage Applications', 'writeAction' => 'Manage Applications', 'confidence' => 'curated'],
    'tawasulApplicationFormFile' => ['module' => 'Students', 'action' => 'Manage Applications', 'writeAction' => 'Manage Applications', 'confidence' => 'medium'],
    'tawasulApplicationFormLink' => ['module' => 'Students', 'action' => 'Manage Applications', 'writeAction' => 'Manage Applications', 'confidence' => 'low'],
    'tawasulApplicationFormRelationship' => ['module' => 'Students', 'action' => 'Manage Applications', 'writeAction' => 'Manage Applications', 'confidence' => 'medium'],
    'tawasulAttendanceCode' => ['module' => 'School Admin', 'action' => 'Attendance Settings', 'writeAction' => 'Attendance Settings', 'confidence' => 'curated'],
    'tawasulAttendanceLogCourseClass' => ['module' => 'Attendance', 'action' => 'Attendance By Class', 'writeAction' => 'Attendance By Class', 'confidence' => 'curated', 'readActions' => [['module' => 'Attendance', 'action' => 'Classes Not Registered'], ['module' => 'Attendance', 'action' => 'Students Not In Class'], ['module' => 'Attendance', 'action' => 'Attendance Summary by Date'], ['module' => 'Attendance', 'action' => 'Manage Attendance Logs']], 'writeActions' => [['module' => 'Attendance', 'action' => 'Ad Hoc Attendance'], ['module' => 'Attendance', 'action' => 'Manage Attendance Logs']]],
    'tawasulAttendanceLogFormGroup' => ['module' => 'Attendance', 'action' => 'Attendance By Form Group', 'writeAction' => 'Attendance By Form Group', 'confidence' => 'curated', 'readActions' => [['module' => 'Attendance', 'action' => 'Form Groups Not Registered'], ['module' => 'Attendance', 'action' => 'View Daily Attendance'], ['module' => 'Attendance', 'action' => 'Attendance Summary by Date'], ['module' => 'Attendance', 'action' => 'Manage Attendance Logs']], 'writeActions' => [['module' => 'Attendance', 'action' => 'Ad Hoc Attendance'], ['module' => 'Attendance', 'action' => 'Manage Attendance Logs']]],
    'tawasulAttendanceLogPerson' => ['module' => 'Attendance', 'action' => 'Attendance By Person', 'writeAction' => 'Attendance By Person', 'confidence' => 'curated', 'readActions' => [['module' => 'Attendance', 'action' => 'Student History'], ['module' => 'Attendance', 'action' => 'View Daily Attendance'], ['module' => 'Attendance', 'action' => 'Attendance Summary by Date'], ['module' => 'Attendance', 'action' => 'Attendance Trends'], ['module' => 'Attendance', 'action' => 'Students Not Present'], ['module' => 'Attendance', 'action' => 'Students Not Onsite'], ['module' => 'Attendance', 'action' => 'Students Not In Class'], ['module' => 'Attendance', 'action' => 'Consecutive Absences'], ['module' => 'Attendance', 'action' => 'Manage Attendance Logs'], ['module' => 'Attendance', 'action' => 'Attendance By Form Group'], ['module' => 'Attendance', 'action' => 'Attendance By Class']], 'writeActions' => [['module' => 'Attendance', 'action' => 'Ad Hoc Attendance'], ['module' => 'Attendance', 'action' => 'Set Future Absence'], ['module' => 'Attendance', 'action' => 'Student Self Registration'], ['module' => 'Attendance', 'action' => 'Manage Attendance Logs'], ['module' => 'Attendance', 'action' => 'Attendance By Form Group'], ['module' => 'Attendance', 'action' => 'Attendance By Class']]],
    'tawasulBehaviour' => ['module' => 'Behaviour', 'action' => 'View Behaviour Records', 'writeAction' => 'Manage Behaviour Records', 'confidence' => 'curated'],
    'tawasulBehaviourFollowUp' => ['module' => 'Behaviour', 'action' => 'View Behaviour Records', 'writeAction' => 'Manage Behaviour Records', 'confidence' => 'curated'],
    'tawasulBehaviourLetter' => ['module' => 'Behaviour', 'action' => 'View Behaviour Letters', 'writeAction' => 'View Behaviour Letters', 'confidence' => 'curated'],
    'tawasulCalendar' => ['module' => 'Calendar', 'action' => 'Manage Events', 'writeAction' => 'Manage Events', 'confidence' => 'high'],
    'tawasulCalendarEditor' => ['module' => 'Calendar', 'action' => 'Manage Events', 'writeAction' => 'Manage Events', 'confidence' => 'low'],
    'tawasulCalendarEvent' => ['module' => 'Calendar', 'action' => 'Manage Events', 'writeAction' => 'Manage Events', 'confidence' => 'curated'],
    'tawasulCalendarEventPerson' => ['module' => 'Calendar', 'action' => 'Manage Events', 'writeAction' => 'Manage Events', 'confidence' => 'low'],
    'tawasulCalendarEventType' => ['module' => 'Activities', 'action' => 'Enter Activity Attendance', 'writeAction' => 'Enter Activity Attendance', 'confidence' => 'low'],
    'tawasulCountry' => ['module' => 'System Admin', 'action' => 'System Settings', 'writeAction' => 'System Settings', 'confidence' => 'curated'],
    'tawasulCourse' => ['module' => 'Timetable Admin', 'action' => 'Manage Courses & Classes', 'writeAction' => 'Manage Courses & Classes', 'confidence' => 'curated'],
    'tawasulCourseClass' => ['module' => 'Timetable Admin', 'action' => 'Manage Courses & Classes', 'writeAction' => 'Manage Courses & Classes', 'confidence' => 'curated'],
    'tawasulCourseClassMap' => ['module' => 'Timetable Admin', 'action' => 'Manage Courses & Classes', 'writeAction' => 'Manage Courses & Classes', 'confidence' => 'curated'],
    'tawasulCourseClassPerson' => ['module' => 'Timetable Admin', 'action' => 'Manage Courses & Classes', 'writeAction' => 'Manage Courses & Classes', 'confidence' => 'curated'],
    'tawasulMessengerChat' => ['module' => 'Messenger', 'action' => 'Chat', 'writeAction' => 'Chat', 'confidence' => 'curated'],
    'tawasulMessengerChatParticipant' => ['module' => 'Messenger', 'action' => 'Chat', 'writeAction' => 'Chat', 'confidence' => 'curated'],
    'tawasulMessengerChatMessage' => ['module' => 'Messenger', 'action' => 'Chat', 'writeAction' => 'Chat', 'confidence' => 'curated'],
    'tawasulMessengerChatAttachment' => ['module' => 'Messenger', 'action' => 'Chat', 'writeAction' => 'Chat', 'confidence' => 'curated'],
    'tawasulCrowdAssessDiscuss' => ['module' => 'Crowd Assessment', 'action' => 'Assess', 'writeAction' => 'Assess', 'confidence' => 'medium'],
    'tawasulCustomField' => ['module' => 'Students', 'action' => 'Medical Data Summary', 'writeAction' => 'Medical Data Summary', 'confidence' => 'medium'],
    'tawasulDataRetention' => ['module' => 'User Admin', 'action' => 'Manage Users', 'writeAction' => 'Manage Users', 'confidence' => 'medium'],
    'tawasulDaysOfWeek' => ['module' => 'School Admin', 'action' => 'Days of the Week', 'writeAction' => 'Days of the Week', 'confidence' => 'high'],
    'tawasulDepartment' => ['module' => 'School Admin', 'action' => 'Manage Departments', 'writeAction' => 'Manage Departments', 'confidence' => 'curated'],
    'tawasulDepartmentResource' => ['module' => 'School Admin', 'action' => 'Manage Departments', 'writeAction' => 'Manage Departments', 'confidence' => 'curated'],
    'tawasulDepartmentStaff' => ['module' => 'School Admin', 'action' => 'Manage Departments', 'writeAction' => 'Manage Departments', 'confidence' => 'curated'],
    'tawasulDiscussion' => ['module' => 'Crowd Assessment', 'action' => 'Assess', 'writeAction' => 'Assess', 'confidence' => 'medium'],
    'tawasulDistrict' => ['module' => 'User Admin', 'action' => 'Manage Districts', 'writeAction' => 'Manage Districts', 'confidence' => 'high'],
    'tawasulEmailTemplate' => ['module' => 'System Admin', 'action' => 'Email Templates', 'writeAction' => 'Email Templates', 'confidence' => 'high'],
    'tawasulExternalAssessment' => ['module' => 'School Admin', 'action' => 'Manage External Assessments', 'writeAction' => 'Manage External Assessments', 'confidence' => 'curated'],
    'tawasulExternalAssessmentField' => ['module' => 'Formal Assessment', 'action' => 'External Assessment Data', 'writeAction' => 'External Assessment Data', 'confidence' => 'low'],
    'tawasulExternalAssessmentStudent' => ['module' => 'Formal Assessment', 'action' => 'Write Internal Assessments', 'writeAction' => 'External Assessment Data', 'confidence' => 'low'],
    'tawasulExternalAssessmentStudentEntry' => ['module' => 'Formal Assessment', 'action' => 'External Assessment Data', 'writeAction' => 'External Assessment Data', 'confidence' => 'medium'],
    'tawasulFamily' => ['module' => 'User Admin', 'action' => 'Manage Families', 'writeAction' => 'Manage Families', 'confidence' => 'curated'],
    'tawasulFamilyAdult' => ['module' => 'User Admin', 'action' => 'Manage Families', 'writeAction' => 'Manage Families', 'confidence' => 'curated'],
    'tawasulFamilyChild' => ['module' => 'User Admin', 'action' => 'Manage Families', 'writeAction' => 'Manage Families', 'confidence' => 'curated'],
    'tawasulFamilyRelationship' => ['module' => 'User Admin', 'action' => 'Manage Families', 'writeAction' => 'Manage Families', 'confidence' => 'curated'],
    'tawasulFamilyUpdate' => ['module' => 'Data Updater', 'action' => 'Family Data Updater History', 'writeAction' => 'Family Data Updates', 'confidence' => 'medium'],
    'tawasulFileExtension' => ['module' => 'School Admin', 'action' => 'Manage File Extensions', 'writeAction' => 'Manage File Extensions', 'confidence' => 'high'],
    'tawasulFinanceBillingSchedule' => ['module' => 'Finance', 'action' => 'Manage Invoices', 'writeAction' => 'Manage Invoices', 'confidence' => 'medium'],
    'tawasulFinanceBudget' => ['module' => 'Finance', 'action' => 'Manage Budgets', 'writeAction' => 'Manage Budgets', 'confidence' => 'curated'],
    'tawasulFinanceBudgetCycle' => ['module' => 'Finance', 'action' => 'Manage Budgets', 'writeAction' => 'Manage Budgets', 'confidence' => 'low'],
    'tawasulFinanceBudgetCycleAllocation' => ['module' => 'Finance', 'action' => 'Manage Budget Cycles', 'writeAction' => 'Manage Budget Cycles', 'confidence' => 'medium'],
    'tawasulFinanceBudgetPerson' => ['module' => 'Finance', 'action' => 'Manage Expenses', 'writeAction' => 'Manage Expenses', 'confidence' => 'low'],
    'tawasulFinanceExpense' => ['module' => 'Finance', 'action' => 'Manage Expenses', 'writeAction' => 'Manage Expenses', 'confidence' => 'curated'],
    'tawasulFinanceExpenseApprover' => ['module' => 'Finance', 'action' => 'Manage Expenses', 'writeAction' => 'Manage Expenses', 'confidence' => 'low'],
    'tawasulFinanceExpenseLog' => ['module' => 'Finance', 'action' => 'Manage Expenses', 'writeAction' => 'Manage Expenses', 'confidence' => 'medium'],
    'tawasulFinanceFee' => ['module' => 'Finance', 'action' => 'Manage Fees', 'writeAction' => 'Manage Fees', 'confidence' => 'curated'],
    'tawasulFinanceFeeCategory' => ['module' => 'Finance', 'action' => 'Manage Fee Categories', 'writeAction' => 'Manage Fee Categories', 'confidence' => 'curated'],
    'tawasulFinanceInvoice' => ['module' => 'Finance', 'action' => 'Manage Invoices', 'writeAction' => 'Manage Invoices', 'confidence' => 'curated'],
    'tawasulFinanceInvoicee' => ['module' => 'Finance', 'action' => 'Manage Invoicees', 'writeAction' => 'Manage Invoicees', 'confidence' => 'curated'],
    'tawasulFinanceInvoiceeUpdate' => ['module' => 'Data Updater', 'action' => 'Finance Data Updates', 'writeAction' => 'Finance Data Updates', 'confidence' => 'medium'],
    'tawasulFinanceInvoiceFee' => ['module' => 'Finance', 'action' => 'Manage Invoices', 'writeAction' => 'Manage Invoices', 'confidence' => 'medium'],
    'tawasulFinancePettyCash' => ['module' => 'Finance', 'action' => 'Petty Cash', 'writeAction' => 'Petty Cash', 'confidence' => 'medium'],
    'tawasulFirstAid' => ['module' => 'Students', 'action' => 'First Aid Record', 'writeAction' => 'First Aid Record', 'confidence' => 'high'],
    'tawasulFirstAidFollowUp' => ['module' => 'Students', 'action' => 'First Aid Record', 'writeAction' => 'First Aid Record', 'confidence' => 'curated'],
    'tawasulForm' => ['module' => 'Admissions', 'action' => 'My Application Forms', 'writeAction' => 'My Application Forms', 'confidence' => 'high'],
    'tawasulFormField' => ['module' => 'Staff', 'action' => 'Manage Applications', 'writeAction' => 'Manage Applications', 'confidence' => 'low'],
    'tawasulFormGroup' => ['module' => 'School Admin', 'action' => 'Manage Form Groups', 'writeAction' => 'Manage Form Groups', 'confidence' => 'curated'],
    'tawasulFormPage' => ['module' => 'Admissions', 'action' => 'My Application Forms', 'writeAction' => 'Manage Applications', 'confidence' => 'low'],
    'tawasulFormSubmission' => ['module' => 'Admissions', 'action' => 'My Application Forms', 'writeAction' => 'Manage Applications', 'confidence' => 'low'],
    'tawasulFormUpload' => ['module' => 'System Admin', 'action' => 'Form Builder', 'writeAction' => 'Form Builder', 'confidence' => 'curated'],
    'tawasulGroup' => ['module' => 'Messenger', 'action' => 'Manage Groups', 'writeAction' => 'Manage Groups', 'confidence' => 'curated'],
    'tawasulGroupPerson' => ['module' => 'Messenger', 'action' => 'Manage Groups', 'writeAction' => 'Manage Groups', 'confidence' => 'curated'],
    'tawasulHook' => ['module' => 'System Admin', 'action' => 'Manage Modules', 'writeAction' => 'Manage Modules', 'confidence' => 'curated'],
    'tawasulHouse' => ['module' => 'School Admin', 'action' => 'Manage Houses', 'writeAction' => 'Manage Houses', 'confidence' => 'curated'],
    'tawasuli18n' => ['module' => 'System Admin', 'action' => 'Manage Languages', 'writeAction' => 'Manage Languages', 'confidence' => 'curated'],
    'tawasulIN' => ['module' => 'Individual Needs', 'action' => 'Archive Records', 'writeAction' => 'Archive Records', 'confidence' => 'high'],
    'tawasulINArchive' => ['module' => 'Individual Needs', 'action' => 'Archive Records', 'writeAction' => 'Archive Records', 'confidence' => 'curated'],
    'tawasulINAssistant' => ['module' => 'Individual Needs', 'action' => 'Individual Needs Records', 'writeAction' => 'Individual Needs Records', 'confidence' => 'curated'],
    'tawasulINDescriptor' => ['module' => 'Individual Needs', 'action' => 'Archive Records', 'writeAction' => 'Archive Records', 'confidence' => 'low'],
    'tawasulINInvestigation' => ['module' => 'Individual Needs', 'action' => 'Manage Investigations', 'writeAction' => 'Manage Investigations', 'confidence' => 'curated'],
    'tawasulINInvestigationContribution' => ['module' => 'Individual Needs', 'action' => 'Manage Investigations', 'writeAction' => 'Submit Contributions', 'confidence' => 'curated'],
    'tawasulINPersonDescriptor' => ['module' => 'Individual Needs', 'action' => 'Individual Needs Records', 'writeAction' => 'Individual Needs Records', 'confidence' => 'curated'],
    'tawasulInternalAssessmentColumn' => ['module' => 'Tracking', 'action' => 'Graphing', 'writeAction' => 'Graphing', 'confidence' => 'low'],
    'tawasulInternalAssessmentEntry' => ['module' => 'Tracking', 'action' => 'Graphing', 'writeAction' => 'Graphing', 'confidence' => 'low'],
    'tawasulLanguage' => ['module' => 'Students', 'action' => 'Application Form', 'writeAction' => 'Manage Applications', 'confidence' => 'medium'],
    'tawasulLibraryItem' => ['module' => 'Library', 'action' => 'Manage Catalog', 'writeAction' => 'Manage Catalog', 'confidence' => 'curated'],
    'tawasulLibraryItemEvent' => ['module' => 'Library', 'action' => 'Lending & Activity Log', 'writeAction' => 'Manage Catalog', 'confidence' => 'low'],
    'tawasulLibraryShelf' => ['module' => 'Library', 'action' => 'Browse The Library', 'writeAction' => 'Browse The Library', 'confidence' => 'medium'],
    'tawasulLibraryShelfItem' => ['module' => 'Library', 'action' => 'Browse The Library', 'writeAction' => 'Browse The Library', 'confidence' => 'medium'],
    'tawasulLibraryType' => ['module' => 'Library', 'action' => 'Manage Catalog', 'writeAction' => 'Manage Catalog', 'confidence' => 'curated'],
    'tawasulLog' => ['module' => 'System Admin', 'action' => 'View Logs', 'writeAction' => 'View Logs', 'confidence' => 'high'],
    'tawasulMarkbookColumn' => ['module' => 'Markbook', 'action' => 'View Markbook', 'writeAction' => 'Edit Markbook', 'confidence' => 'curated', 'readActions' => [['module' => 'Markbook', 'action' => 'Edit Markbook'], ['module' => 'Markbook', 'action' => 'Manage Weightings']], 'writeActions' => [['module' => 'Markbook', 'action' => 'Manage Weightings']]],
    'tawasulMarkbookEntry' => ['module' => 'Markbook', 'action' => 'View Markbook', 'writeAction' => 'Edit Markbook', 'confidence' => 'curated', 'readActions' => [['module' => 'Markbook', 'action' => 'Edit Markbook'], ['module' => 'Markbook', 'action' => 'Manage Weightings']], 'writeActions' => [['module' => 'Markbook', 'action' => 'Manage Weightings']]],
    'tawasulMarkbookTarget' => ['module' => 'Markbook', 'action' => 'View Markbook', 'writeAction' => 'Edit Markbook', 'confidence' => 'curated', 'readActions' => [['module' => 'Markbook', 'action' => 'Edit Markbook']], 'writeActions' => [['module' => 'Markbook', 'action' => 'Edit Markbook']]],
    'tawasulMarkbookWeight' => ['module' => 'Markbook', 'action' => 'Manage Weightings', 'writeAction' => 'Manage Weightings', 'confidence' => 'curated'],
    'tawasulMedicalCondition' => ['module' => 'School Admin', 'action' => 'Manage Medical Conditions', 'writeAction' => 'Manage Medical Conditions', 'confidence' => 'curated'],
    'tawasulMessenger' => ['module' => 'Messenger', 'action' => 'Manage Messages', 'writeAction' => 'New Message', 'confidence' => 'curated', 'readActions' => [['module' => 'Messenger', 'action' => 'View Message Wall'], ['module' => 'Messenger', 'action' => 'Manage Mailing Lists'], ['module' => 'Messenger', 'action' => 'Manage Mailing List Recipients'], ['module' => 'Messenger', 'action' => 'Canned Response']], 'writeActions' => [['module' => 'Messenger', 'action' => 'New Quick Wall Message'], ['module' => 'Messenger', 'action' => 'Manage Mailing Lists']]],
    'tawasulMessengerCannedResponse' => ['module' => 'Messenger', 'action' => 'Canned Response', 'writeAction' => 'Canned Response', 'confidence' => 'medium'],
    'tawasulMessengerMailingList' => ['module' => 'Messenger', 'action' => 'Manage Mailing List Recipients', 'writeAction' => 'Manage Mailing List Recipients', 'confidence' => 'low'],
    'tawasulMessengerMailingListRecipient' => ['module' => 'Messenger', 'action' => 'Manage Mailing List Recipients', 'writeAction' => 'Manage Mailing List Recipients', 'confidence' => 'low'],
    'tawasulMessengerReceipt' => ['module' => 'Messenger', 'action' => 'Manage Messages', 'writeAction' => 'New Message', 'confidence' => 'curated', 'readActions' => [['module' => 'Messenger', 'action' => 'View Message Wall']], 'writeActions' => [['module' => 'Messenger', 'action' => 'New Quick Wall Message']]],
    'tawasulMessengerTarget' => ['module' => 'Messenger', 'action' => 'Manage Messages', 'writeAction' => 'New Message', 'confidence' => 'curated', 'readActions' => [['module' => 'Messenger', 'action' => 'Manage Mailing Lists'], ['module' => 'Messenger', 'action' => 'View Message Wall']], 'writeActions' => [['module' => 'Messenger', 'action' => 'Manage Mailing Lists'], ['module' => 'Messenger', 'action' => 'New Quick Wall Message']]],
    'tawasulModule' => ['module' => 'System Admin', 'action' => 'Manage Modules', 'writeAction' => 'Manage Modules', 'confidence' => 'curated'],
    'tawasulNotification' => ['module' => 'System Admin', 'action' => 'Notification Events', 'writeAction' => 'Notification Events', 'confidence' => 'high'],
    'tawasulNotificationEvent' => ['module' => 'System Admin', 'action' => 'Notification Events', 'writeAction' => 'Notification Events', 'confidence' => 'high'],
    'tawasulNotificationListener' => ['module' => 'System Admin', 'action' => 'Notification Events', 'writeAction' => 'Notification Events', 'confidence' => 'medium'],
    'tawasulOutcome' => ['module' => 'Planner', 'action' => 'Manage Outcomes', 'writeAction' => 'Manage Outcomes', 'confidence' => 'curated', 'readActions' => [['module' => 'Planner', 'action' => 'Outcomes By Course'], ['module' => 'Planner', 'action' => 'Concept Explorer']]],
    'tawasulPayment' => ['module' => 'Students', 'action' => 'Manage Applications', 'writeAction' => 'Manage Applications', 'confidence' => 'low'],
    'tawasulPermission' => ['module' => 'User Admin', 'action' => 'Manage Permissions', 'writeAction' => 'Manage Permissions', 'confidence' => 'curated'],
    'tawasulPerson' => ['module' => 'User Admin', 'action' => 'Manage Users', 'writeAction' => 'Manage Users', 'confidence' => 'curated', 'readActions' => [['module' => 'Students', 'action' => 'View Student Profile'], ['module' => 'Students', 'action' => 'Students by Form Group'], ['module' => 'Students', 'action' => 'Students by House'], ['module' => 'Students', 'action' => 'Form Group Summary'], ['module' => 'Students', 'action' => 'Age & Gender Summary'], ['module' => 'Students', 'action' => 'Emergency Data Summary'], ['module' => 'Students', 'action' => 'Family Address by Student'], ['module' => 'Students', 'action' => 'Student ID Cards'], ['module' => 'Students', 'action' => 'Student Transport'], ['module' => 'Students', 'action' => 'Privacy Choices by Student'], ['module' => 'Students', 'action' => 'Letters Home by Form Group'], ['module' => 'Students', 'action' => 'My Student History'], ['module' => 'Students', 'action' => 'Emergency SMS by Year Group'], ['module' => 'Students', 'action' => 'Emergency SMS by Transport'], ['module' => 'Students', 'action' => 'Personal Document Summary'], ['module' => 'Staff', 'action' => 'Staff Directory'], ['module' => 'Form Groups', 'action' => 'View Form Groups']], 'writeActions' => [['module' => 'Data Updater', 'action' => 'Update Personal Data']]],
    'tawasulPersonalDocument' => ['module' => 'Students', 'action' => 'Personal Document Summary', 'writeAction' => 'Manage Applications', 'confidence' => 'high'],
    'tawasulPersonalDocumentType' => ['module' => 'User Admin', 'action' => 'Personal Document Settings', 'writeAction' => 'Personal Document Settings', 'confidence' => 'curated'],
    'tawasulPersonMedical' => ['module' => 'Students', 'action' => 'Manage Medical Forms', 'writeAction' => 'Manage Medical Forms', 'confidence' => 'curated'],
    'tawasulPersonMedicalCondition' => ['module' => 'Students', 'action' => 'Manage Medical Forms', 'writeAction' => 'Manage Medical Forms', 'confidence' => 'curated'],
    'tawasulPersonMedicalConditionUpdate' => ['module' => 'Students', 'action' => 'Manage Medical Forms', 'writeAction' => 'Manage Medical Forms', 'confidence' => 'curated'],
    'tawasulPersonMedicalUpdate' => ['module' => 'Data Updater', 'action' => 'Medical Form Updates', 'writeAction' => 'Update Medical Data', 'confidence' => 'curated'],
    'tawasulPersonPhoto' => ['module' => 'System Admin', 'action' => 'Upload Photos & Files', 'writeAction' => 'Upload Photos & Files', 'confidence' => 'curated'],
    'tawasulPersonReset' => ['module' => 'User Admin', 'action' => 'Manage Users', 'writeAction' => 'Manage Users', 'confidence' => 'curated'],
    'tawasulPersonStatusLog' => ['module' => 'User Admin', 'action' => 'Rollover', 'writeAction' => 'Rollover', 'confidence' => 'medium'],
    'tawasulPersonUpdate' => ['module' => 'Data Updater', 'action' => 'Student Data Updater History', 'writeAction' => 'Personal Data Updates', 'confidence' => 'low'],
    'tawasulPlannerEntry' => ['module' => 'Planner', 'action' => 'Lesson Planner', 'writeAction' => 'Lesson Planner', 'confidence' => 'curated', 'readActions' => [['module' => 'Planner', 'action' => 'Concept Explorer'], ['module' => 'Planner', 'action' => 'Scope & Sequence'], ['module' => 'Planner', 'action' => 'Work Summary by Form Group'], ['module' => 'Planner', 'action' => 'Outcomes By Course'], ['module' => 'Planner', 'action' => 'View Resources']], 'writeActions' => [['module' => 'Planner', 'action' => 'Unit Planner']]],
    'tawasulPlannerEntryDiscuss' => ['module' => 'Planner', 'action' => 'Lesson Planner', 'writeAction' => 'Lesson Planner', 'confidence' => 'curated'],
    'tawasulPlannerEntryGuest' => ['module' => 'Planner', 'action' => 'Lesson Planner', 'writeAction' => 'Lesson Planner', 'confidence' => 'curated'],
    'tawasulPlannerEntryHomework' => ['module' => 'Planner', 'action' => 'Lesson Planner', 'writeAction' => 'Lesson Planner', 'confidence' => 'curated'],
    'tawasulPlannerEntryOutcome' => ['module' => 'Planner', 'action' => 'Lesson Planner', 'writeAction' => 'Lesson Planner', 'confidence' => 'curated'],
    'tawasulPlannerEntryStudentHomework' => ['module' => 'Planner', 'action' => 'Lesson Planner', 'writeAction' => 'Lesson Planner', 'confidence' => 'curated'],
    'tawasulPlannerEntryStudentTracker' => ['module' => 'Planner', 'action' => 'Lesson Planner', 'writeAction' => 'Lesson Planner', 'confidence' => 'curated'],
    'tawasulPlannerParentWeeklyEmailSummary' => ['module' => 'Planner', 'action' => 'Parent Weekly Email Summary', 'writeAction' => 'Parent Weekly Email Summary', 'confidence' => 'medium'],
    'tawasulReport' => ['module' => 'Reports', 'action' => 'Generate Reports', 'writeAction' => 'Manage Reports', 'confidence' => 'high'],
    'tawasulReportArchive' => ['module' => 'Reports', 'action' => 'Manage Archives', 'writeAction' => 'Manage Archives', 'confidence' => 'curated'],
    'tawasulReportArchiveEntry' => ['module' => 'Reports', 'action' => 'Manage Archives', 'writeAction' => 'Manage Archives', 'confidence' => 'curated', 'readActions' => [['module' => 'Reports', 'action' => 'View Past Reports'], ['module' => 'Reports', 'action' => 'View by Student'], ['module' => 'Reports', 'action' => 'View Reports']], 'writeActions' => [['module' => 'Reports', 'action' => 'Upload Reports'], ['module' => 'Reports', 'action' => 'Generate Reports'], ['module' => 'Reports', 'action' => 'Send Reports'], ['module' => 'Reports', 'action' => 'Send Notifications']]],
    'tawasulReportingAccess' => ['module' => 'Reports', 'action' => 'Manage Access', 'writeAction' => 'Manage Access', 'confidence' => 'curated'],
    'tawasulReportingCriteria' => ['module' => 'Reports', 'action' => 'Manage Criteria', 'writeAction' => 'Manage Criteria', 'confidence' => 'high'],
    'tawasulReportingCriteriaType' => ['module' => 'Reports', 'action' => 'Manage Criteria', 'writeAction' => 'Manage Criteria', 'confidence' => 'curated'],
    'tawasulReportingCycle' => ['module' => 'Reports', 'action' => 'Generate Reports', 'writeAction' => 'Manage Reports', 'confidence' => 'low', 'readActions' => [['module' => 'Reports', 'action' => 'Manage Reporting Cycles'], ['module' => 'Reports', 'action' => 'My Reporting'], ['module' => 'Reports', 'action' => 'View by Report'], ['module' => 'Reports', 'action' => 'View Past Reports']], 'writeActions' => [['module' => 'Reports', 'action' => 'Manage Reporting Cycles'], ['module' => 'Reports', 'action' => 'Manage Reports']]],
    'tawasulReportingProgress' => ['module' => 'Reports', 'action' => 'Progress by Reporting Cycle', 'writeAction' => 'Write Reports', 'confidence' => 'curated', 'readActions' => [['module' => 'Reports', 'action' => 'Progress by Person'], ['module' => 'Reports', 'action' => 'Progress by Department'], ['module' => 'Reports', 'action' => 'Proof Reading Progress'], ['module' => 'Reports', 'action' => 'My Reporting']], 'writeActions' => [['module' => 'Reports', 'action' => 'Write Reports'], ['module' => 'Reports', 'action' => 'Generate Reports']]],
    'tawasulReportingProof' => ['module' => 'Reports', 'action' => 'Proof Reading Progress', 'writeAction' => 'Proof Read', 'confidence' => 'curated', 'readActions' => [['module' => 'Reports', 'action' => 'Proof Reading Progress']], 'writeActions' => [['module' => 'Reports', 'action' => 'Proof Read']]],
    'tawasulReportingScope' => ['module' => 'Reports', 'action' => 'My Reporting', 'writeAction' => 'My Reporting', 'confidence' => 'low'],
    'tawasulReportingValue' => ['module' => 'Reports', 'action' => 'View by Student', 'writeAction' => 'Write Reports', 'confidence' => 'curated', 'readActions' => [['module' => 'Reports', 'action' => 'View by Report'], ['module' => 'Reports', 'action' => 'View by Student'], ['module' => 'Reports', 'action' => 'View Draft Reports'], ['module' => 'Reports', 'action' => 'View Past Reports'], ['module' => 'Reports', 'action' => 'View Reports'], ['module' => 'Reports', 'action' => 'My Reporting'], ['module' => 'Reports', 'action' => 'Proof Read'], ['module' => 'Reports', 'action' => 'Student Name Conflicts']], 'writeActions' => [['module' => 'Reports', 'action' => 'Write Reports'], ['module' => 'Reports', 'action' => 'Generate Reports'], ['module' => 'Reports', 'action' => 'Upload Reports'], ['module' => 'Reports', 'action' => 'Proof Read']]],
    'tawasulReportPrototypeSection' => ['module' => 'Reports', 'action' => 'Template Builder', 'writeAction' => 'Template Builder', 'confidence' => 'curated'],
    'tawasulReportTemplate' => ['module' => 'Reports', 'action' => 'Template Builder', 'writeAction' => 'Template Builder', 'confidence' => 'curated', 'readActions' => [['module' => 'Reports', 'action' => 'Manage Reports']], 'writeActions' => [['module' => 'Reports', 'action' => 'Manage Reports'], ['module' => 'Reports', 'action' => 'Generate Reports']]],
    'tawasulReportTemplateFont' => ['module' => 'Reports', 'action' => 'Template Builder', 'writeAction' => 'Template Builder', 'confidence' => 'curated'],
    'tawasulReportTemplateSection' => ['module' => 'Reports', 'action' => 'Template Builder', 'writeAction' => 'Template Builder', 'confidence' => 'curated'],
    'tawasulResource' => ['module' => 'Planner', 'action' => 'View Resources', 'writeAction' => 'Manage Resources', 'confidence' => 'high'],
    'tawasulResourceTag' => ['module' => 'Planner', 'action' => 'Manage Resources', 'writeAction' => 'Manage Resources', 'confidence' => 'low'],
    'tawasulRole' => ['module' => 'User Admin', 'action' => 'Manage Roles', 'writeAction' => 'Manage Roles', 'confidence' => 'curated'],
    'tawasulRubric' => ['module' => 'Rubrics', 'action' => 'Manage Rubrics', 'writeAction' => 'Manage Rubrics', 'confidence' => 'curated'],
    'tawasulRubricCell' => ['module' => 'Rubrics', 'action' => 'Manage Rubrics', 'writeAction' => 'Manage Rubrics', 'confidence' => 'curated'],
    'tawasulRubricColumn' => ['module' => 'Rubrics', 'action' => 'Manage Rubrics', 'writeAction' => 'Manage Rubrics', 'confidence' => 'curated'],
    'tawasulRubricEntry' => ['module' => 'Rubrics', 'action' => 'View Rubrics', 'writeAction' => 'Manage Rubrics', 'confidence' => 'curated'],
    'tawasulRubricRow' => ['module' => 'Rubrics', 'action' => 'Manage Rubrics', 'writeAction' => 'Manage Rubrics', 'confidence' => 'curated'],
    'tawasulScale' => ['module' => 'School Admin', 'action' => 'Manage Grade Scales', 'writeAction' => 'Manage Grade Scales', 'confidence' => 'curated'],
    'tawasulScaleGrade' => ['module' => 'School Admin', 'action' => 'Manage Grade Scales', 'writeAction' => 'Manage Grade Scales', 'confidence' => 'curated'],
    'tawasulSchoolYear' => ['module' => 'School Admin', 'action' => 'Manage School Years', 'writeAction' => 'Manage School Years', 'confidence' => 'curated'],
    'tawasulSchoolYearSpecialDay' => ['module' => 'School Admin', 'action' => 'Manage Special Days', 'writeAction' => 'Manage Special Days', 'confidence' => 'curated'],
    'tawasulSchoolYearTerm' => ['module' => 'School Admin', 'action' => 'Manage Terms', 'writeAction' => 'Manage Terms', 'confidence' => 'curated'],
    'tawasulSetting' => ['module' => 'System Admin', 'action' => 'Third Party Settings', 'writeAction' => 'Third Party Settings', 'confidence' => 'curated'],
    'tawasulSpace' => ['module' => 'School Admin', 'action' => 'Manage Facilities', 'writeAction' => 'Manage Facilities', 'confidence' => 'curated'],
    'tawasulSpacePerson' => ['module' => 'School Admin', 'action' => 'Manage Facilities', 'writeAction' => 'Manage Facilities', 'confidence' => 'curated'],
    'tawasulStaff' => ['module' => 'Staff', 'action' => 'Manage Staff', 'writeAction' => 'Manage Staff', 'confidence' => 'curated', 'readActions' => [['module' => 'Staff', 'action' => 'Staff Directory'], ['module' => 'Staff', 'action' => 'Weekly Absences'], ['module' => 'Staff', 'action' => 'Staff Absence Summary'], ['module' => 'Staff', 'action' => 'Staff Coverage Summary'], ['module' => 'Staff', 'action' => 'Substitute Availability'], ['module' => 'Staff', 'action' => 'Daily Coverage Planner']], 'writeActions' => [['module' => 'Data Updater', 'action' => 'Update Staff Data']]],
    'tawasulStaffAbsence' => ['module' => 'Staff', 'action' => 'View Absences', 'writeAction' => 'Manage Staff Absences', 'confidence' => 'curated', 'readActions' => [['module' => 'Staff', 'action' => 'Staff Absence Summary'], ['module' => 'Staff', 'action' => 'Weekly Absences'], ['module' => 'Staff', 'action' => 'View Absences'], ['module' => 'Staff', 'action' => 'Approve Staff Absences']], 'writeActions' => [['module' => 'Staff', 'action' => 'New Absence'], ['module' => 'Staff', 'action' => 'Approve Staff Absences']]],
    'tawasulStaffAbsenceDate' => ['module' => 'Staff', 'action' => 'View Absences', 'writeAction' => 'Manage Staff Absences', 'confidence' => 'curated', 'readActions' => [['module' => 'Staff', 'action' => 'Staff Absence Summary'], ['module' => 'Staff', 'action' => 'Weekly Absences'], ['module' => 'Staff', 'action' => 'View Absences']], 'writeActions' => [['module' => 'Staff', 'action' => 'New Absence'], ['module' => 'Staff', 'action' => 'Approve Staff Absences']]],
    'tawasulStaffAbsenceType' => ['module' => 'Staff', 'action' => 'Weekly Absences', 'writeAction' => 'Manage Staff Coverage', 'confidence' => 'low'],
    'tawasulStaffApplicationForm' => ['module' => 'Staff', 'action' => 'Manage Applications', 'writeAction' => 'Manage Applications', 'confidence' => 'curated'],
    'tawasulStaffApplicationFormFile' => ['module' => 'Staff', 'action' => 'Manage Applications', 'writeAction' => 'Manage Applications', 'confidence' => 'medium'],
    'tawasulStaffContract' => ['module' => 'Staff', 'action' => 'Manage Staff', 'writeAction' => 'Manage Staff', 'confidence' => 'medium'],
    'tawasulStaffCoverage' => ['module' => 'Staff', 'action' => 'Manage Staff Coverage', 'writeAction' => 'Manage Staff Coverage', 'confidence' => 'curated', 'readActions' => [['module' => 'Staff', 'action' => 'Staff Coverage Summary'], ['module' => 'Staff', 'action' => 'My Coverage'], ['module' => 'Staff', 'action' => 'Open Requests'], ['module' => 'Staff', 'action' => 'Daily Coverage Planner'], ['module' => 'Staff', 'action' => 'Manage Substitutes'], ['module' => 'Staff', 'action' => 'Substitute Availability']], 'writeActions' => [['module' => 'Staff', 'action' => 'Request Coverage'], ['module' => 'Staff', 'action' => 'Manage Substitutes']]],
    'tawasulStaffCoverageDate' => ['module' => 'Staff', 'action' => 'Manage Staff Coverage', 'writeAction' => 'Manage Staff Coverage', 'confidence' => 'curated', 'readActions' => [['module' => 'Staff', 'action' => 'Staff Coverage Summary'], ['module' => 'Staff', 'action' => 'My Coverage'], ['module' => 'Staff', 'action' => 'Open Requests'], ['module' => 'Staff', 'action' => 'Daily Coverage Planner']], 'writeActions' => [['module' => 'Staff', 'action' => 'Request Coverage'], ['module' => 'Staff', 'action' => 'Manage Substitutes']]],
    'tawasulStaffDuty' => ['module' => 'Staff', 'action' => 'Duty Schedule', 'writeAction' => 'Duty Schedule', 'confidence' => 'curated'],
    'tawasulStaffDutyPerson' => ['module' => 'Staff', 'action' => 'Daily Coverage Planner', 'writeAction' => 'Manage Staff Coverage', 'confidence' => 'medium'],
    'tawasulStaffJobOpening' => ['module' => 'Staff', 'action' => 'Job Openings', 'writeAction' => 'Job Openings', 'confidence' => 'curated'],
    'tawasulStaffUpdate' => ['module' => 'Data Updater', 'action' => 'Staff Data Updates', 'writeAction' => 'Update Staff Data', 'confidence' => 'curated'],
    'tawasulString' => ['module' => 'System Admin', 'action' => 'String Replacement', 'writeAction' => 'String Replacement', 'confidence' => 'high'],
    'tawasulStudentEnrolment' => ['module' => 'User Admin', 'action' => 'Manage Users', 'writeAction' => 'Manage Users', 'confidence' => 'curated', 'readActions' => [['module' => 'Students', 'action' => 'Students by Form Group'], ['module' => 'Students', 'action' => 'Students by House'], ['module' => 'Students', 'action' => 'Form Group Summary'], ['module' => 'Students', 'action' => 'View Student Profile'], ['module' => 'Timetable Admin', 'action' => 'Class Enrolment by Form Group']], 'writeActions' => [['module' => 'Timetable Admin', 'action' => 'Course Enrolment Rollover'], ['module' => 'User Admin', 'action' => 'Rollover']]],
    'tawasulStudentNote' => ['module' => 'Students', 'action' => 'View Student Profile', 'writeAction' => 'View Student Profile', 'confidence' => 'curated', 'readActions' => [['module' => 'Students', 'action' => 'View Student Profile'], ['module' => 'Student Alerts', 'action' => 'Manage Student Alerts'], ['module' => 'Student Alerts', 'action' => 'Student Alerts by Class'], ['module' => 'Student Alerts', 'action' => 'Student Alerts by Form Group']], 'writeActions' => [['module' => 'Student Alerts', 'action' => 'Manage Student Alerts']]],
    'tawasulStudentNoteCategory' => ['module' => 'Students', 'action' => 'View Student Profile', 'writeAction' => 'View Student Profile', 'confidence' => 'curated'],
    'tawasulSubstitute' => ['module' => 'Staff', 'action' => 'Substitute Availability', 'writeAction' => 'Manage Staff Coverage', 'confidence' => 'high'],
    'tawasulTheme' => ['module' => 'System Admin', 'action' => 'Manage Themes', 'writeAction' => 'Manage Themes', 'confidence' => 'curated'],
    'tawasulTT' => ['module' => 'Timetable Admin', 'action' => 'Manage Timetables', 'writeAction' => 'Manage Timetables', 'confidence' => 'curated'],
    'tawasulTTColumn' => ['module' => 'Timetable Admin', 'action' => 'Manage Timetables', 'writeAction' => 'Manage Timetables', 'confidence' => 'curated'],
    'tawasulTTColumnRow' => ['module' => 'Timetable Admin', 'action' => 'Manage Timetables', 'writeAction' => 'Manage Timetables', 'confidence' => 'curated'],
    'tawasulTTDay' => ['module' => 'Timetable Admin', 'action' => 'Manage Timetables', 'writeAction' => 'Manage Timetables', 'confidence' => 'curated'],
    'tawasulTTDayDate' => ['module' => 'Timetable Admin', 'action' => 'Manage Timetables', 'writeAction' => 'Manage Timetables', 'confidence' => 'curated'],
    'tawasulTTDayRowClass' => ['module' => 'Timetable Admin', 'action' => 'Manage Timetables', 'writeAction' => 'Manage Timetables', 'confidence' => 'curated'],
    'tawasulTTDayRowClassException' => ['module' => 'Timetable Admin', 'action' => 'Manage Timetables', 'writeAction' => 'Manage Timetables', 'confidence' => 'curated'],
    'tawasulTTImport' => ['module' => 'Timetable Admin', 'action' => 'Manage Timetables', 'writeAction' => 'Manage Timetables', 'confidence' => 'curated'],
    'tawasulTTSpaceBooking' => ['module' => 'Timetable', 'action' => 'Manage Facility Bookings', 'writeAction' => 'Manage Facility Bookings', 'confidence' => 'curated'],
    'tawasulTTSpaceChange' => ['module' => 'Timetable', 'action' => 'Manage Facility Changes', 'writeAction' => 'Manage Facility Changes', 'confidence' => 'curated'],
    'tawasulUnit' => ['module' => 'Planner', 'action' => 'Unit Planner', 'writeAction' => 'Unit Planner', 'confidence' => 'curated', 'readActions' => [['module' => 'Planner', 'action' => 'Scope & Sequence'], ['module' => 'Planner', 'action' => 'Concept Explorer'], ['module' => 'Planner', 'action' => 'Outcomes By Course']], 'writeActions' => [['module' => 'Planner', 'action' => 'Lesson Planner']]],
    'tawasulUnitBlock' => ['module' => 'Planner', 'action' => 'Unit Planner', 'writeAction' => 'Unit Planner', 'confidence' => 'curated'],
    'tawasulUnitClass' => ['module' => 'Planner', 'action' => 'Unit Planner', 'writeAction' => 'Unit Planner', 'confidence' => 'curated'],
    'tawasulUnitClassBlock' => ['module' => 'Planner', 'action' => 'Unit Planner', 'writeAction' => 'Unit Planner', 'confidence' => 'curated'],
    'tawasulUnitOutcome' => ['module' => 'Planner', 'action' => 'Unit Planner', 'writeAction' => 'Unit Planner', 'confidence' => 'curated'],
    'tawasulUsernameFormat' => ['module' => 'User Admin', 'action' => 'User Settings', 'writeAction' => 'User Settings', 'confidence' => 'curated'],
    'tawasulYearGroup' => ['module' => 'School Admin', 'action' => 'Manage Year Groups', 'writeAction' => 'Manage Year Groups', 'confidence' => 'curated'],
];
