<?php
/*
Tawasul OS Tools — shared helpers.
*/

function tosValidHex($value, $fallback)
{
    return preg_match('/^#[0-9a-fA-F]{6}$/', (string) $value) ? strtolower($value) : $fallback;
}

function tosPresets()
{
    return [
        'green'  => ['label' => 'Tawasul Green', 'primary' => '#1f4a33', 'accent' => '#e8664f', 'highlight' => '#e9b949'],
        'teal'   => ['label' => 'Sea Green',     'primary' => '#14514f', 'accent' => '#e8664f', 'highlight' => '#e9c46a'],
        'blue'   => ['label' => 'Ocean Blue',    'primary' => '#1d3a5f', 'accent' => '#e76f51', 'highlight' => '#f2c14e'],
        'purple' => ['label' => 'Plum',          'primary' => '#4a2545', 'accent' => '#e07a5f', 'highlight' => '#f2cc8f'],
        'red'    => ['label' => 'Coral',         'primary' => '#5a2a27', 'accent' => '#e8664f', 'highlight' => '#f4d35e'],
    ];
}

/**
 * Writes uploads/tawasul/brand.css, which the Tawasul OS Theme imports on every
 * page including the login page. Deleting the file restores the theme preset.
 */
function tosWriteBrandCss($absolutePath, $useCustom, $primary, $accent, $highlight)
{
    $dir = rtrim($absolutePath, '/').'/uploads/tawasul';
    $file = $dir.'/brand.css';

    if ($useCustom !== 'Y') {
        if (is_file($file)) {
            return @file_put_contents($file, "/* Tawasul OS: custom colours off */\n") !== false;
        }
        return true;
    }

    if (!is_dir($dir) && !@mkdir($dir, 0755, true)) {
        return false;
    }

    $css = "/* Generated by Tawasul OS Tools. Do not edit. */\n"
        ."html body[class] {\n"
        ."  --tos-forest: {$primary};\n"
        ."  --tos-forest-soft: color-mix(in srgb, {$primary} 82%, #ffffff);\n"
        ."  --tos-coral: {$accent};\n"
        ."  --tos-accent: {$highlight};\n"
        ."  --tos-gold: {$highlight};\n"
        ."  --tos-focus: {$highlight};\n"
        ."}\n";

    return @file_put_contents($file, $css) !== false;
}
