<?php
/*
Operations: activities, library, finance, messenger, forms, calendar events,
staff absence and cover.
*/

return [

'activities' => [
    'title' => 'Activities',
    'group' => 'Operations',
    'scope' => 'activities',
    'module' => 'Activities',
    'action' => 'Manage Activities',
    'table' => 'tawasulActivity',
    'primaryKey' => 'tawasulActivityID',
    'description' => 'Extra-curricular activities, their dates, capacity and payment details.',
    'select' => "SELECT tawasulActivity.tawasulActivityID, tawasulActivity.tawasulSchoolYearID, tawasulActivity.tawasulActivityCategoryID, tawasulActivity.active, tawasulActivity.registration, tawasulActivity.name, tawasulActivity.provider, tawasulActivity.type, tawasulActivity.listingStart, tawasulActivity.listingEnd, tawasulActivity.programStart, tawasulActivity.programEnd, tawasulActivity.tawasulYearGroupIDList, tawasulActivity.maxParticipants, tawasulActivity.description, tawasulActivity.payment, tawasulActivity.paymentType, tawasulActivityCategory.name AS categoryName, (SELECT COUNT(*) FROM tawasulActivityStudent WHERE tawasulActivityStudent.tawasulActivityID=tawasulActivity.tawasulActivityID AND status='Accepted') AS participantCount FROM tawasulActivity LEFT JOIN tawasulActivityCategory ON (tawasulActivity.tawasulActivityCategoryID=tawasulActivityCategory.tawasulActivityCategoryID)",
    'yearFilter' => 'tawasulActivity.tawasulSchoolYearID',
    'filters' => ['active' => 'tawasulActivity.active', 'type' => 'tawasulActivity.type', 'tawasulActivityCategoryID' => 'tawasulActivity.tawasulActivityCategoryID', 'provider' => 'tawasulActivity.provider'],
    'search' => ['tawasulActivity.name', 'tawasulActivity.description'],
    'sort' => ['name' => 'tawasulActivity.name', 'programStart' => 'tawasulActivity.programStart'],
    'defaultSort' => 'tawasulActivity.name',
    'writable' => ['tawasulSchoolYearID', 'tawasulActivityCategoryID', 'active', 'registration', 'name', 'provider', 'type', 'listingStart', 'listingEnd', 'programStart', 'programEnd', 'tawasulYearGroupIDList', 'maxParticipants', 'description', 'payment', 'paymentType', 'paymentFirmness'],
    'required' => ['tawasulSchoolYearID', 'name'],
    'methods' => ['GET', 'POST', 'PATCH', 'PUT', 'DELETE'],
],

'activity-students' => [
    'title' => 'Activity Students',
    'group' => 'Operations',
    'scope' => 'activities',
    'module' => 'Activities',
    'action' => 'Manage Activities',
    'table' => 'tawasulActivityStudent',
    'primaryKey' => 'tawasulActivityStudentID',
    'description' => 'Student sign-ups for an activity and their acceptance status.',
    'select' => "SELECT tawasulActivityStudent.tawasulActivityStudentID, tawasulActivityStudent.tawasulActivityID, tawasulActivityStudent.tawasulPersonID, tawasulActivityStudent.status, tawasulActivityStudent.timestamp, tawasulActivity.name AS activityName, tawasulActivity.tawasulSchoolYearID, tawasulPerson.surname, tawasulPerson.preferredName, tawasulPerson.studentID FROM tawasulActivityStudent JOIN tawasulActivity ON (tawasulActivityStudent.tawasulActivityID=tawasulActivity.tawasulActivityID) JOIN tawasulPerson ON (tawasulActivityStudent.tawasulPersonID=tawasulPerson.tawasulPersonID)",
    'yearFilter' => 'tawasulActivity.tawasulSchoolYearID',
    'filters' => ['tawasulActivityID' => 'tawasulActivityStudent.tawasulActivityID', 'tawasulPersonID' => 'tawasulActivityStudent.tawasulPersonID', 'status' => 'tawasulActivityStudent.status'],
    'search' => ['tawasulPerson.surname', 'tawasulPerson.preferredName'],
    'defaultSort' => 'tawasulPerson.surname, tawasulPerson.preferredName',
    'writable' => ['tawasulActivityID', 'tawasulPersonID', 'status'],
    'required' => ['tawasulActivityID', 'tawasulPersonID', 'status'],
    'methods' => ['GET', 'POST', 'PATCH', 'PUT', 'DELETE'],
],

'activity-staff' => [
    'title' => 'Activity Staff',
    'group' => 'Operations',
    'scope' => 'activities',
    'module' => 'Activities',
    'action' => 'Manage Activities',
    'table' => 'tawasulActivityStaff',
    'primaryKey' => 'tawasulActivityStaffID',
    'description' => 'Staff running or assisting with an activity.',
    'select' => "SELECT tawasulActivityStaff.*, tawasulActivity.name AS activityName, tawasulActivity.tawasulSchoolYearID, tawasulPerson.surname, tawasulPerson.preferredName FROM tawasulActivityStaff JOIN tawasulActivity ON (tawasulActivityStaff.tawasulActivityID=tawasulActivity.tawasulActivityID) JOIN tawasulPerson ON (tawasulActivityStaff.tawasulPersonID=tawasulPerson.tawasulPersonID)",
    'yearFilter' => 'tawasulActivity.tawasulSchoolYearID',
    'filters' => ['tawasulActivityID' => 'tawasulActivityStaff.tawasulActivityID', 'tawasulPersonID' => 'tawasulActivityStaff.tawasulPersonID', 'role' => 'tawasulActivityStaff.role'],
    'defaultSort' => 'tawasulPerson.surname',
    'writable' => ['tawasulActivityID', 'tawasulPersonID', 'role'],
    'required' => ['tawasulActivityID', 'tawasulPersonID', 'role'],
    'methods' => ['GET', 'POST', 'PATCH', 'PUT', 'DELETE'],
],

    'library-items' => [
        'title' => 'Library Items',
        'group' => 'Operations',
        'scope' => 'library',
        'module' => 'Library',
        'action' => 'Manage Catalog',
        'writeAction' => 'Manage Catalog',
        'table' => 'tawasulLibraryItem',
    'primaryKey' => 'tawasulLibraryItemID',
    'description' => 'Library catalogue: books, devices and other borrowable assets.',
    'select' => "SELECT tawasulLibraryItem.tawasulLibraryItemID, tawasulLibraryItem.tawasulLibraryTypeID, tawasulLibraryItem.id, tawasulLibraryItem.name, tawasulLibraryItem.producer, tawasulLibraryItem.vendor, tawasulLibraryItem.purchaseDate, tawasulLibraryItem.cost, tawasulLibraryItem.comment, tawasulLibraryItem.tawasulSpaceID, tawasulLibraryItem.locationDetail, tawasulLibraryItem.ownershipType, tawasulLibraryItem.physicalCondition, tawasulLibraryItem.bookable, tawasulLibraryItem.borrowable, tawasulLibraryItem.status, tawasulLibraryItem.tawasulPersonIDStatusResponsible, tawasulLibraryItem.returnExpected, tawasulLibraryType.name AS typeName, tawasulSpace.name AS spaceName, borrower.surname AS borrowerSurname, borrower.preferredName AS borrowerPreferredName FROM tawasulLibraryItem LEFT JOIN tawasulLibraryType ON (tawasulLibraryItem.tawasulLibraryTypeID=tawasulLibraryType.tawasulLibraryTypeID) LEFT JOIN tawasulSpace ON (tawasulLibraryItem.tawasulSpaceID=tawasulSpace.tawasulSpaceID) LEFT JOIN tawasulPerson AS borrower ON (tawasulLibraryItem.tawasulPersonIDStatusResponsible=borrower.tawasulPersonID)",
    'filters' => ['status' => 'tawasulLibraryItem.status', 'tawasulLibraryTypeID' => 'tawasulLibraryItem.tawasulLibraryTypeID', 'borrowable' => 'tawasulLibraryItem.borrowable', 'tawasulSpaceID' => 'tawasulLibraryItem.tawasulSpaceID', 'tawasulPersonIDStatusResponsible' => 'tawasulLibraryItem.tawasulPersonIDStatusResponsible', 'id' => 'tawasulLibraryItem.id'],
    'search' => ['tawasulLibraryItem.name', 'tawasulLibraryItem.producer', 'tawasulLibraryItem.id'],
    'sort' => ['name' => 'tawasulLibraryItem.name', 'returnExpected' => 'tawasulLibraryItem.returnExpected'],
    'defaultSort' => 'tawasulLibraryItem.name',
    'writable' => ['tawasulLibraryTypeID', 'id', 'name', 'producer', 'vendor', 'purchaseDate', 'invoiceNumber', 'cost', 'comment', 'tawasulSpaceID', 'locationDetail', 'ownershipType', 'tawasulPersonIDOwnership', 'tawasulDepartmentID', 'physicalCondition', 'bookable', 'borrowable', 'status'],
    'required' => ['tawasulLibraryTypeID', 'name'],
    'methods' => ['GET', 'POST', 'PATCH', 'PUT', 'DELETE'],
],

    'library-events' => [
        'title' => 'Library Events',
        'group' => 'Operations',
        'scope' => 'library',
        'module' => 'Library',
        'action' => 'Manage Catalog',
        'writeAction' => 'Manage Catalog',
        'table' => 'tawasulLibraryItemEvent',
    'primaryKey' => 'tawasulLibraryItemEventID',
    'description' => 'Loan and return history for library items.',
    'select' => "SELECT tawasulLibraryItemEvent.*, tawasulLibraryItem.name AS itemName FROM tawasulLibraryItemEvent JOIN tawasulLibraryItem ON (tawasulLibraryItemEvent.tawasulLibraryItemID=tawasulLibraryItem.tawasulLibraryItemID)",
    'filters' => ['tawasulLibraryItemID' => 'tawasulLibraryItemEvent.tawasulLibraryItemID', 'type' => 'tawasulLibraryItemEvent.type'],
    'defaultSort' => 'tawasulLibraryItemEvent.timestampOut DESC',
],

'fees' => [
    'title' => 'Fees',
    'group' => 'Operations',
    'scope' => 'finance',
    'module' => 'Finance',
    'action' => 'Manage Fees',
    'table' => 'tawasulFinanceFee',
    'primaryKey' => 'tawasulFinanceFeeID',
    'description' => 'The fee catalogue for a school year.',
    'select' => "SELECT tawasulFinanceFee.tawasulFinanceFeeID, tawasulFinanceFee.tawasulSchoolYearID, tawasulFinanceFee.name, tawasulFinanceFee.nameShort, tawasulFinanceFee.description, tawasulFinanceFee.active, tawasulFinanceFee.fee, tawasulFinanceFee.tawasulFinanceFeeCategoryID, tawasulFinanceFeeCategory.name AS categoryName FROM tawasulFinanceFee LEFT JOIN tawasulFinanceFeeCategory ON (tawasulFinanceFee.tawasulFinanceFeeCategoryID=tawasulFinanceFeeCategory.tawasulFinanceFeeCategoryID)",
    'yearFilter' => 'tawasulFinanceFee.tawasulSchoolYearID',
    'filters' => ['active' => 'tawasulFinanceFee.active', 'tawasulFinanceFeeCategoryID' => 'tawasulFinanceFee.tawasulFinanceFeeCategoryID'],
    'search' => ['tawasulFinanceFee.name', 'tawasulFinanceFee.nameShort'],
    'defaultSort' => 'tawasulFinanceFee.name',
],

'invoices' => [
    'title' => 'Invoices',
    'group' => 'Operations',
    'scope' => 'finance',
    'module' => 'Finance',
    'action' => 'Manage Invoices',
    'table' => 'tawasulFinanceInvoice',
    'primaryKey' => 'tawasulFinanceInvoiceID',
    'description' => 'Invoices issued to invoicees, with status and payment details.',
    'select' => "SELECT tawasulFinanceInvoice.tawasulFinanceInvoiceID, tawasulFinanceInvoice.tawasulSchoolYearID, tawasulFinanceInvoice.tawasulFinanceInvoiceeID, tawasulFinanceInvoice.invoiceTo, tawasulFinanceInvoice.billingScheduleType, tawasulFinanceInvoice.status, tawasulFinanceInvoice.invoiceIssueDate, tawasulFinanceInvoice.invoiceDueDate, tawasulFinanceInvoice.paidDate, tawasulFinanceInvoice.paidAmount, tawasulFinanceInvoice.reminderCount, tawasulFinanceInvoice.notes, tawasulFinanceInvoicee.tawasulPersonID, tawasulPerson.surname, tawasulPerson.preferredName, tawasulPerson.studentID, (SELECT SUM(fee) FROM tawasulFinanceInvoiceFee WHERE tawasulFinanceInvoiceFee.tawasulFinanceInvoiceID=tawasulFinanceInvoice.tawasulFinanceInvoiceID) AS invoiceTotal FROM tawasulFinanceInvoice JOIN tawasulFinanceInvoicee ON (tawasulFinanceInvoice.tawasulFinanceInvoiceeID=tawasulFinanceInvoicee.tawasulFinanceInvoiceeID) JOIN tawasulPerson ON (tawasulFinanceInvoicee.tawasulPersonID=tawasulPerson.tawasulPersonID)",
    'yearFilter' => 'tawasulFinanceInvoice.tawasulSchoolYearID',
    'filters' => ['status' => 'tawasulFinanceInvoice.status', 'tawasulFinanceInvoiceeID' => 'tawasulFinanceInvoice.tawasulFinanceInvoiceeID', 'tawasulPersonID' => 'tawasulFinanceInvoicee.tawasulPersonID', 'invoiceDueDate' => 'tawasulFinanceInvoice.invoiceDueDate'],
    'search' => ['tawasulPerson.surname', 'tawasulPerson.preferredName', 'tawasulPerson.studentID'],
    'sort' => ['invoiceDueDate' => 'tawasulFinanceInvoice.invoiceDueDate', 'status' => 'tawasulFinanceInvoice.status'],
    'defaultSort' => 'tawasulFinanceInvoice.invoiceDueDate DESC',
    'sensitive' => ['key'],
],

'invoice-fees' => [
    'title' => 'Invoice Fees',
    'group' => 'Operations',
    'scope' => 'finance',
    'module' => 'Finance',
    'action' => 'Manage Invoices',
    'table' => 'tawasulFinanceInvoiceFee',
    'primaryKey' => 'tawasulFinanceInvoiceFeeID',
    'description' => 'Line items on an invoice.',
    'select' => "SELECT tawasulFinanceInvoiceFee.* FROM tawasulFinanceInvoiceFee",
    'filters' => ['tawasulFinanceInvoiceID' => 'tawasulFinanceInvoiceFee.tawasulFinanceInvoiceID'],
    'defaultSort' => 'tawasulFinanceInvoiceFee.sequenceNumber',
],

'budgets' => [
    'title' => 'Budgets',
    'group' => 'Operations',
    'scope' => 'finance',
    'module' => 'Finance',
    'action' => 'Manage Budgets',
    'table' => 'tawasulFinanceBudget',
    'primaryKey' => 'tawasulFinanceBudgetID',
    'description' => 'Departmental and school budgets.',
    'select' => "SELECT tawasulFinanceBudget.tawasulFinanceBudgetID, tawasulFinanceBudget.name, tawasulFinanceBudget.nameShort, tawasulFinanceBudget.active, tawasulFinanceBudget.category FROM tawasulFinanceBudget",
    'filters' => ['active' => 'tawasulFinanceBudget.active', 'category' => 'tawasulFinanceBudget.category'],
    'search' => ['tawasulFinanceBudget.name'],
    'defaultSort' => 'tawasulFinanceBudget.name',
],

'expenses' => [
    'title' => 'Expenses',
    'group' => 'Operations',
    'scope' => 'finance',
    'module' => 'Finance',
    'action' => 'Manage Expenses',
    'table' => 'tawasulFinanceExpense',
    'primaryKey' => 'tawasulFinanceExpenseID',
    'description' => 'Expense requests and their approval and payment status.',
    'select' => "SELECT tawasulFinanceExpense.tawasulFinanceExpenseID, tawasulFinanceExpense.tawasulFinanceBudgetID, tawasulFinanceExpense.tawasulFinanceBudgetCycleID, tawasulFinanceExpense.title, tawasulFinanceExpense.status, tawasulFinanceExpense.cost, tawasulFinanceExpense.paymentDate, tawasulFinanceExpense.paymentAmount, tawasulFinanceExpense.tawasulPersonIDCreator, tawasulFinanceExpense.timestampCreator, tawasulFinanceBudget.name AS budgetName FROM tawasulFinanceExpense JOIN tawasulFinanceBudget ON (tawasulFinanceExpense.tawasulFinanceBudgetID=tawasulFinanceBudget.tawasulFinanceBudgetID)",
    'filters' => ['status' => 'tawasulFinanceExpense.status', 'tawasulFinanceBudgetID' => 'tawasulFinanceExpense.tawasulFinanceBudgetID', 'tawasulFinanceBudgetCycleID' => 'tawasulFinanceExpense.tawasulFinanceBudgetCycleID'],
    'search' => ['tawasulFinanceExpense.title'],
    'defaultSort' => 'tawasulFinanceExpense.timestampCreator DESC',
],

'messages' => [
    'title' => 'Messages',
    'group' => 'Operations',
    'scope' => 'messenger',
    'module' => 'Messenger',
    'action' => 'Manage Messages',
    'table' => 'tawasulMessenger',
    'primaryKey' => 'tawasulMessengerID',
    'description' => 'Messenger broadcasts: email, SMS and message wall posts.',
    'select' => "SELECT tawasulMessenger.tawasulMessengerID, tawasulMessenger.tawasulSchoolYearID, tawasulMessenger.status, tawasulMessenger.email, tawasulMessenger.messageWall, tawasulMessenger.messageWall_dateStart, tawasulMessenger.messageWall_dateEnd, tawasulMessenger.sms, tawasulMessenger.subject, tawasulMessenger.body, tawasulMessenger.tawasulPersonID, tawasulMessenger.timestamp, tawasulMessenger.confidential, tawasulPerson.surname AS senderSurname, tawasulPerson.preferredName AS senderPreferredName FROM tawasulMessenger JOIN tawasulPerson ON (tawasulMessenger.tawasulPersonID=tawasulPerson.tawasulPersonID)",
    'yearFilter' => 'tawasulMessenger.tawasulSchoolYearID',
    'filters' => ['status' => 'tawasulMessenger.status', 'tawasulPersonID' => 'tawasulMessenger.tawasulPersonID', 'messageWall' => 'tawasulMessenger.messageWall', 'email' => 'tawasulMessenger.email'],
    'search' => ['tawasulMessenger.subject', 'tawasulMessenger.body'],
    'sort' => ['timestamp' => 'tawasulMessenger.timestamp'],
    'defaultSort' => 'tawasulMessenger.timestamp DESC',
    'writable' => ['tawasulSchoolYearID', 'status', 'email', 'messageWall', 'messageWall_dateStart', 'messageWall_dateEnd', 'sms', 'subject', 'body', 'tawasulPersonID', 'confidential'],
    'methods' => ['GET', 'POST', 'PATCH', 'PUT', 'DELETE'],
],

'message-receipts' => [
    'title' => 'Message Receipts',
    'group' => 'Operations',
    'scope' => 'messenger',
    'module' => 'Messenger',
    'action' => 'Manage Messages',
    'table' => 'tawasulMessengerReceipt',
    'primaryKey' => 'tawasulMessengerReceiptID',
    'description' => 'Delivery and read receipts for a message.',
    'select' => "SELECT tawasulMessengerReceipt.tawasulMessengerReceiptID, tawasulMessengerReceipt.tawasulMessengerID, tawasulMessengerReceipt.tawasulPersonID, tawasulMessengerReceipt.sent, tawasulMessengerReceipt.targetType, tawasulMessengerReceipt.targetID, tawasulMessengerReceipt.contactType, tawasulMessengerReceipt.confirmed, tawasulMessengerReceipt.confirmedTimestamp FROM tawasulMessengerReceipt",
    'filters' => ['tawasulMessengerID' => 'tawasulMessengerReceipt.tawasulMessengerID', 'tawasulPersonID' => 'tawasulMessengerReceipt.tawasulPersonID', 'sent' => 'tawasulMessengerReceipt.sent', 'confirmed' => 'tawasulMessengerReceipt.confirmed'],
    'defaultSort' => 'tawasulMessengerReceipt.tawasulMessengerReceiptID DESC',
    'sensitive' => ['key', 'unsubscribeKey', 'contactDetail'],
],

    'forms' => [
        'title' => 'Forms',
        'group' => 'Operations',
        'scope' => 'forms',
        'module' => 'System Admin',
        'action' => 'Form Builder',
        'writeAction' => 'Form Builder',
        'table' => 'tawasulForm',
    'primaryKey' => 'tawasulFormID',
    'description' => 'Forms built with the form builder.',
    'select' => "SELECT tawasulForm.tawasulFormID, tawasulForm.name, tawasulForm.description, tawasulForm.type, tawasulForm.active, tawasulForm.public, tawasulForm.tawasulYearGroupIDList FROM tawasulForm",
    'filters' => ['active' => 'tawasulForm.active', 'public' => 'tawasulForm.public', 'type' => 'tawasulForm.type'],
    'search' => ['tawasulForm.name'],
    'defaultSort' => 'tawasulForm.name',
    'writable' => ['name', 'description', 'type', 'active', 'public', 'tawasulYearGroupIDList'],
    'required' => ['name'],
    'methods' => ['GET', 'POST', 'PATCH', 'PUT', 'DELETE'],
],

    'form-submissions' => [
        'title' => 'Form Submissions',
        'group' => 'Operations',
        'scope' => 'forms',
        'module' => 'System Admin',
        'action' => 'Form Builder',
        'writeAction' => 'Form Builder',
        'table' => 'tawasulFormSubmission',
    'primaryKey' => 'tawasulFormSubmissionID',
    'description' => 'Submitted form data and its workflow status.',
    'select' => "SELECT tawasulFormSubmission.tawasulFormSubmissionID, tawasulFormSubmission.tawasulFormID, tawasulFormSubmission.foreignTable, tawasulFormSubmission.foreignTableID, tawasulFormSubmission.status, tawasulFormSubmission.identifier, tawasulFormSubmission.data, tawasulFormSubmission.result, tawasulFormSubmission.timestampCreated, tawasulFormSubmission.timestampModified, tawasulForm.name AS formName FROM tawasulFormSubmission JOIN tawasulForm ON (tawasulFormSubmission.tawasulFormID=tawasulForm.tawasulFormID)",
    'filters' => ['tawasulFormID' => 'tawasulFormSubmission.tawasulFormID', 'status' => 'tawasulFormSubmission.status', 'foreignTable' => 'tawasulFormSubmission.foreignTable', 'foreignTableID' => 'tawasulFormSubmission.foreignTableID'],
    'search' => ['tawasulFormSubmission.identifier'],
    'defaultSort' => 'tawasulFormSubmission.timestampCreated DESC',
    'writable' => ['tawasulFormID', 'foreignTable', 'foreignTableID', 'status', 'identifier', 'data', 'result'],
    'methods' => ['GET', 'POST', 'PATCH', 'PUT', 'DELETE'],
],

'calendar-events' => [
    'title' => 'Calendar Events',
    'group' => 'Operations',
    'scope' => 'calendar',
    'module' => 'School Admin',
    'action' => 'Manage Calendars',
    'table' => 'tawasulCalendarEvent',
    'primaryKey' => 'tawasulCalendarEventID',
    'description' => 'Events on a school calendar, with location and timing.',
    'select' => "SELECT tawasulCalendarEvent.tawasulCalendarEventID, tawasulCalendarEvent.tawasulCalendarID, tawasulCalendarEvent.tawasulCalendarEventTypeID, tawasulCalendarEvent.name, tawasulCalendarEvent.description, tawasulCalendarEvent.status, tawasulCalendarEvent.allDay, tawasulCalendarEvent.dateStart, tawasulCalendarEvent.dateEnd, tawasulCalendarEvent.timeStart, tawasulCalendarEvent.timeEnd, tawasulCalendarEvent.locationType, tawasulCalendarEvent.locationDetail, tawasulCalendarEvent.locationURL, tawasulCalendarEvent.tawasulSpaceID, tawasulCalendarEvent.tawasulPersonIDOrganiser, tawasulCalendar.name AS calendarName, tawasulCalendar.tawasulSchoolYearID, tawasulSpace.name AS spaceName FROM tawasulCalendarEvent JOIN tawasulCalendar ON (tawasulCalendarEvent.tawasulCalendarID=tawasulCalendar.tawasulCalendarID) LEFT JOIN tawasulSpace ON (tawasulCalendarEvent.tawasulSpaceID=tawasulSpace.tawasulSpaceID)",
    'yearFilter' => 'tawasulCalendar.tawasulSchoolYearID',
    'filters' => ['tawasulCalendarID' => 'tawasulCalendarEvent.tawasulCalendarID', 'status' => 'tawasulCalendarEvent.status', 'dateStart' => 'tawasulCalendarEvent.dateStart', 'tawasulSpaceID' => 'tawasulCalendarEvent.tawasulSpaceID'],
    'search' => ['tawasulCalendarEvent.name', 'tawasulCalendarEvent.description'],
    'sort' => ['dateStart' => 'tawasulCalendarEvent.dateStart'],
    'defaultSort' => 'tawasulCalendarEvent.dateStart, tawasulCalendarEvent.timeStart',
    'writable' => ['tawasulCalendarID', 'tawasulCalendarEventTypeID', 'name', 'description', 'status', 'allDay', 'dateStart', 'dateEnd', 'timeStart', 'timeEnd', 'locationType', 'locationDetail', 'locationURL', 'tawasulSpaceID', 'tawasulPersonIDOrganiser'],
    'required' => ['tawasulCalendarID', 'name', 'dateStart'],
    'methods' => ['GET', 'POST', 'PATCH', 'PUT', 'DELETE'],
],

    'staff-absences' => [
        'title' => 'Staff Absences',
        'group' => 'Operations',
        'scope' => 'staff.absence',
        'module' => 'Staff',
        'action' => 'Manage Staff Absences',
    'table' => 'tawasulStaffAbsence',
    'primaryKey' => 'tawasulStaffAbsenceID',
    'description' => 'Staff absences, their type, status and whether cover is required.',
    'select' => "SELECT tawasulStaffAbsence.tawasulStaffAbsenceID, tawasulStaffAbsence.tawasulStaffAbsenceTypeID, tawasulStaffAbsence.tawasulSchoolYearID, tawasulStaffAbsence.tawasulPersonID, tawasulStaffAbsence.reason, tawasulStaffAbsence.comment, tawasulStaffAbsence.status, tawasulStaffAbsence.coverageRequired, tawasulStaffAbsence.timestampCreator, tawasulStaffAbsenceType.name AS absenceTypeName, tawasulPerson.surname, tawasulPerson.preferredName FROM tawasulStaffAbsence JOIN tawasulPerson ON (tawasulStaffAbsence.tawasulPersonID=tawasulPerson.tawasulPersonID) LEFT JOIN tawasulStaffAbsenceType ON (tawasulStaffAbsence.tawasulStaffAbsenceTypeID=tawasulStaffAbsenceType.tawasulStaffAbsenceTypeID)",
    'yearFilter' => 'tawasulStaffAbsence.tawasulSchoolYearID',
    'filters' => ['tawasulPersonID' => 'tawasulStaffAbsence.tawasulPersonID', 'status' => 'tawasulStaffAbsence.status', 'coverageRequired' => 'tawasulStaffAbsence.coverageRequired', 'tawasulStaffAbsenceTypeID' => 'tawasulStaffAbsence.tawasulStaffAbsenceTypeID'],
    'search' => ['tawasulPerson.surname', 'tawasulPerson.preferredName'],
    'defaultSort' => 'tawasulStaffAbsence.timestampCreator DESC',
    'writable' => ['tawasulStaffAbsenceTypeID', 'tawasulSchoolYearID', 'tawasulPersonID', 'reason', 'comment', 'status', 'coverageRequired'],
    'methods' => ['GET', 'POST', 'PATCH', 'PUT', 'DELETE'],
],

    'staff-absence-dates' => [
        'title' => 'Staff Absence Dates',
        'group' => 'Operations',
        'scope' => 'staff.absence',
        'module' => 'Staff',
        'action' => 'Manage Staff Absences',
    'table' => 'tawasulStaffAbsenceDate',
    'primaryKey' => 'tawasulStaffAbsenceDateID',
    'description' => 'The individual dates covered by a staff absence.',
    'select' => "SELECT tawasulStaffAbsenceDate.*, tawasulStaffAbsence.tawasulPersonID, tawasulStaffAbsence.tawasulSchoolYearID FROM tawasulStaffAbsenceDate JOIN tawasulStaffAbsence ON (tawasulStaffAbsenceDate.tawasulStaffAbsenceID=tawasulStaffAbsence.tawasulStaffAbsenceID)",
    'yearFilter' => 'tawasulStaffAbsence.tawasulSchoolYearID',
    'filters' => ['tawasulStaffAbsenceID' => 'tawasulStaffAbsenceDate.tawasulStaffAbsenceID', 'date' => 'tawasulStaffAbsenceDate.date', 'tawasulPersonID' => 'tawasulStaffAbsence.tawasulPersonID'],
    'sort' => ['date' => 'tawasulStaffAbsenceDate.date'],
    'defaultSort' => 'tawasulStaffAbsenceDate.date DESC',
    'writable' => ['tawasulStaffAbsenceID', 'date'],
    'methods' => ['GET', 'POST', 'PATCH', 'PUT', 'DELETE'],
],

'staff-coverage' => [
    'title' => 'Staff Coverage',
    'group' => 'Operations',
    'scope' => 'staff.absence',
    'module' => 'Staff',
    'action' => 'Staff Coverage',
    'table' => 'tawasulStaffCoverage',
    'primaryKey' => 'tawasulStaffCoverageID',
    'description' => 'Cover requests and the staff assigned to them.',
    'select' => "SELECT tawasulStaffCoverage.tawasulStaffCoverageID, tawasulStaffCoverage.tawasulStaffAbsenceID, tawasulStaffCoverage.tawasulSchoolYearID, tawasulStaffCoverage.tawasulPersonID, tawasulStaffCoverage.status, tawasulStaffCoverage.requestType, tawasulStaffCoverage.tawasulPersonIDCoverage, tawasulStaffCoverage.timestampCoverage, absent.surname AS absentSurname, absent.preferredName AS absentPreferredName, cover.surname AS coverSurname, cover.preferredName AS coverPreferredName FROM tawasulStaffCoverage LEFT JOIN tawasulPerson AS absent ON (tawasulStaffCoverage.tawasulPersonID=absent.tawasulPersonID) LEFT JOIN tawasulPerson AS cover ON (tawasulStaffCoverage.tawasulPersonIDCoverage=cover.tawasulPersonID)",
    'yearFilter' => 'tawasulStaffCoverage.tawasulSchoolYearID',
    'filters' => ['tawasulStaffAbsenceID' => 'tawasulStaffCoverage.tawasulStaffAbsenceID', 'status' => 'tawasulStaffCoverage.status', 'tawasulPersonIDCoverage' => 'tawasulStaffCoverage.tawasulPersonIDCoverage'],
    'defaultSort' => 'tawasulStaffCoverage.timestampCoverage DESC',
    'writable' => ['tawasulStaffAbsenceID', 'tawasulSchoolYearID', 'tawasulPersonID', 'status', 'requestType', 'tawasulPersonIDCoverage'],
    'methods' => ['GET', 'POST', 'PATCH', 'PUT', 'DELETE'],
],

'staff-duties' => [
    'title' => 'Staff Duties',
    'group' => 'Operations',
    'scope' => 'staff.duties',
    'module' => 'Staff',
    'action' => 'Manage Staff Duty',
    'table' => 'tawasulStaffDuty',
    'primaryKey' => 'tawasulStaffDutyID',
    'description' => 'Duty rosters such as playground and bus duty.',
    'select' => "SELECT tawasulStaffDuty.* FROM tawasulStaffDuty",
    'filters' => ['type' => 'tawasulStaffDuty.type'],
    'search' => ['tawasulStaffDuty.name'],
    'defaultSort' => 'tawasulStaffDuty.sequenceNumber',
    'writable' => ['name', 'type', 'sequenceNumber'],
    'methods' => ['GET', 'POST', 'PATCH', 'PUT', 'DELETE'],
],

];
